### ISSUE TITLE
Testing code using data class copy() with mocks

### ISSUE THREAD

**Issue by rrva** [mockk/mockk#101]
If I want to test code which use data classes, and the code under test invokes `copy()`, how can I use mockk? 

The following test case does not work. But also, as a deeper question, are mocks even suitable for code that modifies the input using copy() ?

```kotlin
package foo

import io.mockk.every
import io.mockk.mockk
import org.junit.Test

class MockkDataclassCopyTest {

    data class Foo(
        val bar: String,
        val baz: String
    )

    class UnderTest {

        fun doSomething(f: Foo): Foo {
            return f.copy(baz = "aaa")
        }
    }

    @Test
    fun `testing code which uses data classes and copy() function should work with mocks`() {
        val mockFoo = mockk<Foo>()
        every { mockFoo.bar } returns ""
        UnderTest().doSomething(mockFoo)
    }

}
```

**Comment by oleksiyp** [comment]
There is few things here.

`copy` for mocked object is regular mocked function i.e. it doesn't do any copying and access "bar" property. So it is useless to define it's behavior.

Now you have two options:
Do relaxed mock:
```
val mockFoo = mockk<Foo>(relaxed = true)
mockFoo.copy(baz = "aaa")
```
and mockFoo.copy(baz = "aaa") in testing code will return one more relaxed mock.

OR

Set behavior for strict mock:
```
val mockFoo = mockk<Foo>()
every {
    mockFoo.copy(bar = any(), baz = "aaa")
} returns mockk() // or anything else
mockFoo.copy(baz = "aaa")```

**Comment by TheWishWithin** [comment]
Do you really need to mock a data class? Does it include complex logic? If so, maybe the data class is the wrong place for that? After all it's a _data_ class.
If you don't want to set up complex data objects all the time, maybe add a Kotlin file that only includes data class stubs? If you need a data object, but you only care about one specific field, you could create a copy of the stub where you're only setting this one specific field.

**Comment by oleksiyp** [comment]
Seems question is answered and no further help needed. Closing
