### ISSUE TITLE
Feature: intercept getfield/setfield JVM bytecodes

### ISSUE THREAD

**Issue by oleksiyp** [mockk/mockk#104]
### Expected Behavior

Expecting private properties to be captured by dynamic calls.

### Current Behavior

Currently, this is not supported.

**Comment by martofeld** [comment]
Any updates on this? [Documentation](https://mockk.io/#private-functions-mocking--dynamic-calls) suggests this is possible but fails with `io.mockk.MockKException: Missing calls inside every { ... } block`

**Comment by oleksiyp** [comment]
The documentation says: "Additionally more verbose syntax allows to get and set properties, do same dynamic calls", so not stating if it works for private properties. Unfortunately, this is not easy to achieve functionality. It is required to transform all places getter and setter is called. I will consider it as last priority.

**Comment by BulatMukhutdinov** [comment]
Any update on this?

**Comment by nehahemnani92** [comment]
Any update on this

**Comment by antonid08** [comment]
Up

**Comment by sdudziak** [comment]
Also up for this feature.

**Comment by isfaaghyth** [comment]
Hi @oleksiyp,
any updates for this feature?

**Comment by soroush-bn** [comment]
Any update on this ??

**Comment by Chaz0r** [comment]
An update here would be great, this is a major problem for us : /

**Comment by huangyujian** [comment]
hope to support this feature

**Comment by gustavo-pedreros** [comment]
Up!

**Comment by Nodrex** [comment]
Any update on this ??

**Comment by usease** [comment]
Any updates?

**Comment by Demetori0** [comment]
any updates?

**Comment by liuluyangdev** [comment]
顶

**Comment by rfn123** [comment]
Having same problem, any updates?
