### ISSUE TITLE
Kotlin version configured from GitHub Actions workflow is not correctly applied

### ISSUE THREAD

**Issue by SimonMarquis** [mockk/mockk#1048]
CI uses the following matrix to test Kotlin versions:

https://github.com/mockk/mockk/blob/6c7a06cedafc6b00b127a46ea304f404dcb3c180/.github/workflows/gradle.yml#L20

and propagate them as Gradle project properties:

https://github.com/mockk/mockk/blob/6c7a06cedafc6b00b127a46ea304f404dcb3c180/.github/workflows/gradle.yml#L41

MockK uses this property here:

https://github.com/mockk/mockk/blob/6c7a06cedafc6b00b127a46ea304f404dcb3c180/buildSrc/src/main/kotlin/buildsrc/config/Deps.kt#L6

but this method is unused in this project.
And therefore I suspect all jobs are using the same Kotlin version.

---

Also, I tried to run the same command as in the workflow but with an invalid Kotlin version, and it still ran the tests sucessfully:

```bash
gradlew check --stacktrace -Pkotlin.version=0.0.0 -Pkotlin.ir.enabled=true -PjavaToolchainTestVersion=17
```

**Comment by SimonMarquis** [comment]
`kotlin.ir.enabled` seems to be no longer used as well.

**Comment by aSemy** [comment]
Good spot! Removing `kotlin.ir.enabled` would really help with the tests in CI.

The dependencies versions handling was never tidied up after the big refactoring in #855

I've made a PR - let's see if the tests pass...
I'll make a PR for this.
I'll make a PR for this.

**Comment by SimonMarquis** [comment]
Kotlin-IR will be removed in #1153, but the main issue persist: `Project.kotlinVersion()` is never used.

**Comment by SimonMarquis** [comment]
@Raibaz is this really meant to be used on CI? I'm wondering what was this trying to achieve as we can only ship a single artifact, targeting a single Kotlin version 🤔

**Comment by Raibaz** [comment]
Yep it was meant to be used on CI to make sure master was building fine and tests were passing against several different Kotlin versions; specifically the tests in clientTests, which depend on MockK as if they were a client project.

It is true we ship a single artifact targeting a single Kotlin version, but we also want to ensure backwards compatibility with older versions, and that was what I was trying to ensure on CI.

Usage of `Project.kotlinVersion()` must have been mistakenly dropped when we refactored gradle files to .kts, as @aSemy mentioned, see [here](https://github.com/mockk/mockk/blob/6ce0616e16e63a5430b7f2989b0e3f0de666dd5a/build.gradle#L35)

**Comment by SimonMarquis** [comment]
Understood. Then maybe we should simply take advantage of the Kotlin BoM and only provide the version once. I'll try to come up with something unless you have a specific solution in mind.

**Comment by Raibaz** [comment]
I don't have a specific solution in mind, so any help on this (as on any other topic) is greatly appreciated <3
