### ISSUE TITLE
Mocking final static java variable from Kotlin, reflection

### ISSUE THREAD

**Issue by RafaRuiz** [mockk/mockk#107]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

Trying to mock a final static variable in Java from Kotlin such as `BuildConfig.DEBUG` in Android

### Current Behavior

Can't reflect

-------------------------------------------

Is this possible with MockK? I'm using [SuperReflect](https://github.com/dpreussler/SuperReflect) but it won't work when `testCoverageEnabled true`

**Comment by oleksiyp** [comment]
Fields are not mockable.

If you want to mock object that is referenced by "BuildConfig.DEBUG" use mockkObject.

If this answers your question close the ticket, otherwise elaborate on what should be achieved.

**Comment by RafaRuiz** [comment]
That's clever, using an object to mock those fields. 🤦‍♂️ Thanks

**Comment by afaucogney** [comment]
@RafaRuiz I have the same kind of deal with Build.VERSION.SDK_INT. How have you done ?

        mockkObject(Build.VERSION.SDK_INT)
        every { Build.VERSION.SDK_INT } returns 21

still get the issue

     io.mockk.MockKException: Missing calls inside every { ... } block.

**Comment by RafaRuiz** [comment]
As said above, I've created a class that would tell me my SDK_INT and used it everywhere. I think it's a good practice.
I called it like: `MyAppBuildConfig`.

And I defined:
fun getVersionSDKInt(): Int {
    return Build.VERSION.SDK_INT
}

then I mocked my class.

**Comment by calvarez-ov** [comment]
Argh, I have checks on `Build.VERSION.SDK_INT` everywhere in the code base... Don't really want to replace these all with a custom function 😞

**Comment by calvarez-ov** [comment]
Anybody interested in a lazy bad practice solution 😃 : this works:
```kotlin
    // https://stackoverflow.com/questions/38074224/stub-value-of-build-version-sdk-int-in-local-unit-test/38074424
    private fun mockSdkInt(sdkInt: Int) {
        val sdkIntField = Build.VERSION::class.java.getField("SDK_INT")
        sdkIntField.isAccessible = true
        Field::class.java.getDeclaredField("modifiers").also {
            it.isAccessible = true
            it.set(sdkIntField, sdkIntField.modifiers and Modifier.FINAL.inv())
        }
        sdkIntField.set(null, sdkInt)
    }
```

**Comment by roshaan-sadapay** [comment]
Unable to mock BuildConfig fields.
  
 private fun mockSdkInt(sdkInt: Int) {
        val sdkIntField = BuildConfig.VERSION::class.java.getField("VERSION_CODE")
        sdkIntField.isAccessible = true
        Field::class.java.getDeclaredField("modifiers").also {
            it.isAccessible = true
            it.set(sdkIntField, sdkIntField.modifiers and Modifier.FINAL.inv())
        }
        sdkIntField.set(null, sdkInt)
    }

**Comment by AlejandroHCruz** [comment]
It also doesn't work for me. Any ideas about what could be wrong?

```
        private fun mockBuildConfigString(fieldString: String, value: String) {
            val field = BuildConfig::class.java.getField(fieldString)
            field.isAccessible = true
            Field::class.java.getDeclaredField("modifiers").also {
                it.isAccessible = true
                it.set(field, field.modifiers and Modifier.FINAL.inv())
            }
            field.set(null, value)
        }
```

**Comment by bnovakovic** [comment]
@roshaan-sadapay & @AlejandroHCruz and others... 
what's stopping you from using this?

```
mockkObject(your_object)
every {your_object.some_variable} returns another_variable
```

Works perfectly for me

**Comment by xyz-fly** [comment]
> Anybody interested in a lazy bad practice solution 😃 : this works:
> 
> ```kotlin
>     // https://stackoverflow.com/questions/38074224/stub-value-of-build-version-sdk-int-in-local-unit-test/38074424
>     private fun mockSdkInt(sdkInt: Int) {
>         val sdkIntField = Build.VERSION::class.java.getField("SDK_INT")
>         sdkIntField.isAccessible = true
>         Field::class.java.getDeclaredField("modifiers").also {
>             it.isAccessible = true
>             it.set(sdkIntField, sdkIntField.modifiers and Modifier.FINAL.inv())
>         }
>         sdkIntField.set(null, sdkInt)
>     }
> ```

JDK11 to JDK12  java.lang.NoSuchFieldException: modifiers

so, I improved the above code and added a section like this:

```kotlin
 private fun mockSdkInt(sdkInt: Int) {
        val sdkIntField = Build.VERSION::class.java.getField("SDK_INT")
        sdkIntField.isAccessible = true
        getModifiersField().also {
            it.isAccessible = true
            it.set(sdkIntField, sdkIntField.modifiers and Modifier.FINAL.inv())
        }
        sdkIntField.set(null, sdkInt)
    }

    private fun getModifiersField(): Field {
        return try {
            Field::class.java.getDeclaredField("modifiers")
        } catch (e: NoSuchFieldException) {
            try {
                val getDeclaredFields0: Method =
                    Class::class.java.getDeclaredMethod("getDeclaredFields0", Boolean::class.javaPrimitiveType)
                getDeclaredFields0.isAccessible = true
                val fields = getDeclaredFields0.invoke(Field::class.java, false) as Array<Field>
                for (field in fields) {
                    if ("modifiers" == field.name) {
                        return field
                    }
                }
            } catch (ex: ReflectiveOperationException) {
                e.addSuppressed(ex)
            }
            throw e
        }
    }
```

**Comment by marcelofilho** [comment]
Has any good hearted person ever found a solution for java 17?

**Comment by michedsa** [comment]
any news for Java17? How to mock final fields?

**Comment by sergestanislavsky** [comment]
last comments about java 17 can be fixed by adding this part to gradle
```
 testOptions {
       ...
        unitTests.all {
            jvmArgs(
                    "--add-opens", "java.base/java.lang=ALL-UNNAMED",
                    "--add-opens", "java.base/java.lang.reflect=ALL-UNNAMED"
            )
        }
     ...
    }
```
or to your command 
`--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED`

**Comment by balazsbanyai** [comment]
In case of the android Build class, you don't need to mock it at all. Just add a java class in your test sourceSet matching the android Build class package and signature, like this:
```java
package android.os;

public class Build {
    public static class VERSION {
        public static String RELEASE = "11";
        public static int SDK_INT = 30;
    }
}

```

You can then go ahead and set the fields in the tests as you please.
`Build.VERSION.SDK_INT = 42`
