### ISSUE TITLE
The 'returnsArgument' stub for methods with context receivers has misleading behavior

### ISSUE THREAD

**Issue by vstepchik** [mockk/mockk#1102]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The `every { ... } returnsArgument N` stub makes the mocked method return the argument at the given index position regardless of the presence of context receivers.

### Current Behavior

The mocked method returns the argument at the index-specified position, but context comes first before the arguments. So if the method signature is: 
```kotlin
context (Ctx)
fun action(foo: Foo, bar: Bar): Foo { // ...
```
the `returnsArgument 0` stub will make the method return `Ctx` and fail with ClassCastException instead of returning `Foo`.

### Sample code

```kotlin
    data class SomeContext(val userName: String)

    class TestSubjectDependency {
        context (SomeContext)
        fun addUserName(input: String): String = "$input, $userName"
    }

    class TestSubject(val testSubjectDependency: TestSubjectDependency) {
        context (SomeContext)
        fun greet(): String = testSubjectDependency.addUserName("Hello")
    }

    @Test
    fun `failing test`() {
        val testSubjectDependency: TestSubjectDependency = mockk()
        val context = SomeContext(userName = "Bob")
        val testSubject = TestSubject(testSubjectDependency)

        every {
            with (context) {
                testSubjectDependency.addUserName(any())
            }
        } returnsArgument 0 // I want it to return "Hello", but argument 0 is the context

        val actualGreeting = with (context) {
            testSubject.greet()
        }

        assertEquals("Hello", actualGreeting)
    }
```

The test will pass if `returnsArgument 0` is changed to `returnsArgument 1`, otherwise it throws
```
class com.example.MockkContextReceiverTest$SomeContext cannot be cast to class java.lang.String (com.example.MockkContextReceiverTest$SomeContext is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class com.example.MockkContextReceiverTest$SomeContext cannot be cast to class java.lang.String (com.example.MockkContextReceiverTest$SomeContext is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at com.example.MockkContextReceiverTest$TestSubjectDependency.addUserName(MockkContextReceiverTest.kt:410)
	at com.example.MockkContextReceiverTest$TestSubject.greet(MockkContextReceiverTest.kt:415)
	at com.example.MockkContextReceiverTest.failing test(MockkContextReceiverTest.kt:431)
	...
```

#### Context

* MockK version: 1.13.4
* OS: MacOS 13.4
* Kotlin version: 1.8.22
* JDK version: 17.0.1
* JUnit version: 5.7.2
* Type of test: unit test

**Comment by Raibaz** [comment]
If you look at how `with` is implemented (described in detail [here](https://stackoverflow.com/a/68505794/1454)), it makes perfect sense and, imho, mockk's behavior is what you'd expect in this case.

**Comment by vstepchik** [comment]
@Raibaz I agree that it does make perfect sense **after** you realize why argument 0 is the context object and not the 1st parameter in function parentheses. And indices of the parameters will be offset by the number of contexts the function receives.

I decided to create the issue because a person spent a few hours of debugging trying to figure out why he is receiving ClassCastException, and hoped maybe there is a way to make the behavior more explicit, even if it is a "Note" section under documentation for `returnsArgument` stub, maybe it will save time for other people.
