### ISSUE TITLE
Mockk making tests to run very slowly 

### ISSUE THREAD

**Issue by luis-possatti** [mockk/mockk#1113]
## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules.
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
- Write a bunch of unit tests containing `Mockk` mocks and have a smooth test execution time after framework initialization. 

### Current Behavior

1. First test class takes sometime to execute (this is fine.)
2. Next 2 or 3 test classes executes lighting fast.
3. The next test class takes some seconds to execute.
4. Next 2 or 3 test classes executes lighting fast.
5. ...
6. All tests are executed

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce
 - I've set up a minimum project to reproduce this issue. Please, take a look here: https://github.com/luis-possatti/slow-tests-with-mockk

   - This project has basically 3 branchs:
     - [mainline](https://github.com/luis-possatti/slow-tests-with-mockk/tree/mainline):
       - this branch reproduces the issue with the setup of my real project: JDK 11 and using Mockk
     - [without-mockk](https://github.com/luis-possatti/slow-tests-with-mockk/tree/without-mockk)
       - this branch just remove the mocks (and use stubs in tests) to show that the issue is related to Mockk.
     - [mockk-with-java-17](https://github.com/luis-possatti/slow-tests-with-mockk/tree/with-mockk-java-17)
       - this branch shows that changing JDK 11 to JDK 17 reduces the impact of the issue, but seems that it does not eliminate it.

   - In every branch is necessary only to execute `./gradlew test`.
   - All branches contain the respective unit test report at `lib/reports` to make it easy to check the behaviour I am describing here.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.5
* OS: macOs
* Kotlin version: 1.8.10
* JDK version: 11
* JUnit version: 5
* Type of test: unit test with `Kotest 5.6.2` 

#### Failure Logs

In all three cases below, I am executing unit tests with 30 test classes with 2 test each. All the tests follow the same template:
 - Have one test object that has a single dependence. This dependence is mocked with mockk.

##### Mockk + Java 11
 - total execution time: 17.444 seconds.
 - first test executed takes some seconds, a few other tests are quite fast. Then next test takes some seconds, then a few are quite fast.
<img width="1054" alt="Screen Shot 2023-07-06 at 18 54 20" src="https://github.com/mockk/mockk/assets/8042139/4dd7acc3-5e60-4219-b06e-4123e48af21a">
<img width="977" alt="Screen Shot 2023-07-06 at 18 54 29" src="https://github.com/mockk/mockk/assets/8042139/c961c51a-1c0a-4ea0-9633-a9293d74080f">

##### Mockk + Java 17
 - same pattern happens with Java 17, but the tests that takes too long now takes some hundred of milliseconds.
![Screen Shot 2023-07-06 at 18 57 00](https://github.com/mockk/mockk/assets/8042139/7491b7ea-657b-4f40-9d81-81406712cff2)

##### JDK11 without mockk
 - very first test takes some seconds. Then **all** other tests executes lightning fast.
![Screen Shot 2023-07-06 at 19 00 04](https://github.com/mockk/mockk/assets/8042139/c5eb8e8b-e500-4b1b-81b7-74848148c64d)

**Comment by luis-possatti** [comment]
This behavior makes my real project test suite to take something like 2 minutes.

In my real setup, I am using JDK 11.

-----

I would like to know if this is a known issue if there is at least a workaround to make JDK 11 performance to match the performance that I get with JDK 17, which seems to have the same issue but lower impact.

**Comment by MaciejCzekanski** [comment]
Interesting to see such big difference on java17. 

My results are:
baseline: 2.487s
java17: 0.421s
no mockk: 0.399s

Java 17 result is fantastic and not much slower than not using mockk at all. My machine is M1 Pro Macbook.
