### ISSUE TITLE
Unable to match anonymous object

### ISSUE THREAD

**Issue by EnzoMolionDiabeloop** [mockk/mockk#1115]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected behavior 

I am trying to verify a `logger::error` method called like this: 

```Kotlin
logger.error(MY_ENUM_VALUE, object {
    val field0 = field0Value
    val field1 = field1Value
})
```

I wonder how to match the anonymous object, something (type accurate) that would look around something like this:
```kotlin 
verify {
    loggerMock.error(MY_ENUM_VALUE, match { it.field0 = theField0Value && it.field1 = theField1Value})
}
```

### Issue on degraded matching 

I tried this degraded version: 
```kotlin 
verify {
    loggerMock.error(MY_ENUM_VALUE, any()
}
```
But I get a weird error code: 
> Verification failed: call 1 of 1: DblLogger(loggerMock#2).error(eq(MY_ENUM_VALUE), any())) was not called.
> Calls to same mock:
> 1) DblLogger(loggerMock#2).error(MY_ENUM_VALUE, my.package.myClass$myFunction$memoryAddress>)

To me, `DblLogger(loggerMock#2).error(eq(MY_ENUM_VALUE), any()))` should've matched `DblLogger(loggerMock#2).error(MY_ENUM_VALUE, my.package.myClass$myFunction$memoryAddress>)`

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.2
* OS: Windows 10
* Kotlin version: 1.7.21
* JDK version: 11
* JUnit version: 4.13.2
* Type of test: unit test

**Comment by EnzoMolionDiabeloop** [comment]
**Note:** 
I turned out `logger::error` had several overloads among which `fun error(tag: MyEnumType, message: String): Unit` and `any()` was thus inferred to `String`. 

Writing 
```kotlin
verify { loggerMock.error(MY_ENUM_VALUE, any<Any>() }
```
makes the degraded version work.

**Comment by vincepandolfo** [comment]
As you are using an anonymous object, there is no way to access the properties directly in your matcher. You can, however, use reflection to access properties by their name. The accepted answer on [this StackOverflow question](https://stackoverflow.com/questions/48158909/java-android-kotlin-reflection-on-private-field-and-call-public-methods-on-it) provides an implementation that should work.

If possible, I would recommend refactoring your code to define an interface the anonymous object will implement:

```kotlin
interface ThingToLog {
   val field0: A
   val field1: B
}

[...]
    logger.error(
        MY_ENUM_VALUE,
        object : ThingToLog{
             override val field0 = field0Value
             override val field1 = field1Value
        }
    )
[...]
```

You will then be able to match on the fields without the need for any reflective access:
```kotlin
verify {
    loggerMock.error(MY_ENUM_VALUE, match<ThingToLog> { it.field0 = theField0Value && it.field1 = theField1Value})
}
```

**Comment by Raibaz** [comment]
@vincepandolfo's suggestion is correct.
