### ISSUE TITLE
Offer for MockK Team - Contact Request

### ISSUE THREAD

**Issue by Jonas1893** [mockk/mockk#1124]
Hi @aSemy ,

Apologies for using the GitHub ticket system. We reached out to @oleksiyp via email but received no response. We have something valuable to offer the MockK team and would like to share details privately.

If interested, please email us at [abdul.khan@mercedes-benz.com](mailto:abdul.khan@mercedes-benz.com).
Thank you.

**Comment by aSemy** [comment]
Hi @Jonas1893, I'm just an occasional contributor, @Raibaz is the best person to speak to. You can also try reaching out via the [Kotlin Slack](https://slack.kotlinlang.org) in [`#mockk`](https://slack-chats.kotlinlang.org/c/mockk)

**Comment by Jonas1893** [comment]
Thank you!
