### ISSUE TITLE
Front page documentation does not get one started quickly

### ISSUE THREAD

**Issue by binkley** [mockk/mockk#1137]
The frontpage documentation at https://mockk.io/ does not provide at the top a how to get started. When I want to pull in a cool library, first thing I need is how to use it in my project. Initial setup with Gradle or Maven would be a speed up in the onboarding ramp for projects to adopt MockK.

An example (among many) for developer-oriented documentation is https://www.yegor256.com/2019/04/23/elegant-readme.html. The "installation" instructions should appear near the top (https://mockk.io/#installation): developers know to look up mockk in searches, and want to get started.

Side note: the installation instructions do not provide the current version for MockK dependencies, so one must research that further if copy/paste.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

"found no answer" is not a correct choice for this issue

### Expected Behavior

The public page for MockK provides a "getting started" section at the top with instructions for using MockK with Gradle or Maven.

### Current Behavior

The current public page for MockK begins with article, references, and recommendations. This is the case also for the GitHub page.

**Comment by Raibaz** [comment]
Thanks for noticing this!

I restructured the README.md file to make the "Getting started" section more prominent at the top.

**Comment by binkley** [comment]
@Raibaz Looks good -- thanks!
