### ISSUE TITLE
Reduce the use of spread operator to improve performance.

### ISSUE THREAD

**Issue by k163377** [mockk/mockk#1139]
I found some code that takes `vararg` as an argument and uses the spread operator to call another function that takes `vararg` as an argument.
In particular, the code that calls `io.mockk.MockKDsl`.

Spread operator is expensive operation, such as generating a copy of an array.
Therefore, it is better to use `List` to communicate internally to improve performance.

If this proposal looks good, I would like to submit a PR regarding modifications to `internal` functions.

## Benchmark score
A simple benchmark comparison shows an improvement of just under 1.2x in throughput.

```
Benchmark          Mode  Cnt        Score        Error  Units
Benchmark.list    thrpt    4  4789181.882 ± 765260.680  ops/s
Benchmark.vararg  thrpt    4  4035049.285 ± 543861.224  ops/s
```

The benchmarks performed are as follows

```kotlin
import org.openjdk.jmh.annotations.Benchmark
import org.openjdk.jmh.annotations.Level
import org.openjdk.jmh.annotations.Scope
import org.openjdk.jmh.annotations.Setup
import org.openjdk.jmh.annotations.State
import kotlin.random.Random

@State(Scope.Benchmark)
open class Benchmark {
    lateinit var arr: Array<String>

    @Setup(Level.Trial)
    fun setUp() {
        arr = Array(5) { Random.nextInt(10).toString() }
    }

    private inline fun _vararg(vararg args: String) = args.joinToString(separator = ", ")

    private inline fun _list(args: List<String>) = args.joinToString(separator = ", ")

    @Benchmark
    fun vararg() = _vararg(*arr)

    @Benchmark
    fun list() = _list(arr.asList())
}
```

https://github.com/k163377/vararg-benchmark

**Comment by Raibaz** [comment]
Thanks for looking into this!

The idea definitely looks good, provided that we don't change the external API I'm definitely in favor of improving the inner workings of the framework.

**Comment by k163377** [comment]
> don't change the external API

Yes, that was my intention as well.

I will try to work on this when I have time.

**Comment by k163377** [comment]
PR submitted.
#1143
