### ISSUE TITLE
JVM-Target changed in latest releases?

### ISSUE THREAD

**Issue by jschneider** [mockk/mockk#1173]
Today I updated mockk to 1.13.8 (from 1.13.7)

Now, I get this error message:
`e: file:///home/johannes/projects/com.cedarsoft.monorepo/internal/open/meistercharts/meistercharts-history/meistercharts-history-core/src/jvmTest/kotlin/com/meistercharts/history/QueryInfoHistoryStorageTest.kt:30:35 Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option
`

I suspect, that mockk is build with a new language level now?

Could you add this to the release notes? We are stuck with JDK 1.8 for now. Therefore, I will have to stay on an older mockk version.

**Comment by igorwojda** [comment]
This issue was covered here
https://github.com/mockk/mockk/issues/1168

**Comment by alsoba13** [comment]
I have the same problem but for kotlin:
```Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.```

And version 1.13.9 doesn't seem to fix this one

**Comment by jschneider** [comment]
I upgrade to 1.13.9. Everything works as expected for me.
@alsoba13 Your problem seem to be related to the Kotlin version. Not the JVM version.
