### ISSUE TITLE
Does 1.13.8 version require jvm 11?

### ISSUE THREAD

**Issue by xiaoqian0408** [mockk/mockk#1197]
Hi, recently I just upgraded mockk from 1.13.7 to 1.13.8, then our unit test cases failed due to this error:

> Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

In our project, the jvm target is 1.8. Seems we can't use 1.13.8 in our project, does it request jvm 11?

Thanks

**Comment by TWiStErRob** [comment]
This is a duplicate of https://github.com/mockk/mockk/issues/1168
