### ISSUE TITLE
Readme file example doesn't work

### ISSUE THREAD

**Issue by hunterchung** [mockk/mockk#122]
## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The example in readme file should run without exception.
```
@ExtendWith(MockKExtension::class)
class Test {
  @MockK
  lateinit var car1: Car

  @RelaxedMockK
  lateinit var car2: Car

  @MockK(relaxUnitFun = true)
  lateinit var car3: Car

  @SpyK
  val car4 = Car()

  @Test
  fun calculateAddsValues1() {
      // ... use car1, car2, car3 and car4
  }
}
```

### Current Behavior

1. Compile error for `@Test` because the class name is `Test`, which is overlaped with `org.junit.Test`.
1. `@SpyK val car4 = Car()` cause exception:
```
io.mockk.MockKException: Annotation @io.mockk.impl.annotations.SpyK(name=, recordPrivateCalls=true) present on car4 read-only property, make it read-write please('lateinit var' for example)
```
1. `@InjectMockKs val trafficSystem = TrafficSystem()` has the same exception as above.

### Solution
1. Make class name other than `Test`
1. Change from `val` to `var`
1. Same as above.

**Comment by oleksiyp** [comment]
Thanks for reporting it

**Comment by oleksiyp** [comment]
Fixed readme
