### ISSUE TITLE
Mock a nullable value class => ClassCastException

### ISSUE THREAD

**Issue by CedrickFlocon** [mockk/mockk#1258]
Trying to update mockk from `1.13.10` to `1.13.11` break some tests. 

### Reproducible example 
````kotlin
package com.cedrickflocon

import io.mockk.every
import io.mockk.mockk
import org.junit.jupiter.api.Test

class ExampleTest {

    class Foo(val result: Result<String>?)

    @Test
    fun nullableTest() {
        val foo = mockk<Foo>()
        every { foo.result } returns Result.failure(Exception())
        println(foo.result?.isFailure)
    }
}
```` 

### Stack trace
````
class kotlin.Result$Failure cannot be cast to class kotlin.Result (kotlin.Result$Failure and kotlin.Result are in unnamed module of loader 'app')
java.lang.ClassCastException: class kotlin.Result$Failure cannot be cast to class kotlin.Result (kotlin.Result$Failure and kotlin.Result are in unnamed module of loader 'app')
	at com.cedrickflocom.ExampleTest$Foo.getResult-xLWZpok(ExampleTest.kt:9)
	at com.cedrickflocom.ExampleTest.nullableTest(ExampleTest.kt:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
````

### Version
* MockK version: 1.13.11
* OS: Apple M1 14.4.1
* Kotlin version: 1.9.23
* JDK version: 17
* JUnit version: 5.10.2
* Type of test: unit test

**Comment by Kulesko** [comment]
Just my two cents: a nullable Result is a Kotlin anti-pattern because it undermines the purpose of a Result being a success or failure. I have modified the suggested Test and could not reproduce the issue.

```kotlin
class Box<T>(t: T) {
    val value = t
}

class Foo(val result: Box<String>?)

@Test
fun nullableTest() {
    val foo = mockk<Foo>()
    every { foo.result } returns Box("foo")
    assertNotNull(foo.result?.value)
}
```

**Comment by CedrickFlocon** [comment]
>I have modified the suggested Test and could not reproduce the issue.

You didn't modified the suggested Test. You modified the code under test. Which is probably not what you should do if you want to investigate into a reported issue.


 >Just my two cents: a nullable Result is a Kotlin anti-pattern because it undermines the purpose of a Result being a success or failure.

Why it can't be undefined ? 
Does an `Int?` is a Kotlin anti-pattern because it undetermines the purpose of an int being between [`Int.Min`, `Int.Max`] ?

On the title you can see : `Mock a nullable value class => ClassCastException`

This is reproductible with any value class out side of the module.
Other e.g :  
````
    class Foo(val result: UInt?)

    @Test
    fun nullableTest() {
        val foo = mockk<Foo>()
        every { foo.result } returns 12u
    }
````

Also embedded the value class inside the module lead to another stack trace 

````
    @JvmInline
    value class ValueClass(val value: Int)

    class Foo(val result: ValueClass?)

    @Test
    fun nullableTest() {
        val foo = mockk<Foo>()
        every { foo.result } returns ValueClass(1)
    }
````

````
io.mockk.MockKException: Class cast exception happened.
Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method.
````

**Comment by VasilisDrettas-tomtom** [comment]
@CedrickFlocon is this maybe the same issue as https://github.com/mockk/mockk/issues/813 ?
I merge a fix for that issue and I think your latest example is also fixed by it.

**Comment by CedrickFlocon** [comment]
Yes it is, thanks for the follow up 👍
