### ISSUE TITLE
After invoking mockk; the mocked ::class.java constructor is overriden in the JVM

### ISSUE THREAD

**Issue by TarodBOFH** [mockk/mockk#129]
- [X] I am running the latest version (1.8.6)
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed (but looks similar to https://github.com/mockk/mockk/issues/126 )

### Expected Behavior

After invoking mockk() to mock an object (not a class!); the constructor parameters of the mocked class (not the object) are the same than before calling mockk();

### Current Behavior

After invoking mockk() the JVM constructor is replaced and the parameters, even if they keep order and type, do not keep the names (they change to arg0, arg1, arg2... etc.)

### Failure Information (for bugs)

See the attached gist.

This might be caused by some external tool using older class version or different target implementations when generating code (see https://stackoverflow.com/questions/21455403/how-to-get-method-parameter-names-in-java-8-using-reflection/21455958#21455958 for reference). The parameter names are part of JDK 8 and JVM dependent. I don't know why mocking a specific object requires to alter the constructor of the class and if this should be the expected behavior

#### Steps to Reproduce

Gist attached:
https://gist.github.com/TarodBOFH/fd3c61fdac611fad9678f1d981419cf7 (test)
https://gist.github.com/TarodBOFH/5bbb1d1907f2a0e4c7ce58e0fa3560de (.gradle)
 
Due to the imposibility of JUnit 5 (yet) to specify the test order two tests have been provided. Run them separately; once a call has been made to mockk() the tests fill fail.

#### Context

I was writing a test for a module and suddenly other test suites started to fail. Digging deeper it turned that jooq was not able to retrieve the parameter names of a constructor after any instance of that class had been mocked using mockk(). I dug in the code and I was able to isolate the problem to the constructor being changed after mocking.

* MockK version: 1.8.6
* OS: Windows 10; MacOS 10.13.6; docker alpine 3.7
* Kotlin version: 1.2,59
* JDK version: 8
* Type of test: Unit Test
* Gradle Version: 4.8.1

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
repositories {
    jcenter()
    mavenCentral()
}

buildscript {
    repositories {
        mavenCentral()
    }

     dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.51"
    }
}

group 'org.tarodbofh.medium'
version '1.0-SNAPSHOT'

apply plugin: 'kotlin'

dependencies {
    testCompile "io.mockk:mockk:1.8.5"
    testCompile "org.junit.jupiter:junit-jupiter-api:5.2.0"
    testRuntime "org.junit.jupiter:junit-jupiter-engine:5.2.0"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

test {
    testLogging {
        exceptionFormat = 'full'
    }

    useJUnitPlatform {
    }

    systemProperties = [
            'org.junit.platform.console.options.Details': 'tree',
            'spring.profiles.active': 'local-test'
    ]
}

[compileKotlin, compileTestKotlin]*.kotlinOptions*.javaParameters   = true

// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package org.tarodbofh.medium.mockk

import io.mockk.clearMocks
import io.mockk.mockk
import io.mockk.unmockkAll
import org.junit.jupiter.api.Test

internal class MockkMessingNativeJVM {
    @Test
    fun testConstructorGetParametersMocked() {
        var parameters = DataClass::class.java.constructors[0].parameters

        assert(parameters.map { it.name }.contains("name"))
        assert(parameters.map { it.name }.contains("age"))

        // inject a mockk object to alter native constructor.getParameters
        val instance: DataClass = mockk()

        clearMocks()
        unmockkAll()

        parameters = DataClass::class.java.constructors[0].parameters

        assert(parameters.map { it.name }.contains("name"))
        assert(parameters.map { it.name }.contains("age"))
    }

    @Test
    fun testConstructorEqualityAfterClearMocks() {
        val javaClass = DataClass::class.java

        val constructor = DataClass::class.java.constructors[0]

        assert(javaClass.constructors.size == 1)

        // inject a mockk object to alter native constructor.getParameters
        val instance: DataClass = mockk()

        clearMocks()
        unmockkAll()

        assert(javaClass === DataClass::class.java)
        assert(constructor.parameterCount == DataClass::class.java.constructors[0].parameterCount)
        assert(constructor === DataClass::class.java.constructors[0])
    }

}

data class DataClass(val name: String, val age: Int)

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Thank you for reporting it

**Comment by TarodBOFH** [comment]
Hey, I'm not sure if this will help you somehow, but I dag out and I found this bug on mockito https://github.com/mockito/mockito/issues/695 which got its regresion https://github.com/mockito/mockito/issues/764 

It seems either a regression on bytebuddy or an old version.

I have experienced a similar error with Mockito but I have been able to reproduce it on alpine:3.7 using latest jdk and as the mockito reports state, happens apparantly randomly.

**Comment by oleksiyp** [comment]
Interesting

**Comment by oleksiyp** [comment]
I implemented a fix analogous to mockito one. Let's see if it passes all the tests. btw this `assert(constructor === DataClass::class.java.constructors[0]) ` shouldn't pass because every time `getConstructors` returns new array and new instances of `Constructor` class.

**Comment by oleksiyp** [comment]
Version 1.8.7 is released please check if it fixes your issue.

**Comment by TarodBOFH** [comment]
I can confirm the tests are passing now. This should solve my issue. I will replace some mockito mocks with mockk one in the real test code and let you know if I run into any other issues.

Thank you very much!

In order to fix the failing test I forgot to remove an `=` on it; sry!

**Comment by TarodBOFH** [comment]
👍 🥇 I am using now mockk on production code and it is working perfectly. Great job and thank you!
