### ISSUE TITLE
[1.13.13] ClassCastException when mocking function returning a nullable value class containing another value class

### ISSUE THREAD

**Issue by felixkrull-neuland** [mockk/mockk#1308]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Can mock a function returning a nullable value class containing another value class

### Current Behavior

ClassCastException when calling the mocked function returning aforementioned value class sandwich

### Failure Information (for bugs)

This is a regression from 1.13.12 to .13 when returning nested value classes from a mocked function. 

#### Steps to Reproduce

1. have a value class
2. have another value class containing the first value class
3. have a function returning the second value class, nullable
4. mock the function
5. call the mocked function

Removing the nullability makes the problem go away, as does moving the nullability into either of the value classes.

#### Context

I'm guessing this is related to the fix for https://github.com/mockk/mockk/issues/813

#### Stack trace

```
Exception in thread "main" java.lang.ClassCastException: class Outer cannot be cast to class java.lang.String (Outer is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at Cls.returnValueClass-dzOYYKU(Repro.kt:11)
	at ReproKt.main(Repro.kt:17)
	at ReproKt.main(Repro.kt)

```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// --------- Gradle deps
dependencies {
    implementation("io.mockk:mockk:1.13.13")
}

// --------- code ---------
import io.mockk.every
import io.mockk.mockk

@JvmInline
value class Inner(val underlying: String)

@JvmInline
value class Outer(val inner: Inner)

open class Cls {
    fun returnValueClass(): Outer? = null
}

fun main() {
    val mock = mockk<Cls>()
    every { mock.returnValueClass() } returns Outer(Inner("mock"))
    println(mock.returnValueClass())
}
```

**Comment by TWiStErRob** [comment]
Even simpler:

```
@JvmInline
value class V(val underlying: String)

interface Subject {
    fun returnValueClass(): V?
}

    @Test
    fun test() {
        val mock = mockk<Subject>()
        every { mock.returnValueClass() } returns V("data")

        val ret = mock.returnValueClass()

        assertEquals(V("data"), ret)
    }
```

Changing to non-null (= removing `?` from interface) works as expected.

**Comment by NickyNOS** [comment]
@dependabot ignore this patch version

**Comment by TWiStErRob** [comment]
@Raibaz this prevents us from updating to latest patch version, which in turn blocks us from using Kotlin 2. How can we move this along?

**Comment by TWiStErRob** [comment]
cc @VasilisDrettas-tomtom
