### ISSUE TITLE
Help needed: unit testing private methods

### ISSUE THREAD

**Issue by wfeng-fsde** [mockk/mockk#134]
## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

I want to be able to unit test private methods. 

### Current Behavior

Right now when I try with `MyClass["myPrivateFun"](myArgs)` I get 2 errors when I try to run it:
1. Error:(68, 17) Kotlin: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
@InlineOnly public operator inline fun <@OnlyInputTypes K, V> Map<out String, ???>.get(key: String): ??? defined in kotlin.collections
@SinceKotlin public operator fun MatchGroupCollection.get(name: String): MatchGroup? defined in kotlin.text
2. Error:(68, 34) Kotlin: No get method providing array access

I also tried `MyClass.myPrivateFun(myArgs)` which of course didn't work because the function is private.

My question is: Can I do this somehow with the current mockk? If not, could it be considered a feature request?

**Comment by Kerooker** [comment]
I don't believe you can mock inline methods, and the stack trace seems to point in that direction.

Can you provide a minimum and verifiable example? Something like
```
class Foo {

private fun bar() {
    //This will give me an error!
}
}

@Test
fun testBar() {
every {........}
}
```

**Comment by wfeng-fsde** [comment]
here's a minimal example:

    class MyTest {
        class Foo {
            fun doSomething() : Boolean {
                return doSomethingPrivate()
            }
            private fun doSomethingPrivate() : Boolean {
                println("doing something")
                return true
            }
        }
        @Test
        fun testFoo() {
            val foo = spyk(Foo())
            assertTrue(foo.doSomething())

            val u = foo["doSomethingPrivate"]()
            assertTrue(u)
        }
    }
The error is the same as what I included in the original issue description.

**Comment by Kerooker** [comment]
Unfortunately, this isn't how Mockk's private mocking works.

`foo["doSomethingPrivate"]()` should only be used in a mocking scope, for instance:

```
@Test
fun testFoo() {
val foo = spyk(Foo())

every {  foo["doSomethingPrivate"]()  } returns false      //Mocking here
assertFalse(foo.doSomething()) 
```

As a word of advice: testing a private method is a big code smell! You should always test your public interface for other classes (for instance, the doSomething method), and not the private methods! They're not exposed to whoever is using them (not even yourself :P).

You should always test the public methods.
More information on testing private methods in [this stackoverflow question](https://stackoverflow.com/questions/34571/how-do-i-test-a-private-function-or-a-class-that-has-private-methods-fields-or)

**Comment by Kerooker** [comment]
If you want more assistance with your testing, hit me up at Kotlin's slack:
kotlinlang.slack.com

For now: I don't believe this issue is in Mockk's scope. Do you think the lib could assist you in anyway given my explanation?

**Comment by wfeng-fsde** [comment]
OK. My private method was small and only does one thing. I guess I'll just test it through a public method then. Thanks for the help.
