### ISSUE TITLE
`every {} just Runs` on unit returning method of spyk object won't compile

### ISSUE THREAD

**Issue by wfeng-fsde** [mockk/mockk#135]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

I created `myObj` with `spyk`. Then I expect to be able to do `every { myObj.unitReturningMethod() } just Runs` on `myObj` to stub the function `unitReturningMethod` such that I can check if it was ever called in my tests.

### Current Behavior

The code won't compile.

### Failure Information (for bugs)

The error being reported is: 
`Error:(165, 9) Kotlin: Type mismatch: inferred type is MockKStubScope<Any?, Any?> but MockKStubScope<Unit, Unit> was expected`

#### Steps to Reproduce

Minimal reproducible code.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.6
* OS: macOS High Sierra version 10.13.6
* Kotlin version: 1.2.60
* JDK version: 1.8
* JUnit version: 4
* Type of test: unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
No stack trace. Compile errors. The error is:
Error:(165, 9) Kotlin: Type mismatch: inferred type is MockKStubScope<Any?, Any?> but MockKStubScope<Unit, Unit> was expected
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testCompile group: 'org.apache.kafka', name: 'kafka_2.12', version: '1.1.0'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
class MyTest {
    class Foo {
        fun doSomething() : Boolean {
            doSomethingPrivate("description", 3)
            return true
        }
        private fun doSomethingPrivate(a: String, b: Int) {
            println("doing something: $a, $b")
        }
    }

    @Test
    fun testFoo() {
        val foo = spyk(Foo())
        every { foo["doSomethingPrivate"](any<String>(), any<Int>()) } just Runs
        assertTrue(foo.doSomething())
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

### Caveat
I can make the code compile and run just fine if I replace the `just Runs` part with `returns Unit` or `returns null`. Why?

**Comment by Kerooker** [comment]
I believe the reason for this is that at compile time we can't be sure that `foo.doSomethingPrivate` actually returns unit.

Given the class

```
 class Foo {
        fun doSomething() : Boolean {
            doSomethingPrivate("description", 3)
            return true
        }
        
        fun bar() {
        
        }
        
        private fun doSomethingPrivate(a: String, b: Int) {
            println("doing something: $a, $b")
        }
    }
```

When we try to mock `bar` behavior, we know for sure that it's Unit, the compiler ensures that. When it's a call via reflection, we can't be sure it's Unit, so it's returned `Any`.

The `just` infix function only works for Unit methods:
```
/**
 * Part of DSL. Answer placeholder for Unit returning functions.
 */
@Suppress("UNUSED_PARAMETER")
infix fun MockKStubScope<Unit, Unit>.just(runs: Runs) = answers(ConstantAnswer(Unit))
```

This is the reason you can't `just Runs` in a dynamic call.

**Comment by Kerooker** [comment]
What you can do, as a workaround, but I think it's ugly:

Cast the private function to unit:
```
@Test
    fun testFoo() {
        val foo = spyk(Foo())
        every { foo["doSomethingPrivate"](any<String>(), any<Int>()) as Unit } just Runs
        assertTrue(foo.doSomething())
    }
```

**Comment by wfeng-fsde** [comment]
@oleksiyp do you have an update on this? Thanks.

**Comment by oleksiyp** [comment]
Sorry, there is no such thing as "change return type for dynamic call". There is "change return type for dynamic property access", but it is not helpful.

Anyway you can always write like that(I think it is shortest way and adding anything to API is not needed):
```
every { t["privateMethod"](allAny<String>()) as Unit } just Runs
```

**Comment by oleksiyp** [comment]
Initiial question was `why?`. Because dynamic calls are special and need `Any` type and better to keep `just Runs` applicable only to `Unit` types(for regular calls).

**Comment by wfeng-fsde** [comment]
Got it and thanks.
