### ISSUE TITLE
Cannot mockkstatic for Kotlin companion object static method

### ISSUE THREAD

**Issue by joetsaitw** [mockk/mockk#136]
### Expected Behavior
I try to mock static method using mockkStatic(). It seems that mockkStatic() only works with two cases.

**1. Pure Java Static Class**

``` java
public class UtilJava {

    static String ok() {
        return "UtilJava ok()";
    }
}

```

**2. Kotlin Object** 

``` Kotlin
object UtilKotlin {

    @JvmStatic
    fun ok(): String {
        return "UtilKotlin ok()"
    }

}
```

**Usage**
``` kotlin
class Util {
    fun ok() {
        UtilJava.ok()
        UtilKotlin.ok()
    }
}
```

**Test Code**
``` kotlin
class UtilTest {
    @Test
    fun ok() {
        // Given
        val util = Util()
        mockkStatic(UtilJava::class)
        mockkStatic(UtilKotlin::class)

        every { UtilJava.ok() } returns "Joe"
        every { UtilKotlin.ok() } returns "Tsai"

        // When
        util.ok()

        // Then
        verify { UtilJava.ok() }
        verify { UtilKotlin.ok() }

        assertEquals("Joe", UtilJava.ok())
        assertEquals("Tsai", UtilKotlin.ok())
    }
}
```

### Current Behavior

Above code works pretty good, but it doesn't work with **Kotlin companion object**.

``` kotlin
 class UtilKotlin {

    companion object {
        @JvmStatic
        fun ok(): String {
            return "UtilKotlin ok()"
        }
    }
}

```
Same test as above will throw this exception: 
`io.mockk.MockKException: Missing calls inside every { ... } block.` on this line `every { UtilKotlin.ok() } returns "Tsai"`

Is there any way to mock companion object? Thanks!

**Comment by oleksiyp** [comment]
Just a quick guess. Have you tried this:

```
  mockkStatic(UtilJava::class) 
  mockkStatic(UtilKotlin.Companion::class)
```

**Comment by joetsaitw** [comment]
@oleksiyp I tried it, but still getting same exception.

`io.mockk.MockKException: Missing calls inside every { ... } block.`

**Comment by Kerooker** [comment]
I believe that in this scenario, as the calls are delegated to the companion object, you should mock the object itself using `mockkObject`.

```
class UtilTest {
    @Test
    fun ok() {
        // Given
        val util = Util()
        mockkStatic(UtilJava::class)
        mockkObject(UtilKotlin)

        every { UtilJava.ok() } returns "Joe"
        every { UtilKotlin.ok() } returns "Tsai"

        // When
        util.ok()

        // Then
        verify { UtilJava.ok() }
        verify { UtilKotlin.ok() }

        assertEquals("Joe", UtilJava.ok())
        assertEquals("Tsai", UtilKotlin.ok())
    }
}
```

**Comment by joetsaitw** [comment]
@Kerooker Thanks man! Even though `mockkObject()` is not intuitive to mock static method, it works like a charm. Besides, `mockkObject(UtilKotlin.Companion)` also works. Delegating to the companion object makes everything clear. However, I just wonder which scenario I can use `mockkstatic()` except those two cases I mention above?

**Comment by oleksiyp** [comment]
`mockkStatic` can be used to mock extension methods

**Comment by joetsaitw** [comment]
@oleksiyp @Kerooker 
Thanks a lot. It's clear to me now!

**Comment by bnacey** [comment]
Please consider adding this example of mocking a companion object to the documentation.

**Comment by svkaka** [comment]
**For people like me**. 
Be sure you `mock` your object before calling a method that works with this object. 
That was my problem.

**Comment by mmorenoxumak** [comment]
> **For people like me**. Be sure you `mock` your object before calling a method that works with this object. That was my problem.

It helped me, thank you.

**Comment by waylife** [comment]
> I am writing unit test case for following class in Kotlin object class.
> 
> ```
> object DeviceUtils {
> 
>     fun getManufacture() = Build.MANUFACTURER.toLowerCase()
> }
> ```
> 
> Test case:
> 
> ```
> @Before
>     fun setUp() {
>         MockitoAnnotations.initMocks(this)
>         PowerMockito.mockStatic(DeviceUtils::class.java)
>         subject = PowerMockito.spy(DeviceUtils)
> 
>         PowerMockito.`when`(subject.getManufacture()).then { "samsung" }
>     }
> ```
> 
> I've tried with different solutions but no luck.
> 
> Can you guys please help me on same.

if you use mockk, try this
1.  add   @JvmStatic to getManufacture method
2.    mockkStatic.mockStatic(DeviceUtils::class)
        every {DeviceUtils.getManufacture() } returns "samsung"
