### ISSUE TITLE
Feature Request: @MockkBean for Spring Boot

### ISSUE THREAD

**Issue by Kerooker** [mockk/mockk#140]
Spring boot has a [specific artifact for testing](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing), and Spring Boot Starter Test contains a lot of libraries. One of which is Mockito.

In this artifact, there's a specific package for Mockito: `org.springframework.boot.test.mock.mockito`, and this package contains some very useful annotations: [`MockBean`](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/mock/mockito/MockBean.html) and [`SpyBean`](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/mock/mockito/SpyBean.html) among some others.

These annotations allow the developer to create mocked instances of beans without much trouble, and this is very useful for integration testing when a bean, for example, calls an external dependency.

Given that [Spring is one of the most used Java frameworks](https://javapipe.com/hosting/blog/best-java-web-frameworks/), I believe that Mockk should have a `@MockkBean` annotation that mimics what Mockito does.

----

Current workaround:
--

Mocking the bean by hand:

```
@Bean fun foo(): FooBean = mockk()
```

This had a question in [StackOverflow](https://stackoverflow.com/questions/52132203/how-to-achive-capturing-like-behavior-in-mockk) and some discussion in Mockk's Gitter.

----

Possibilities to handle this issue:
--

- Create a Pull Request for the Spring Framework to include a `org.springframework.boot.test.mock.mockk` package with the given annotations
- Implement this as a different artifact in mockk (shouldn't be included in the main lib, IMO)
- Implement this as part of the mockk library, considering Spring usage (might inflate the lib a few classes)

**Comment by oleksiyp** [comment]
It is possible Spring wont accept our PR, so we have to do it in a function that can be performed manually.

Currently I think there is no reason to create more user-facing artifacts. It can be just one more internal + compile time dependencies

**Comment by Kerooker** [comment]
Should we try to go for the PR or do it internally straight?

**Comment by oleksiyp** [comment]
First is implementation itself, then attempt to do a PR

**Comment by travikk** [comment]
@oleksiyp is there any plan to implement this soon?

**Comment by jnizet** [comment]
I have started (and in fact almost finished) writing such an implementation: see https://github.com/Ninja-Squad/springmockk.

I have started contacted a member of the Spring team that I know (who is in charge of Kotlin support in the Spring team) to know if that could be integrated in Spring-Boot.

**Comment by oleksiyp** [comment]
Very nice. Fill free to ask any stuff you need or have questions regarding it

**Comment by jnizet** [comment]
I have filed an issue on the Spring Boot project to support MockK. See https://github.com/spring-projects/spring-boot/issues/15749

**Comment by jnizet** [comment]
The Spring Boot team [declined my feature request](https://github.com/spring-projects/spring-boot/issues/15749#issuecomment-456869715), so I released SpringMockK. See https://github.com/Ninja-Squad/springmockk for usage notes.

**Comment by oleksiyp** [comment]
May you'd like to incorporate it into MockK? It can be compileOnly dependency on spring for example

**Comment by jnizet** [comment]
Thanks for the offer. Since it only has a dependency on the public API of MockK, and might have a release cycle that is different, I guess it can stay there, at least for now. I still hope it (or something like it) will eventually be part of Spring Boot itself.

**Comment by oleksiyp** [comment]
That's fine. Just in case you get bored to promote it yourself (and this is quite challenging, but fun :smile: ) let me know, will join our efforts. As for now when you are ready I can place a link at the top of the main MockK page to your project

**Comment by jnizet** [comment]
Thanks a lot @oleksiyp! 

I will tweet about it tomorrow, and Sébastien (member of the Spring team, responsible for Kotlin support) should mention it in the official documentation. Hopefully that will bring more developers to SpringMockK, and more importantly, to MockK, which I haven't used a lot yet, but which I find brilliant and a pleasure to use.

You can link to SpringMockK as soon as you want to.

**Comment by oleksiyp** [comment]
Close this one as it is now separate project https://github.com/Ninja-Squad/springmockk
