### ISSUE TITLE
Feature: auto-clear Mockks after tests execution(integration with JUnit)

### ISSUE THREAD

**Issue by LeoColman** [mockk/mockk#142]
Sometimes, when mockking in static way (for instance, mocking constructors, mocking static and mocking objects), one may forget to execute a `clearMock` or `unmockkAll` method, and the mocked object context may be leaked to other test cases.

Right now, the current workaround is to unmockk manually

```
@After
fun after() {
    unmockkAll()
}
```

However, having to add this to every `@After` is pretty cumbersome, and when one forgets, the error might be pretty sneaky.

----
Solution for this issue
--

Add an integration to Mockk that executes `unmockkAll` automatically after a test class.

Possibilities:

- Execute it automatically after every test (`@After`) with a hook into JUnit

**Comment by milgner** [comment]
This sounds like a very good idea! I recently ran into some issues because I assumed that the `MockkExtension` already did this.
Would a PR with a corresponding enhancement be considered for integration?

**Comment by Raibaz** [comment]
Yep I think adding this feature to the `MockkExtension` is the right way to do this.

**Comment by milgner** [comment]
I added a basic implementation for this in https://github.com/milgner/mockk/commit/548ce6b568f5d0201c4bab91f814d75f61037135

However when running tests it seems to me like the tests in `MockKExtensionTest` aren't being run. To test this out I added some code to [intentionally break the test](https://github.com/milgner/mockk/commit/6600bcf332f3d044fbb786d7a4d7040dab5241c9)  and the test in question doesn't show up in the test output of failed tests.

**Comment by Raibaz** [comment]
You're right, the MockKExtension-related tests were not being executed.

I fixed it, so if you rebase your branch on master you should be able to get them to run.

**Comment by gmazzo** [comment]
Performing `unmockkAll` on `afterEach` is not always the correct behavior and we should support a way to configure that. Recenly, we introduced `–Djunit.extensions.autodetection.enabled=true` and this change has broken all our `@TestInstance(PER_CLASS)` tests, because it's cleaning mocks after the first execution and not at the end of the class
