### ISSUE TITLE
InliningClassTransformer - Failed to transform class with a java.lang.ArrayIndexOutOfBoundsException, followed by NPE

### ISSUE THREAD

**Issue by wfeng-fsde** [mockk/mockk#143]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

I am testing one class that receives multiple constructor injected guice dependencies, most of them have their own constructor injected dependencies. In my test @Before function, I define the mock behavior by using things like `every { dependency.method(any(),...) } returns true`. For example, one of the dependency is a guice singleton with a constructor injected dependency:

    @Singleton
    class ProcessTracker @Inject constructor(private val anotherController: AnotherController) {
        fun startJob(msg: SomeMessage) : Boolean {
            val fetchedJobStatus = anotherController.fetchJob(msg.id, msg.name)
            ...
        }
    }
In my test:
    
    class MyTest {
        @MockK private lateinit var otherDependency1: OtherDependency1
        @MockK private lateinit var otherDependency2: OtherDependency2
        @MockK private lateinit var processTracker: ProcessTracker

        @MockK private lateinit var classUnderTest: ClassUnderTest
        
        ...
        @Before
        fun setUp() {
            MockKAnnotations.init(this, relaxUnitFun = true)

            every { otherDependency1.someMethod1(any(), any()) } just Runs
            every { otherDependency1.someMethod2(any(), any(), any()) } returns 3
            every { processTracker.startJob(any()) } returns true
            ...
            
            classUnderTest = spyk(ClassUnderTest(otherDependency1, otherDependency2, processTracker, ...), recordPrivateCalls=true)
        }

        @After
        fun tearDown() {
            unmockkAll()
        }

        @Test
        fun myFirstTest() {
            val msg = buildMessage()
            classUnderTest.methodToTest(msg)
            verify {...}
            verify {...}
        }
    }
I expect the mocked behavior of `ProcessTracker.startJob` be mocked and just return true in the tests.

### Current Behavior

I'm getting the following errors:

```
io.mockk.proxy.jvm.transformation.InliningClassTransformer - Failed to transform class com/mycompany/myproject/ClassUnderTest

java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default$TranslationMode$1.copy(Advice.java:1301)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1192)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1141)
...
```

followed by another error:

```
[main] WARN io.mockk.proxy.jvm.transformation.InliningClassTransformer - Failed to transform class com/mycompany/myproject/.../ProcessTracker

java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default$TranslationMode$1.copy(Advice.java:1301)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1192)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1141)
	at net.bytebuddy.asm.Advice$AdviceVisitor.visitFrame(Advice.java:6590)
...
```
and finally:

```
java.lang.NullPointerException
at com.mycompany.<>.<>.ProcessTracker.startJob(ProcessTracker.kt: 23)
...
```

Also I should note that sometimes I make some small changes that I don't think is substantial, and then the test would pass. Then I `git commit` that, close the project, open it again and run the test, it would fail with the same exceptions again.

One thing to note is that `ProcessTracker` is not the only guice injected singleton with a constructor injected dependency. Some of the other dependencies are also the same way. However, I'm getting the exceptions at this class only.

### Failure Information (for bugs)

Please see above description.

#### Steps to Reproduce

I've included detailed description of the issue above. Not sure I can reproduce it here without sharing my work code.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8.6
* OS: macOS High Sierra version 10.13.6
* Kotlin version: 1.2.60
* JDK version: 1.8
* JUnit version: 4
* Type of test: unit test

#### Failure Logs

see above description.

#### Stack trace

also see above description
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

see above
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by Kerooker** [comment]
> Also I should note that sometimes I make some small changes that I don't think is substantial, and then the test would pass. Then I git commit that, close the project, open it again and run the test, it would fail with the same exceptions again.

This part is especially interesting

**Comment by Kerooker** [comment]
Could you try to create a small sample project that reproduces this issue? It's pretty hard for us to understand what's going on if we can't reproduce it :/

**Comment by Kerooker** [comment]
What are the libs that you're using?

**Comment by oleksiyp** [comment]
Looks alike ByteBuddy issue, would be nice to report it there

**Comment by wfeng-fsde** [comment]
So one thing I am curious about is why would it try to call the real `ProcessTracker.startJob` function in the test since I've mocked it with `every { processTracker.startJob(any()) } returns true`. I thought  it would just use the mock and be done with it. Instead it's throwing exceptions at the first line in that function.

**Comment by oleksiyp** [comment]
It was not able to inatrument mocked class, so calling original

**Comment by wfeng-fsde** [comment]
Also that class `ProcessTracker` looks just like any other dependencies I have. However, the other dependency mocks are not complaining.

**Comment by oleksiyp** [comment]
How big methods are? Seems it is related to some classfile structure

**Comment by wfeng-fsde** [comment]
The methods are not that big. Like one method is exactly the following:

    fun startJob(message: SomeMessage): Boolean {
        val fetchedJob = anotherController.fetchJob(message.id, message.name)
        if (fetchedJob.isPresent) {
            val originStatus = JobStatus.valueOf(fetchedJob.get().getStatus())
            if (originStatus == JobStatus.DONE) {
                log.info("Skipping startJob since the job is already DONE. message: $message")
                return true
            }
        }
        return anotherController.startJob(message.id, message.name)
    }

**Comment by raphw** [comment]
Could you attach a class file of a class that is failing to transform? It looks like an issue with Kotlin stack map frames and in this context, I am sure exact versions matter so attaching the original class file would make it the easiest to investigate.

**Comment by raphw** [comment]
Could you also try to use Byte Buddy 1.8.22 and see if the issue still occurs?

**Comment by wfeng-fsde** [comment]
Thanks @raphw. I found that one of my dependency was using `mockito` and that was using `byte-budy` 1.6.11`. I excluded that and explicitly added `1.8.22` and now the problem has gone.

**Comment by meridsa** [comment]
I have no conflicts in terms of `byte-buddy`. However upgrading a library X from kotlin 1.4.32 to 1.5.0 causes me to face the exact same errors in the tests mocking classes in library X due to a common dependency in a class A of another common library.
