### ISSUE TITLE
Having `relax = true` in  Annontation

### ISSUE THREAD

**Issue by xizz** [mockk/mockk#144]
### Expected Behavior

Be able to do:
@MockK(relax = true)

### Current Behavior

Only have:
@MockK(relaxUnitFun = true)

**Comment by pusolito** [comment]
I’d like to see a way of defaulting to relaxed mockks.  All of my test code uses them and it’s annoying to have to be explicit.  I see the value in defaulting to strict, but it’s too painful to go the other way.

**Comment by oleksiyp** [comment]
I see. Valid point. 

What would you choose:
 * `MockKAnnotations.init(relaxed = true)` in every Test class in `@Before`
 * `-Dio.mockk.relaxed = true` via command line
 * creating file `io/mockk/settings/relaxed` in resources with content `true`

I think 3-rd option is most sustainable and simple as you have it global and don't need to specify at every Java configuration.

**Comment by pusolito** [comment]
Option 3 sounds great.

**Comment by xizz** [comment]
@oleksiyp Thanks. I think `@RelaxedMockk` would serve my need for now. It is just kind inconsistent for `relaxUnitFun` and `relaxed` to be handled differently.

**Comment by oleksiyp** [comment]
Added both resources settings file and annotation `@MockK(relaxed = true)` parameter in an annotation. Didn't test it well because needed to release Java 11 support faster. No docs so far as well.

How to use: 
 1. create `io/mockk/settings.properties` file in resources.
 2. Put one of following options:
```
relaxed=true|false
relaxUnitFun=true|false
recordPrivateCalls=true|false
```

**Comment by oleksiyp** [comment]
Please check it and let me know if it is working. Available in MockK 1.8.8

**Comment by xizz** [comment]
@oleksiyp I verify that both `@MockK(relaxed = true)` and `MockKAnnotations.init(this, relaxed = true)` are working as expected in 1.8.8. Thanks!

**Comment by oleksiyp** [comment]
Welcome
