### ISSUE TITLE
Feature: @StubBeans

### ISSUE THREAD

**Issue by oleksiyp** [mockk/mockk#145]
Simplify integration testing of legacy application with Spock 1.2 https://solidsoft.wordpress.com/2018/09/14/simplify-integration-testing-of-legacy-application-with-spock-1-2/amp/

**Comment by Kerooker** [comment]
Is this somewhat duplicate of
https://github.com/mockk/mockk/issues/140 ?

**Comment by oleksiyp** [comment]
#140 + `@StubBeans`, but in general yes. Just wanted to add this link on mobile

**Comment by oleksiyp** [comment]
moved https://github.com/Ninja-Squad/springmockk/issues/11
