### ISSUE TITLE
Missing feature: extra wrapper to "every { ... } returns ..."

### ISSUE THREAD

**Issue by KonradAdamek** [mockk/mockk#154]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
```
import io.mockk.MockKMatcherScope
import io.mockk.every
import io.mockk.mockk
import org.testng.annotations.Test

data class Point(val x: Int,
                 val y: Int,
                 val z: Int,
                 val foo: Foo,
                 val bar: Bar)

data class Foo(val v: Int)
data class Bar(val v: Int)

class MyTest {
    @Test fun test() {
        val foo4 = Foo(v = 4)
        val bar5 = Bar(v = 5)
        val point: Point = mockk(relaxed = true) {
            1 on { x }
            2 on { y }
            3 on { z }
            foo4 on { foo }
            bar5 on { bar }
        }
        with(point) { println("x=$x, y=$y, z=$z, foo=$bar5, bar=$foo4") }
    }
}

infix fun <T : Any> T.on(stubBlock: MockKMatcherScope.() -> T) = every(stubBlock) returns this
```

### Current Behavior
```
import io.mockk.MockKMatcherScope
import io.mockk.every
import io.mockk.mockk
import org.testng.annotations.Test

data class Point(val x: Int,
                 val y: Int,
                 val z: Int,
                 val foo: Foo,
                 val bar: Bar)

data class Foo(val v: Int)
data class Bar(val v: Int)

class MyTest {
    @Test fun test() {
        val foo4 = Foo(v = 4)
        val bar5 = Bar(v = 5)
        val point: Point = mockk(relaxed = true) {
            every { x } returns 1
            every { y } returns 2
            every { z } returns 3
            every { foo } returns foo4
            every { bar } returns bar5
        }
        with(point) { println("x=$x, y=$y, z=$z, foo=$bar5, bar=$foo4") }
    }
}
```

#### Steps to Reproduce
1. Run code from Expected and Behavior section
2. See that added extra infix function works as standard call and add it to library

#### Context
* MockK version: 1.8.9
* Kotlin version: 1.2.71
* JDK version: 9 (1.8 in target)

**Comment by oleksiyp** [comment]
It can be great holywar, because there is no objective measure, but `every {...}` is more readable and eye catching. I am not covinced to change it. Please give some reasoning or close the ticket. @Keeroker what do you think?

**Comment by KonradAdamek** [comment]
I see no side effects here. It can be available as optional feature, not as strongly recommended way to write those expressions but just alternative. Just to give possibility to shorten and simplify code based on actual team preferences. Just simple one line:
```
infix fun <T : Any> T.on(stubBlock: MockKMatcherScope.() -> T) = every(stubBlock) returns this
```
Now I have it in my project and it works fine, so it would be nice to see and use it from library.

**Comment by oleksiyp** [comment]
@pusolito I believe it is like that now:
```
   every {  foo.bar  } returns "hi" andThen "hi" andThen "there"
```
or 
```
   every {  foo.bar  } returnsMany listOf("hi", "hi", "there")
```
Isn't it enough for your usecases?

**Comment by oleksiyp** [comment]
@KonradAdamek every team can define own set of simplifications, but I would like most people to use full form and aware of what the standard is.

**Comment by pusolito** [comment]
Ahh, I missed this capability.  This is sufficient.  Thanks.

**Comment by oleksiyp** [comment]
Finally decided not to go with it
