### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Xavbm** [mockk/mockk#155]
Typo in JvmMockKGateway.kt file 

Andorid in text.

> Android instrumented test is running, " +
                    "include 'io.mockk:mockk-**andorid**' dependency " +
                    "instead 'io.mockk:mockk'"
        )
    else
        InternalPlatform.loadPlugin(
            "io.mockk.proxy.jvm.JvmMockKAgentFactory",
            "Check if you included 'io.mockk:mockk-**andorid**' dependency " +
                    "instead of 'io.mockk:mockk'"

**Comment by oleksiyp** [comment]
Thanks for  reporting it

**Comment by Xavbm** [comment]
you are welcome, keep up the good work !

**Comment by oleksiyp** [comment]
PR merged
