### ISSUE TITLE
Is there a way to make String property in mocked object to return "" instead of null?

### ISSUE THREAD

**Issue by KazafChen** [mockk/mockk#160]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Given I have the following class:
```kotlin
class Person(val name: String)
```
And I run the following test:
```kotlin
@Test
fun test() {
    val person = mockk<Person>()
    assertThat(person.name, `is`(""))
}
```
This test will definitely failed. Property `name` of the mocked object `Person` will return `null` by default.
I'm wondering if there is a way to make a String property of an object to `""` instead of `null`?

**Comment by Kerooker** [comment]
Yes, you can. But it actually doesn't return null by default, it will throw an exception, AFAIK.

```
@Test
fun test() {
val person = mockk<Person>()
every { person.name } returns ""
assertThat(person.name, `is`(""))
}

```

or

```
@Test
fun test() {
    val person = mockk<Person> {
        every { name } returns ""
    }
    assertThat(person.name, `is`(""))
}
```

**Comment by KazafChen** [comment]
I see. Thank you for your reply :)
