### ISSUE TITLE
Documentation enhancement

### ISSUE THREAD

**Issue by lfmunoz** [mockk/mockk#172]
I am using 
"io.mockk:mockk:1.7.17"
because I can't upgrade to Kotlin 1.3 yet. 

The following does not work(timeout parameter doesn't exist), but according to the documentation it should work:
verify(timeout = 3000) { socket.writeTextMessage(pktObj.toJson().encode()) }

Perhaps this was added in a newer version of mockk, who knows. To figure this out is a lot of effort. Please link to the source code in the documentation, or/add comments about what version a feature was added in.

**Comment by oleksiyp** [comment]
Hm, documentation reflects the latest state of things.

Just do not understand why there is a problem to use current version.
There is two versions `1.8.12.kotlin13` for Kotlin 1.3 and `1.8.12` for Kotlin 1.2.x (where x is >= some more or less recent version I think)

**Comment by lfmunoz** [comment]
@oleksiyp thank you. I moved to 1.8.12 I didn't realize there are two versions. I suppose if we always stick to the latest version then there isn't a problem with the documentation.

**Comment by oleksiyp** [comment]
Yes, it shouldn't be a problem. Only in rare cases, when I am in a process of release and updating README.md.
