### ISSUE TITLE
Mocking Suspend Coroutine Extension Functions in Multi-Module Project

### ISSUE THREAD

**Issue by BracketCove** [mockk/mockk#173]
*Note: A similar issue has been filed #56, but my use case is a bit more complex, and it doesn't use the deprecated staticMockk() function. 

I've put together a small example of what I'm trying to do, which has the same set up and requirements as I'm aiming for in my production code. The primary goal is to adequately test the "Logic" class, while being able to Mock the extension functions which it uses to request data from the "domain" module. 

https://github.com/BracketCove/ExtensionFunctionInteractorTest

### Expected Behaviour:
I would like to be able to Mock module-wide extension functions, which exist in a separate module than the class I'd like to test. Theses extensions are also suspending functions.

For anyone curious, the reason why it's important that I don't actually use the implementation of my extension functions, is that I don't actually want to test them in this case; just respond with appropriate values based on the test case.

### Current Behaviour:
Based on results of executing the test, it appears that the Extension Function I'm trying to Mock, is not being mocked (instead the actual implementation is used). I assert this based on the fact that locator.getSource() is being called during the test execution (which leads to a no answer exception), which tells me that the extension function which calls that method on the locator is not mocked; but rather the actual implementation is used. I doubled checked this with the debugger and it does appear to be the case.

### Failure Information:

Here is the result of the test. If I'm not mistaken, getSource() should not be called if the extension function was mocked properly.
This
`Exception in thread "DefaultDispatcher-worker-2 @coroutine#3" io.mockk.MockKException: no answer found for: ServiceLocator(#1).getSource()
	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:94)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:46)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:15)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:48)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:223)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:23)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at com.wiseassblog.domain.ServiceLocator.getSource(ServiceLocator.kt:3)
	at com.wiseassblog.domain.InteractorExtKt$getStringData$2.invokeSuspend(InteractorExt.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:221)
	at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:67)
	at kotlinx.coroutines.scheduling.Task.run(Tasks.kt:94)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:732)

java.lang.AssertionError: Verification failed: call 1 of 1: IView(#2).updateUI(eq(Oy Blin))) was not called
//I've omitted the assertion error details as I don't believe they are relevant to the issue.
	`
#### Steps to Reproduce

Clone the repository and execute the test in Android Studio (presumably Intellij might also work). I'm using AS 3.2.1, with JRE 1.8.0, and JUnit 5.2.0, Kotlin version 1.3.0.

- Logic.kt is the class I'm testing
- LogicTest.kt (in test dir) holds the test in question
- InteractorExtension.kt from the domain module holds the Extension Function I wish to mock
- versions and dependencies for various libraries is located in the root directory, in deps.gradle 

I hope it's acceptable to just supply the repo, but if I can provide any other info, or you'd like to see some more info in this issue, let me know and I'll happily oblige.

Thank you kindly.

**Comment by oleksiyp** [comment]
The problem I found is that `CoroutineScope` is an implicit first parameter(receiver).

When mocking happens it is capturing `runBlocking` scope `this` and when it is used from `launch` new scope is used which is not matching.

As under the hood, the receiver is the same kind of parameter as any other you can apply matchers in such case:
```
        runBlocking {
            mockkStatic("com.wiseassblog.domain.InteractorExtKt")

            coEvery {
                any<CoroutineScope>().getStringData("hey")
            } returns "ho"

            launch {
                println(getStringData("hey"))
            }
        }
```

Besides that, I can admit that everything you run via `launch` should be either `joined` or awaited in `verify` with `timout`:
```
        verify(timeout = 500) { view.updateUI(testData) }
```

**Comment by BracketCove** [comment]
Thanks for the info, I'll play around and see what I can do. 

The good news is that this problem is easily fixable by just using a class instead of the Extension Functions, but I was attempting to replicate something similar to what Roman Elizarov was advocating in this talk (implementing a domain-like API using extensions on CoroutineScope, and using them in a class which implements CoroutineScope):
https://www.youtube.com/watch?v=a3agLJQ6vt8&t=2103s

**Comment by erikhuizinga** [comment]
@oleksiyp I don't fully understand the solution you propose.

I have a bit of a different situation, but similar enough to this issue to post it here.

The difference is that I don't use `runBlocking` so my test method has no `CoroutineScope` in sight. However, one static function being mocked by `mockkStatic` calls a `CoroutineScope` extension function in the same file, which uses `launch` (implicitly on `this`, the `CoroutineScope`). In the `launch` block I call some functions that I mock.

That coroutine scope extension function is somehow called without the mocked stuff being in place, so I get an `io.mockk.MockKException: no answer found for: X.y()` exception. I've used `coEvery { any<X>().y() } returns whatever`, but those mock aren't applied there. Those `X.y()` functions are extensions too and that class is statically mocked too.

Any ideas/suggestions/solutions?

**Comment by erikhuizinga** [comment]
I'm trying to come up with a reproducible MWE, but it seems I simply can't reproduce my own code in a generic way that generates the same exception. ☹️

**Comment by erikhuizinga** [comment]
Nevermind my other comments (deleted). Some unmocked call was made in a coroutine, but the stack trace showed up in a **different** test method. I guess because the coroutine threw an exception while the next test method was already running?

Lesson learned: name you mocks so you can easily identify which one's throwing.
