### ISSUE TITLE
Verification faile. Method was not called

### ISSUE THREAD

**Issue by LipatovNikita** [mockk/mockk#177]
I have a simple Spring MVC app with three layers - dao, service and controller. 
For example, I have `ObjectService`
```
public interface ObjectService {
    Object getById(Object object);
}
```
and its implementation
```
@Service
public class ObjectServiceImpl implements ObjectService {
   private final ObjectDao objectDao;
   
   @Autowired
   public ObjectServiceImpl(ObjectDao objectDao) {
      this.objectDao = objectDao;
   }

   @Override
   @Transactional(readOnly = true)
   public Object getById(Object object) {
      return objectDao.getById(object.getId());
   }
}
```
I decided to add unit testing using Kotlin and found MockK. But using this library I get exceptions(
Here is an example of my test class:
```
@ContextConfiguration(locations = ["classpath:spring/app-context-test.xml"])
class ObjectServiceTests : StringSpec() {
   private val objectDao = mockk<ObjectDao>()
   private lateinit var objectServiceImpl: ObjectServiceImpl
   
   override fun beforeTest(description: Description) {
       super.beforeTest(description)
       objectServiceImpl = ObjectServiceImpl(objectDao)
   }

   init {
        "simpleTest" {
            every { objectDao.getById(any()) } returns null
            objectServiceImpl.getById(object())
            verify { objectDao.getById(any()) }
        }
    }
}
```
And execption... `java.lang.AssertionError: Verification failed: call 1 of 1: ObjectDao(#1).getById(any())) was not called`

Help to understand, please

#### Context

* MockK version: 1.8.13.kotlin13
* Kotlin version: 1.3.0
* JDK version: 1.8
* JUnit version: kotlintest-runner-junit5 (3.1.8)

**Comment by oleksiyp** [comment]
Thank you for the report. It might be a problem with bytebuddy. Check http://mockk.io "Known issues"

**Comment by LipatovNikita** [comment]
That is, it will be enough to add a bytebuddy dependency?

**Comment by oleksiyp** [comment]
Yes, it might help, might not.

**Comment by LipatovNikita** [comment]
Unfortunately, adding dependencies didn't help(

**Comment by oleksiyp** [comment]
Hey, can I ask what was the problem?
