### ISSUE TITLE
Feature: construct to emulate `returns Nothing`

### ISSUE THREAD

**Issue by abelsromero** [mockk/mockk#187]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Found the related the similar issue https://github.com/mockk/mockk/issues/56, but it's not the same.

### Expected Behavior

I'd like to spy on a void method like this:

```kotlin
fun quit(status: Int): Nothing {
    exitProcess(status)
}
```

Basically, if I don't mock this method, any test that runs this, ends the execution of the tests by ending the java process.

### Current Behavior

What is the current behavior?

Haven't been able to mock because it expects for me to add a `return` statement.

Tried this

```kotlin
mockkStatic("kscript.app.AppHelpersKt")
every {
    quit(1)
} returns Nothing
```

In theory I should add `returns Nothing` but, the Nothing cannot be instantiated.
And skipping the `return` causes this error during execution 
```
io.mockk.MockKException: Bad recording sequence. Please finalize every { ... } block with returns/answers/just Runs
```

#### Context

* MockK version: 1.8.13
* OS: Windows 10
* Kotlin version: 1.3.10
* JDK version: 1.8.0_191
* JUnit version: 4.12
* Type of test: unit test

**Comment by oleksiyp** [comment]
You can try the following code:
```
every {
    quit(1)
} answers { throw IllegalArgumentException("this is a test") }
```

Looked up in #158

**Comment by abelsromero** [comment]
Thanks for the quick answer! And apologies for not finding the related issue.
The solution is not perfect, but it will suffice.

Do you think it would be worth mentioning at the end of `Extension functions` in README?

**Comment by oleksiyp** [comment]
Yes, I think it may be useful note

**Comment by oleksiyp** [comment]
Please do not close this ticket. I'll try to figure out what can be done about it in code. It can hang for some time, but after some time I'll get back to it.

**Comment by oleksiyp** [comment]
After all following construct is simple and concise. I didn't find anything better.

```
every { quit(1) } throws Exception("this is a test")
```
