### ISSUE TITLE
Feature: add coVerifySequence

### ISSUE THREAD

**Issue by PaulWoitaschek** [mockk/mockk#189]
I need the equivalent of `verifySequence` with a coroutine scope.

**Comment by oleksiyp** [comment]
To be precise:
```
        coVerify(ordering = Ordering.SEQUENCE) {
            ...
        }
```
Please keep this ticket. I will add shortcuts alike `coVerifySequence` later

**Comment by oleksiyp** [comment]
Versions 1.9 & 1.9.kotlin12 were released with this change included. Please check it and close the ticket if everything is OK.
