### ISSUE TITLE
Bug[Hard]: Constructor mocking for StringBuilder does not work

### ISSUE THREAD

**Issue by MarcinMoskala** [mockk/mockk#192]
The following constructor mocking:

```mockkConstructor(StringBuilder::class)```

Does stop test and displays:

```
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "main"

Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "Thread-0"
```

Minimal code to reproduce this error:

```
class TreeToStringTest {
    @Test
    fun `Uses StringBuilder to construct String`() {
        mockkConstructor(StringBuilder::class)
    }
}
```

**Comment by oleksiyp** [comment]
Hi, thanks for the report. :smile: many stuff like that is not available if it is used internally in mockk

**Comment by MarcinMoskala** [comment]
Ow, ok. Any other idea how can I check if `StringBuilder` is used in `toString` method? I don't want them to just replace it with normal String :P

**Comment by oleksiyp** [comment]
Nothing comes to my mind.
