### ISSUE TITLE
Feature: switch mainline version to use Kotlin 1.3

### ISSUE THREAD

**Issue by PaulWoitaschek** [mockk/mockk#193]
Could you use standard semver versioning?

I use the [Gradle Versions Plugin](https://github.com/ben-manes/gradle-versions-plugin) and it thinks that .kotlin13 is an outdated version.

I think more consistent would be to release a different artifact so it would be
`io.mockk:mockk-kotlin13:1.8.13` instead of `io.mockk:mockk:1.8.13.kotlin13`

**Comment by oleksiyp** [comment]
Hi, releasing other artifact is not feasable. Due to few reasons. Propose something other and will see :smiley:

**Comment by PaulWoitaschek** [comment]
Remove the kotlin13 suffix and prefix the version with the outdated kotlin version as preKotlin13?

When setting up mockk initially I got confused anyways because I thought the default artifact wouldn't have an outdated kotlin version.

**Comment by oleksiyp** [comment]
You are right it's time to switch kotlin13. So that old one is `1.8.14.kotlin12` and new one `1.8.14` that's not so bad idea I think. Any disadvanteges of that except again some confusion(which Ill try to mitigate by adding a note to the main page at the top)

**Comment by PaulWoitaschek** [comment]
I don't think there are other disadvantages. I assume mockk users are progressive devs anyways and keep their kotlin version up to date anyways.

**Comment by oleksiyp** [comment]
Version 1.9 is released. It is a version using new Kotlin and coroutines. Version 1.9.kotlin12 is kept for compatibility
