### ISSUE TITLE
How to move testing class to some state before tests or how to drop mock counters?

### ISSUE THREAD

**Issue by SCpRoION** [mockk/mockk#200]
I need to test a class (f.e. presenter) which has some states. I'm moving presenter to that state using it's public methods, imitating the way it goes in a real execution. Then I want to test presenter at this state, but mock methods call counters are already nonzero, cause some calls were done, when I was moving presenter to necessary state.

So my question is:
is there any way to drop method call counters before test actually begins? Or how else can I test some class from any state?

Using JUnit 5.1.0, mockk 1.8.9. 

Below I gonna describe my question on example:
```
class TestingClass(val dependency: SomeDependency) {
    fun start() {
        dependency.doSmth()
        dependency.doSmthElse()
    }

    fun continue() {
        dependency.doSmth()
    }
}
```
Now I want to test `continue` method for the state, when `start` was already called. I write something like this:
```
class TestingClassTest {
    private lateinit var testingClass: TestingClass
    
    @RelaxedMockK
    lateinint var dependencyMock: SomeDependency

    @BeforeEach
    fun setUp {
        MockKAnnotations.init(this)
        testingClass = TestingClass(dependencyMock)
        testingClass.start()
    }

    @Test
    fun testContinue() {
        testingClass.continue()
        verify(exactly = 0) {
            dependencyMock.doSmthElse() // Fails, because it was called while `start` method
        }
        verify(exactly = 1) {
            dependencyMock.doSmth() // Fails, because it was called twice: once at `start` and once at `continue` methods.
        }
    }
}
```

**Comment by oleksiyp** [comment]
Maybe you are looking for:
```
            clearMocks(
                mock,
                answers = false,
                recordedCalls = true,
                childMocks = false
            )
```

**Comment by SCpRoION** [comment]
Exactly! Thanks a lot!
