### ISSUE TITLE
Mocking external library's top level function

### ISSUE THREAD

**Issue by CarloDePieri** [mockk/mockk#204]
### Prerequisites

- [x] I am running the latest version 
- [x] I checked the documentation and found no answer (some I found, more on this later)
- [x] I checked to make sure that this issue has not already been filed (I did check, and a similar issues is #56 , but the solution proposed there is not working)

### Expected Behavior

I'm trying to mock a top level function called **get** in the [khttp](https://github.com/jkcclemens/khttp) library. I want to replace it. I installed the library via gradle and jitpack. Its package name should be _khttp_ and the file name _KHttp_ ([the file](https://github.com/jkcclemens/khttp/blob/master/src/main/kotlin/khttp/KHttp.kt)); also, in the jar the class file is called _KHttp.class_. The library is functioning and I can call its functions both from tests and from the source code.

To my understanding I'm supposed to use something like this:
```kotlin
mockkStatic("khttp.KHttpKt")
every { get(any()) } answers { .. }
```

### Current Behavior
I cannot get mockkStatic to work (execution does not even get to the _every_). I tried many name combination but I always get:
```
java.lang.ClassNotFoundException: nameIUsed
```

I think mockkStatic is working per se, because if I try to mock a top level function in a package in my own module the error does not come out. Maybe the only thing wrong is the way I'm referring to the function...

**Comment by oleksiyp** [comment]
The key here is following line:

```
@file:JvmName("KHttp")
```

You should try: `mockkStatic("khttp.KHttp")` I think
