### ISSUE TITLE
Sharing mocks across multiple tests

### ISSUE THREAD

**Issue by neilcronin** [mockk/mockk#218]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I am porting some tests from mockito to mockk, and the lifecycle of the injected mocks in the class under test is not clear.  In the code below, the mockito tests pass successfully, but the mockk tests fail with `2 matching calls found, but needs at least 1 and at most 1 calls`.  

I have many tests written in mockito in a way that works as I expect, but I cannot find any docs on how to do the same thing in mockk.

How should I organize a class that contains multiple tests as well as verify() the interactions with the mocks?

```
package com.example

import io.mockk.MockKAnnotations
import io.mockk.impl.annotations.InjectMockKs
import io.mockk.impl.annotations.RelaxedMockK
import io.mockk.verify
import org.mockito.InjectMocks
import org.mockito.Mock
import org.mockito.Mockito.times
import org.mockito.MockitoAnnotations
import org.springframework.beans.factory.annotation.Autowired
import org.testng.annotations.BeforeMethod
import org.testng.annotations.Test

class Dependency {
    fun doSomething() {
        return
    }
}

class Service {
    @Autowired lateinit var dependency: Dependency
    fun doSomething() {
        return dependency.doSomething()
    }
}

@Test
class SomeTestMockk {

    @RelaxedMockK private lateinit var dependency: Dependency

    @InjectMockKs var service: Service = Service()

    @BeforeMethod
    fun setup() {
        MockKAnnotations.init(this)
    }

    @Test
    fun test1() {
        service.doSomething()
        verify(exactly = 1) { dependency.doSomething() }
    }

    @Test
    fun test2() {
        service.doSomething()
        verify(exactly = 1) { dependency.doSomething() }
    }
}


@Test
class SomeTestMockito {

    @Mock private lateinit var dependency: Dependency

    @InjectMocks var service: Service = Service()

    @BeforeMethod
    fun setup() {
        MockitoAnnotations.initMocks(this)
    }

    @Test
    fun test1() {
        service.doSomething()
        org.mockito.Mockito.verify(dependency, times(1)).doSomething()
    }

    @Test
    fun test2() {
        service.doSomething()
        org.mockito.Mockito.verify(dependency, times(1)).doSomething()
    }
}
```

**Comment by oleksiyp** [comment]
Just do `clearMocks(dependency)` in  `@AfterMethod`

**Comment by neilcronin** [comment]
Thank you!  

It might be worth explaining what "clear" means in the docs.  It's not a term I've seen in other mocking libraries, although it's perfectly obvious what it does once you pointed it out in this context.

**Comment by oleksiyp** [comment]
Welcome. Yes, docs are missing this point
