### ISSUE TITLE
Explain confirmVerified better

### ISSUE THREAD

**Issue by erikhuizinga** [mockk/mockk#220]
The new `confirmVerified` function seems to be used a lot (11 times!) in [the latest readme](https://github.com/mockk/mockk/blob/f2a4fba3cec128701ed5da1257a6127a8d938bea/README.md).
1. Should it always be used? If so, it would be helpful to know why.
2. In general, why do we need it and how do we use it correcly:
   - Are there examples where `verify`, `verifySequence`, `verifyOrder` and `verifyAll` fail or don't suffice?
   - Can you provide an example where `confirmVerified` throws an exception?

In the [Mockito documentation on `verifyNoMoreInteractions`](http://static.javadoc.io/org.mockito/mockito-core/2.23.4/org/mockito/Mockito.html#finding_redundant_invocations), they link to [this blog](https://web.archive.org/web/20160326032131/http://monkeyisland.pl/2008/07/12/should-i-worry-about-the-unexpected/) where it is discussed when you want or don't want to check no more calls were made to your mocks. It might be valuable to use these reasons when explaining when to use and when not to use `confirmVerified`.

**Comment by oleksiyp** [comment]
Good point, thanks, will check it later

**Comment by oleksiyp** [comment]
I added some additional information to the explanation about confirm verified: https://github.com/mockk/mockk/blob/master/README.md#verification-confirmation

Regarding whether to use or not there is anyway no definite answers. Hope after some time people will write some articles with their experience.
