### ISSUE TITLE
How to verify order and number of calls exactly?

### ISSUE THREAD

**Issue by erikhuizinga** [mockk/mockk#225]
With MockK we _can_ do

```kotlin
verifyOrder {
    mock.call1()
    mock.call2()
}
```

and

```kotlin
verify(exactly = 1) {
    mock.call1()
    mock.call2()
}
```

but we _cannot_ do

```kotlin
verifyOrder(exactly = 1) {
    mock.call1()
    mock.call2()
}
```

nor

```kotlin
verify(exactly = 1, ordering = Ordering.ORDERED) {
    mock.call1()
    mock.call2()
}
```

Why is this so? How can I verify order _and_ exact call count? Do I simply have to create two calls, i.e., `verify(exactly = 1)` and `verifyOrdered` with the same verify block? This makes the test code somewhat inefficient.

**Comment by oleksiyp** [comment]
Although any subsequence matching will pass in order, so it is not very good way to verify something

**Comment by erikhuizinga** [comment]
Ah, that makes sense. However, my interpretation was: the block should be called exactly `n` times, the block is in order. So:

```
1:
call1
call2

2:
call1
call2
```

but I understand the potential ambiguity. A solution would be to clearly specify the entire block is verified as one unit in the function documentation.

> Although any subsequence matching will pass in `verifyOrder`, so it is not very good way to verify something

I think it's fine any subsequence can be verified. This is useful to to verify just the important calls to mocks without having to verify all the things (like with `verifySequence` or `confirmVerified`).

**Comment by alexxRizz** [comment]
It might be useful for someone

```
fun verifyOnce(
  verifyBlock: MockKVerificationScope.() -> Unit
) =
  verify(exactly = 1, verifyBlock = verifyBlock)

fun verifyOnceWithOrder(
  verifyBlock: MockKVerificationScope.() -> Unit
) {
  verifyOnce(verifyBlock = verifyBlock)
  verifyOrder(verifyBlock = verifyBlock)
}
```
The same for coVerifyXxx
