### ISSUE TITLE
mockkClass() should have a relaxUnitFun argument

### ISSUE THREAD

**Issue by jnizet** [mockk/mockk#227]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I expect to be able to create a relaxUnitFun mock using mockkClass

### Current Behavior

It's not possible because there is no such argument, although the internal method it delegates to has one

* MockK version: 1.9
* OS: MacOS
* Kotlin version: 1.3.11
* JDK version: 8
* JUnit version: 5.3.2
* Type of test: unit test

**Comment by oleksiyp** [comment]
Thanks

**Comment by oleksiyp** [comment]
Fixed in master at b1809e

**Comment by oleksiyp** [comment]
Released [1.9.1](https://github.com/mockk/mockk/releases/tag/1.9.1). Please try it out and close the ticket if everything is fine

**Comment by jnizet** [comment]
Seems to be OK. Thanks a lot. I'll release a new version of SpringMockK with reaxUnitFun support ASAP.
