### ISSUE TITLE
Help: make it possible to test if an object is a mock

### ISSUE THREAD

**Issue by jnizet** [mockk/mockk#228]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I'm trying to implement MockkBean / SpyBean support for Spring using MockK (see https://github.com/Ninja-Squad/springmockk), and I need to check if an object is a mock. 

### Current Behavior

I manage to do it, but I feel I'm using an internal API, and wonder if it would be possible to add a method in the public DSL to do it:

```
import io.mockk.MockKGateway

val <T: Any> T.isMock: Boolean
    get() {
        return try {
            MockKGateway.implementation().mockFactory.isMock(this)
        } catch (e: UninitializedPropertyAccessException) {
            false
        }
    }
```

* MockK version: 1.9
* Kotlin version: 1.3.11
* JDK version: 8

**Comment by oleksiyp** [comment]
Thanks

**Comment by oleksiyp** [comment]
Sorry this tags is for issue 227, just've put it wrongly

**Comment by oleksiyp** [comment]
The way you're doing it is exactly the way it should be. This internal API is for extensions. And external API is for MockK users.

Please fill free to request things for this internal API

Just don't get why do you need this UninitializedPropertyAccessException?

**Comment by jnizet** [comment]
OK, glad to see that's the correct way.

I need that catch block because if I make that call before any mock was ever created using the MockK API (while initializing the spring context), then the lateinit var implementation has not been initialized yet, and it thus throws that exception. And I haven't figured out how to test if the lateinit var was initialized or not.

**Comment by oleksiyp** [comment]
There is a way to check `lateinit` var: https://stackoverflow.com/a/53705801/3742196
But another question is that probably you need to initialize MockK to interact with it. `MockK.useImpl { }` is suitable for this case.

**Comment by jnizet** [comment]
Thanks again @oleksiyp
