### ISSUE TITLE
Callback middleware mocking  (canot find a better title)

### ISSUE THREAD

**Issue by afaucogney** [mockk/mockk#230]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I need to mock a classundertest dependency to test the classundertest
How to do ?

### Current Behavior

I'm not able to mock the expected object. 

#### Context

Here is an example:

https://github.com/afaucogney/kotlin_mockk_callbacktest

Class under test MainClass at: https://github.com/afaucogney/kotlin_mockk_callbacktest/blob/master/app/src/main/java/fr/afaucogney/mobile/android/app/kotlintest/Test.kt

Unit test at MainClassTest: https://github.com/afaucogney/kotlin_mockk_callbacktest/blob/master/app/src/test/java/fr/afaucogney/mobile/android/app/kotlintest/MainClassTest.kt

I want to unit test the MainClass
MainClass has dependencies MainDependency, SecondDependency and 2 instances of MyCallBack interface to call each others recursively

The whole implementation, is like a middleware pattern, that enable usage of MySecondDependency:
I try to better explain : so there is a need to add behavior (MySecondDependency().doStuff()) in the MainClass().execute in case of onSuccess

This is real project case that I tried to simplify

Question is : how unit test MainClass by mocking/stubing all dependencies

**Comment by oleksiyp** [comment]
Quite extensive explanation. I still do not get it. Please ask small questions, that are clear.

I kind of fixed it(as the most common scenario):
```
package fr.afaucogney.mobile.android.app.kotlintest

import io.mockk.*
import org.junit.Test

class MainClassTest {

    @Test
    fun executeOnSuccess() {
        // Given
        val cb = spyk<MyCallBack>()
        mockkConstructor(MyDependency::class, MySecondDependency::class)
        every { anyConstructed<MyDependency>().send(any(), any()) } answers {
            arg<MyCallBack>(1).onSuccess(5)
        }

        //When
        MainClass().execute(cb)

        //Then
        verify {
            anyConstructed<MySecondDependency>().doStuff()
            cb.onSuccess(any())
        }

    }

    @Test
    fun executeOnFailure() {
        // Given
        val cb = spyk<MyCallBack>()
        mockkConstructor(MyDependency::class)
        every { anyConstructed<MyDependency>().send(any(), any()) } answers {
            arg<MyCallBack>(1).onError(5)
        }

        //When
        MainClass().execute(cb)

        //Then
        verifySequence {
            cb.onError(any())
        }

    }
}
```
