### ISSUE TITLE
Calling `verify { }` on realObject doesn't throw an Exception

### ISSUE THREAD

**Issue by JurajBegovac** [mockk/mockk#235]
### Expected Behavior

Calling `verify` on a real object should throw an exception (e.g. in mockito it throws `NotAMockException`). Because it's a real object and not a `spyk` (if it's a spyk then I would not expect an exception).

### Current Behavior

It seems that calling `verify { realObject.doSomething() }` on a real object verifies the real object.

#### Context

* MockK version: 1.9
* OS: macOS Mojave (10.14.2) - Android Studio 3.3 
* Kotlin version: 1.3.0
* JUnit version: 4.12
* Type of test: unit test
* Mockito version: 2.18.3

#### Minimal reproducible code

```kotlin

// open for mockito
open class A(private val b: B) {

    open fun doSomething1() = doSomething2()

    open fun doSomething2() = b.calculate()
}

// open for mockito
open class B {
    // just a dummy method
    open fun calculate() = 2 + 2
}

class TestMockk {

    @RelaxedMockK
    private lateinit var b: B

    private lateinit var a: A

    init {
        MockKAnnotations.init(this)
    }

    @Before
    fun setUp() {
        a = A(b)
    }

    @After
    fun tearDown() {
        unmockkAll()
    }

    @Test
    fun doSomething1() {
        a.doSomething1()

        // This one runs fine - I would expect to throw some exception because "a" is real object
        verify { a.doSomething2() }
    }
}

@RunWith(MockitoJUnitRunner::class)
class TestMockito {

    @Mock
    private lateinit var b: B

    private lateinit var a: A

    @Before
    fun setUp() {
        a = A(b)
    }

    @Test
    fun doSomething1() {
        a.doSomething1()

        Mockito.verify(a).doSomething2() // throws NotAMockException
    }

    @Test
    fun doSomething1WithSpy() {
        val a1 = Mockito.spy(a)

        a1.doSomething1()

        Mockito.verify(a1).doSomething2() // this is fine because it's a spy
    }
}
```

I'm not sure if this is a bug or a feature :)

If it's a feature I think it should be documented somewhere.

Thank you in advance.

**Comment by oleksiyp** [comment]
Thanks for the report

**Comment by oleksiyp** [comment]
After examining how this can be implemented I can tell that there is no solution to this problem. Mockito accepts it as a parameter, but MockK captures intercepted calls. In some cases, classes are instrumented and in some cases are not.

**Comment by JurajBegovac** [comment]
@oleksiyp Ok, thanks for taking a look
