### ISSUE TITLE
MockK and RxJava2

### ISSUE THREAD

**Issue by ispam** [mockk/mockk#238]
Hello, 

I am trying to learn how to correctly use MockK functionalities with RxJava2 and Unit Testing in general, but currently in the web there's not a lot about it, so I am asking here if by chance has someone successfully implemented MockK with RxJava2 and if it is possible to share a public repo.

Thanks in advance and if this is not the correct place to ask that I'll delete this.

**Comment by oleksiyp** [comment]
That's a perfect place, but maybe as well you can cross-post on StackOverflow, share it in Kotlinslack #general, https://reddit.com/r/Kotlin/. And than there is a chance people will notice it.

I myself interested if there is any experience.

**Comment by streetsofboston** [comment]
@ispam What are you exactly looking for? When using Rx Java, it shouldn't matter which testing-framework you are using. You can test your Rx Java code using plain Junit tests, Mockito, MockK, etc.

**Comment by oleksiyp** [comment]
See no further discussion. From my point of view this is perfect candidate for StackOverflow question
