### ISSUE TITLE
SLF4J warnings

### ISSUE THREAD

**Issue by GrahamBorland** [mockk/mockk#243]
I just tried MoccK as a replacement for Mockito with my Android unit tests.

```
testImplementation "io.mockk:mockk:1.9"
```
My tests pass, but I now get this warning every time I run them:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
How can I get this warning to go away?

**Comment by oleksiyp** [comment]
Either exclude slf4j or provide implementation alike logback

**Comment by GrahamBorland** [comment]
I was able to make the warnings go away by adding this dependency:
```
    testImplementation "org.slf4j:slf4j-nop:1.7.21"
```

**Comment by oleksiyp** [comment]
Released [1.9.1](https://github.com/mockk/mockk/releases/tag/1.9.1). Please try it out and close the ticket if everything is fine.

**Comment by GrahamBorland** [comment]
Works nicely now, thanks!

**Comment by jd565** [comment]
@oleksiyp These warnings seem to have reappeared with 1.13.4 (probably to do with the issue above). Do we need to add the nop implementation now or is there a fix that can be put back in?

**Comment by Danil0v3s** [comment]
`1.13.5` also seems to have this issue

**Comment by ianbrandt** [comment]
I just updated to 1.13.7 with the hope that PR #1091 would alleviate this issue, but I'm still getting the warnings whenever there's not a SLF4J provider on the classpath.

**Comment by IonutNegru87** [comment]
I've tried 1.13.8 and it seems this issue was fixed!

**Comment by carterhudson** [comment]
Still seeing it in 1.13.9

**Comment by mbalajee** [comment]
Seeing it in 1.13.12
