### ISSUE TITLE
Feature: Relaxed mock without chaining

### ISSUE THREAD

**Issue by Sam-Kruglov** [mockk/mockk#248]
Hey, I would like an option where relaxed mock would return `null` for all object return types. I just spent a bunch of time debugging that somewhere deep an `Optional` was mocked and returned false for both `isPresent()` and `isEmpty()`. This is very unexpected, especially coming from Mockito. Because of this we have declared `relaxed = true` a code smell and never use it. But I miss the times when Mockito would do relaxed mode by default without creating chained mocks all over the place unless explicitly specified.

**Comment by oleksiyp** [comment]
Thanks for thoughts shared. Need to think about it, not this week/release

**Comment by Sam-Kruglov** [comment]
@oleksiyp will you think some more about it? :)

**Comment by oleksiyp** [comment]
@Sam-Kruglov tbh honest the answer is rather no. I didn't want to close it right away, but my filling was that this is not a quite right thing. This is such kind of tickets where I am keeping way too long, but know that I am not interested to do. So thanks `stale bot`!

I understand spent time regarding finding the cause, but when you type `relaxed = true` indeed you take the responsibility regarding how it behaves.

And MockK just behaves differently from Mockito. That might be unexpected, but adding one more compatibility flags kind of weird and makes the system too complex.

Documentation probably should be improved, but currently, I am busy with my current work, so happy if somebody would volunteer.
