### ISSUE TITLE
Mockk exception is thrown with wrong root cause

### ISSUE THREAD

**Issue by rlsf** [mockk/mockk#251]
### Expected Behavior

Mocked method which throws exception should report the original method as its exception cause.

### Current Behavior

Mocked method which throws exception reports the throw declaration (test class) as its exception cause.

#### class code:
```
class MyGraph {
...
  fun connect(): SqlgGraph {
        try {
            return SqlgGraph.open(configuration)
        } catch (t: Throwable) {
            throw RuntimeException("Cannot connect to graph repository", t)
        }
  }
}
```

#### test code:
```
class MyGraphTest {
...
  val gr = MyGraph()

  @Test
  fun openFails()  {
     mockkStatic(SqlgGraph::class)
     every { SqlgGraph.open<SqlgGraph>(any<Configuration>())} throws IllegalStateException("because")

     val ex = assertThrows<RuntimeException> {  gr.connect() }
     ex.printStackTrace()
  }
}
```

#### results in this error stack:

Caused by: java.lang.IllegalStateException: because
	at MyGraphTest.openFails(File:Line)

#### instead of 

Caused by: java.lang.IllegalStateException: because
	at SqlgGraph.open(File::Line)

#### Context

* MockK version: 1.9
* OS: Windows 10
* Kotlin version: 1.3.20
* JDK version: 8
* JUnit version: 5.2.0
* Type of test: Unit test

**Comment by oleksiyp** [comment]
The problem is that it is hard/impossible to rewrite stack trace I believe as it is JVM internal functionality

**Comment by Morteza-Rastgoo** [comment]
Same issue here

**Comment by Nodrex** [comment]
Same issue for me
