### ISSUE TITLE
how to mock public variables of Java class

### ISSUE THREAD

**Issue by ktiniatros** [mockk/mockk#252]
- [✓] I am running the latest version
- [✓] I checked the documentation and found no answer
- [✓] I checked to make sure that this issue has not already been filed

### Expected Behavior

Mock public properties of a Java class using every:
The Java class:
```
public class LoginResult extends WebRequestResult
{
    public Boolean MaxLoginAttemptsReached = false;
    public String userid = "";
}
```
Trying to mock the class variables in my Test.kt:
```
val loginResult = mockk<LoginResult>()
every { loginResult.MaxLoginAttemptsReached } returns true
every { loginResult.userid } returns "userid"
```

### Current Behavior

```
io.mockk.MockKException: Missing calls inside every { ... } block.

	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:48)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)
```

Should I be able to mock java class public variables like this? Or is there another way?

**Comment by fellahi-ali** [comment]
Hi, 
I'm not sure about this statement but I think that in `every` block you need to specify a method call.
So in your case you have to implement getters for  the two fields `MaxLoginAttemptsReached` and `userid`
and specify them in the `every` block as follow:

```koltin
every { loginResult.getMaxLoginAttemptsReached() } returns true
every { loginResult.getUserid() } returns "userid"

```

**Comment by oleksiyp** [comment]
Mocking fields is not possible in MockK. It is global transformation.

**Comment by ktiniatros** [comment]
Thank you guys for your replies.

Unfortunately, I cannot change the Java class to add getters/setters so for now I will just set values:
```
loginResult.MaxLoginAttemptsReached = true
loginResult.userid = "userid"
```
If you have a better suggestion (with the prerequisite that the Java class cannot change) let me know please.

**Comment by oleksiyp** [comment]
Only way probably is to use PowerMock https://stackoverflow.com/questions/8995540/mocking-member-variables-of-a-class-using-mockito

Maybe this will be useful: https://github.com/mockk/mockk/issues/79#issuecomment-438940991

**Comment by chiara-jm** [comment]
is there any plan on supporting this feature?
