### ISSUE TITLE
Mockk with coroutines is slow

### ISSUE THREAD

**Issue by giangpham96** [mockk/mockk#262]
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I have the following block of code and expect it doesn't take more than 200ms to execute
```
        val useCase: SearchMoviesUseCase = mockk {
            coEvery { execute("Abc") } returns MovieSearchResult(firstMovieList, 200)
            coEvery { execute("Abc", 2) } coAnswers {
                delay(100)
                throw Exception()
            }
            coEvery { execute("Batman") } returns MovieSearchResult(secondMovieList, 1)
        }
``` 
### Current Behavior
However, after running, the test is slow. I put `println(System.currentTimeMillis())` before and after the code block, and found out that it takes more than 1700ms

**Comment by oleksiyp** [comment]
It is not coroutines. It is ByteBuddy initialization. Uit is very costly. All next tests should run fast.

**Comment by giangpham96** [comment]
True, I just noticed the same thing. Thanks @oleksiyp
