### ISSUE TITLE
Bug: `withArgs` breaks IDEA test coverage

### ISSUE THREAD

**Issue by aurozhkov** [mockk/mockk#266]
* MockK version: 1.9
* OS: MacOS
* Kotlin version: 1.3.21
* JDK version: 1.8.0_45
* JUnit version: 4.12
* Type of test: unit test

this code snippet works correctly and allow to see code coverage:
```kotlin
@Test
fun `test change type clicked 1`() {
    presenter.onChangeTypeClicked()
    verify { router.addScreen(any()) }
}
```

this test works correctly:
```kotlin
@Test
fun `test change type clicked 2`() {
    presenter.onChangeTypeClicked()
    verify { router.addScreen(withArg { it is RootScreens.AddressTypeSelection }) }
}
```
but if we run it with test coverage it throws exception:
```
(Coverage): Class data was not extracted: *.presentersTests.CreateAddressTests$test change type clicked 2$1$$special$$inlined$withArg$2: java.lang.Throwable
(Coverage): Class data was not extracted: *.presentersTests.CreateAddressTests$test change type clicked 2$1$$special$$inlined$withArg$1: java.lang.Throwable
```

I understand that it could be bug with IDEA coverage plugin, but mockito's argThat works as expected

**Comment by oleksiyp** [comment]
Ok, will check later

**Comment by francescogatto** [comment]
the same with `when`

**Comment by Raibaz** [comment]
I think this can be resolved by using a slot instead of `withArg`.
