### ISSUE TITLE
Can't find Outcome.*

### ISSUE THREAD

**Issue by SevenWalnut** [mockk/mockk#275]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
Figure out how to use `Outcome.OK` and ` Outcome.RECORED`

### Current Behavior
Android Studio can't find it.
![image](https://user-images.githubusercontent.com/11713363/54739819-5d3ea200-4bf4-11e9-9183-19a8a0a12495.png)

#### Context
* MockK version: 1.9.1.kotlin12
* OS: MacOS 10.14.3
* Kotlin version: 1.3.21
* JDK version: 1.8
* JUnit version: 4.12
* Type of test: android instrumented test

**Comment by oleksiyp** [comment]
It just an example of enum defined by user, so it is fake

**Comment by son1112** [comment]
Thanks @oleksiyp. It might be helpful to mention in the documentation as it gives the impression this is an expected object from mockk or junit. I searched around quite a bit before finding the answer in this issue.
