### ISSUE TITLE
Calls to same mock:

### ISSUE THREAD

**Issue by Kuldeep-Kumar-Sharma** [mockk/mockk#286]
Whenever I am running verify it always points to mockked service that it is a call to same mock , I don't know Why?

**Comment by Kuldeep-Kumar-Sharma** [comment]
internally it is calling this executeRecursively

**Comment by oleksiyp** [comment]
Can you share some code(minimized), so it is possible to reproduce?

**Comment by Kuldeep-Kumar-Sharma** [comment]
can you help, me to know , how can we ignore certain parameters in object when we do verify of calls, I think it is happening due to it

**Comment by oleksiyp** [comment]
`any()` I believe is a matcher that disregards parameters

**Comment by Kuldeep-Kumar-Sharma** [comment]
yeah, Thanks

**Comment by Kuldeep-Kumar-Sharma** [comment]
I have another issue, actually, I was trying to mock exception especially the custom exception on the repo, like some service exception, I am trying to mock the exception from every ({}) block that throws the exception, and when I am trying the relaxed mockk it says it gives the exception
