### ISSUE TITLE
Q: Where to put the settings.properties in an Android project?

### ISSUE THREAD

**Issue by Moes81** [mockk/mockk#290]
We're using MockK for unit testing our Android project. Since we almost always use `mockk(relayed=true)` we wanted to set it as default in the settings.properties as suggested in the docs.

It says: "create io/mockk/settings.properties file in resources."

Ok, so I thought it would be a good idea to put it here: src/main/res/io/mockk/settings.properties. Unfortunately, it does not work. If I remove the explicit relaxed=true in the individual mocks all the tests fail.

So, where do I actually place the settings file?

**Comment by oleksiyp** [comment]
In pure java it would be "src/test/resources/io/mockk/settings.properties". I am not Android dev that's why pointing to resources means this thing for me. Obviously for Android it might mean res

**Comment by Moes81** [comment]
Hi @oleksiyp ! Thank you for the quick response. 
I was jsut about to start banging my head against the wall, because I put it in `src/MAIN/res/` not `src/TEST/res/`. But unfortunately, even after moving it to `app/src/test/res/io/mockk/settings.properties` I still get failing tests with `io.mockk.MockKException: no answer found for`. 
Maybe some of the Android devs using this great lib have a clue.

**Comment by oleksiyp** [comment]
Try "resources" not "res"

**Comment by JiongBull** [comment]
It works well in android environment. @Moes81 

![image](https://user-images.githubusercontent.com/4413502/57119112-592ca500-6d9a-11e9-9c39-929186804b03.png)

**Comment by Moes81** [comment]
Thank you guys, for the quick support! Putting the file to 
`app/scr/test/resources/io/mockk` did the trick.

Thank you!
