### ISSUE TITLE
What's Mockito's clearInvocations equivalent?

### ISSUE THREAD

**Issue by fjna** [mockk/mockk#292]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

It should be possible to reset or ignore previous invocations/calls without losing the current stubbing/mocking so that in a situation where the test is a stateful scenario the subsequent tests can continue unaffected.

### Current Behavior

There seems to be no way to reset invocations/calls and not lose the current stubbing/mocking, and during a stateful scenario the original stubbing is lost when using for example `clearMocks`

**Comment by Stvad** [comment]
@sum-elier why did you close this one? I can't seem to find an analogue :(

**Comment by obecker** [comment]
I guess the solution is
```
clearMocks(theMock, answers = false)
```
(however, it should be better documented)
