### ISSUE TITLE
clearAllMocks() bleeds into tests in other files

### ISSUE THREAD

**Issue by Puddnhead** [mockk/mockk#301]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

`clearAllMocks()` should only clear mocks in the current scope

### Current Behavior

When running a full test suite in Spek, `clearAllMocks()` is clearing mocks defined in different tests from different files, causing other tests to fail.

### Failure Information (for bugs)

Mocks in other tests are reporting that they have no answer when run alongside other tests that include calls to `clearAllMocks()`

#### Steps to Reproduce

1. Write a few Spek tests with mockk mocks in them
2. Run the whole test suite in IntelliJ or as part of a gradle build (both cases fail)

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: macOS Mohave
* Kotlin version: 1.3.10
* JDK version: 1.8
* JUnit version: 4.12
* Type of test: Spek Unit Test

#### Failure Logs

```
10:13:59.324 [main] DEBUG i.m.i.r.states.AnsweringState - Throwing io.mockk.MockKException: no answer found for: Blob(#171).getBlobId() on Blob(#171).getBlobId()

io.mockk.MockKException: no answer found for: Blob(#171).getBlobId()
```

#### Minimal reproducible code (the gist of this issue)

SomeSpec.kt
```kotlin
internal class SomeSpec : Spek({
    describe("SomeSpec") {

        beforeEach {
            clearAllMocks()
        }

        it("runs a test") { assertTrue(true) }
}
```

SomeOtherSpek.kt
```kotlin
internal class SomeOtherSpec : Spek({
    describe("SomeOtherSpec") {
        val someMock = mockk<SomeClass>()
        every { someMock.someMethod() } returns "something"

        it("runs a test") {
           assertEquals("something", someMock.someMethod()) 
        }
}
```

**Comment by oleksiyp** [comment]
In case your tests get execute in parallel you are not able to use `clearAllMocks`

**Comment by xzhang-brex** [comment]
fyi this should be resolved after this is merged: https://github.com/mockk/mockk/pull/1276
