### ISSUE TITLE
Bug: private dynamic call does not work with `any()`

### ISSUE THREAD

**Issue by dtieber** [mockk/mockk#304]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I am mocking a class which I cannot control, and I'd like to check if a protected method has been invoked. However, this is not really possible with because `invoke` requires `withArguments` and in my case, it is not possible to provide a list of arguments and `any()` doesn't work either. 

### Current Behavior

verification fails

#### Steps to Reproduce

see code snippet below

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: macOS 10.14.5
* Kotlin version: 1.3.31
* JDK version: openjdk 11.0.2 2019-01-15
* JUnit version: 5
* Type of test: unit test

#### Stack trace
```
io.mockk.MockKException: can't find function fooPrivate(java.lang.Object@7971279) for dynamic call

	at io.mockk.InternalPlatformDsl.dynamicCall(InternalPlatformDsl.kt:122)
	at io.mockk.MockKMatcherScope$DynamicCallLong.withArguments(API.kt:1978)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
class MyClass{
    fun foo() {
        val random = "imagine i was random"
        fooPrivate(random)
    }

    private fun fooPrivate(something: String){
        println("i'm hard to test: $something")
    }
}

Given("a class which is hard to test") {
    val out = spyk(MyClass(), recordPrivateCalls = true)

    When("foo is invoked") {
        out.foo()

        Then("fooPrivate is invoked as well") {
            verify {
                // works:
                out invoke "fooPrivate" withArguments listOf("imagine i was random")

                // doesn't work: 
                out invoke "fooPrivate" withArguments listOf(any())
            }
        }
    }
}
```

**Comment by Raibaz** [comment]
I think there may be an issue with the test you are trying to write here. 

If the class you are mocking is a class you cannot control, in my opinion you should just be testing its external behavior, not what happens internally; it is its own tests' responsibility to test that `fooPrivate`  is called with the appropriate parameters whenever you call `foo`.

Thus, it feels right to me not to be able to verify private methods of a class; what you can (and should, IMHO) verify is its external behavior, not the internals.

Does this make sense to you?

What exactly do you want to test here?

**Comment by dtieber** [comment]
I basically don't disagree with what you said, but it does not really answer the question. The framework allows me to verify the invocations of private methods in general, but it does not work with `any()`.

To be honest, I can't remember the real-world use case anymore. I guess I tried to cover some side effects as good as possible. You're right - this is most certainly not a best practice, but I'd argue that it can make sense in rare cases.

**Comment by KarenSarmiento** [comment]
I think you want to use allAny<type of object you want to mock>() instead of any()

**Comment by aschugunov** [comment]
I think it is relevant to protected methods too. Sometimes I would like to verify all protected methods were invoked via public one

**Comment by stopfuckinlyin** [comment]
The solution to this (for me, at least) was to do what @KarenSarmiento suggested:

Explicitly give type information to the any<..>() or allAny<..>() functions.
You need to supply the type arguments or the to-be-tested function wont be callable through JVM reflection.
I assume this is because no matching signature is found. 

Verifying a private function using reflection, like this
`verify{ testObject["privateFunction"](any()) }`
should result in a hint along the lines of
```
"No member 'privateFunction' with params java.lang.Object found for com.stuff.TestObject@64bef4. 
If you were trying to verify a private function, make sure to provide type information to exactly match the functions signature"
```

**Comment by Raibaz** [comment]
Yep I agree that the case @stopfuckinlyin mentions should be explicitly handled in an error message,
