### ISSUE TITLE
mock-js:1.9.3 not published

### ISSUE THREAD

**Issue by saschpe** [mockk/mockk#306]
### Expected Behavior
The mockk-js version should match mock-common, mock-android, etc. and be based on Kotlin-1.3.x

```gradle
implementation("io.mockk:mockk-js:1.9.3")
```

### Current Behavior
The only version that is available is:

```gradle
implementation("io.mockk:mockk-js:1.7.17")
```

### Failure Information (for bugs)

```
> Could not resolve all task dependencies for configuration ':core:jsTestRuntimeClasspath'.
   > Could not find io.mockk:mockk-js:1.9.3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/mockk/mockk-js/1.9.3/mockk-js-1.9.3.module
       - https://dl.google.com/dl/android/maven2/io/mockk/mockk-js/1.9.3/mockk-js-1.9.3.pom
       - https://jcenter.bintray.com/io/mockk/mockk-js/1.9.3/mockk-js-1.9.3.module
       - https://jcenter.bintray.com/io/mockk/mockk-js/1.9.3/mockk-js-1.9.3.pom
       - https://repo.maven.apache.org/maven2/io/mockk/mockk-js/1.9.3/mockk-js-1.9.3.module
       - https://repo.maven.apache.org/maven2/io/mockk/mockk-js/1.9.3/mockk-js-1.9.3.pom
     Required by:
         project :core
```
#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. See above

#### Context

Multiplatform project with a jsTest source set:

* MockK version: 1.9.3
* Kotlin version: 1.3.31

```kotlin
    sourceSets {
        // ...
        getByName("jsTest") {
            dependencies {
                implementation(kotlin("test-js"))
                implementation("io.mockk:mockk-js:1.7.17")
            }
        }
        // ...
    }
```

**Comment by saschpe** [comment]
Basically one can't use mockk in JS multiplatform-modules with Kotlin 1.3 / stable coroutines...

```
> Task :core:compileTestKotlinJs
e: Foo.kt: (19, 9): Using 'coEvery(noinline suspend MockKMatcherScope.() -> T): MockKStubScope<T, T>' is an error. Experimental coroutine cannot be used with API version 1.3
```

**Comment by saschpe** [comment]
I kind of wonder how the library is published as it doesn't seem to use the `maven-publish` et al Gradle plugins

**Comment by oleksiyp** [comment]
It experimental to build yourself, not ready for general usage

**Comment by saschpe** [comment]
So should this ticket link to #100 and marked as a duplicate or should the current state be published even though it's experimental? I'd prefer the latter for lack of other (good) options...

**Comment by Raibaz** [comment]
This can be closed, 1.9.3 is published now.

**Comment by chardskarth** [comment]
Help. Issue is closed but mockk-js is not yet published.

**Comment by eugenio1590** [comment]
I searched for this library at https://mvnrepository.com/ and I saw that version but with a DSL format. You can see this [here](https://mvnrepository.com/artifact/io.mockk/mockk-dsl-js/1.10.0) but this did not work. I hope this issue will be resolved soon.
