### ISSUE TITLE
MockStatic calls real method 

### ISSUE THREAD

**Issue by aligurelli** [mockk/mockk#308]
### Expected Behavior

not call real methods if I mocked class

### Current Behavior

Even i mocked static class, which name is TagManagerUtil, it still try to call real methods. I put the code below.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: macOS 10.14.1
* Kotlin version:1.3.30
* JDK version: 11.0.1
* JUnit version: JUnit 4.12
* Type of test: unit test 

#### Minimal reproducible code (the gist of this issue)

```
 @Test
    fun it_should_name() {
        mockkObject(AnalyticsUtil)
        mockkStatic(TagManagerUtil::class)
        
        AnalyticsUtil.test()

        verify { TagManagerUtil.test() }
    }

AnalyticsUtil{
 fun test() : String {
        return TagManagerUtil.test()
    }
}

TagManagerUtil{
public static String test(){
        return "test";
    }
}
```

**Comment by mesut** [comment]
Any progress or workaround ?

**Comment by abangfadli** [comment]
@mesut 
The workaround would be to specify mock to the function you want to avoid using real implementation.
```
mockStatic(StaticClass:class)
every { StaticClass.staticMethod(any) } returns mockk()
every { StaticClass.staticMethodReturningUnit(any) } just Runs
```

**Comment by mesut** [comment]
Thank you. It works well

**Comment by calvarez-ov** [comment]
This workaround doesn't seem to work for me (mockk 1.9.3). Even if I `return mockk()`, it calls into the real implementation.

**Comment by abangfadli** [comment]
That's weird, it works in my setup. 
Mind share the complete code, @calvarez-ov?

**Comment by calvarez-ov** [comment]
Sorry for the delay. Unfortunately my project is not open source, and I haven't invested the time to create an independent project to reproduce this issue. I ended up using a Robolectric shadow instead, to mock the static method (which was in a third-party java lib)

**Comment by oleksiyp** [comment]
The original issue seems to be describing this as it was designed. Static mocks behave like spies.

**Comment by pollux-** [comment]
is this because I'm calling java class from kotlin??

**Comment by MrKieren** [comment]
If I have a android method in MyClass:
```
class MyClass {
    fun methodUnderTest() {
        Log.w("Tag", "Warning")
    }
}
```

Then the following test causes this issue:
```
mockkStatic(Log::class)
every { Log.w(any(), String()) } returns mockk()
MyClass().methodUnderTest() // Method w in android.util.Log not mocked. 
```

**Comment by aminography** [comment]
I managed to fix this with `mockkObject`, as the function I wanted to mock is in the companion object. It might help you as well.

```
@Before
fun setup() {
    mockkObject(LoginActivity)
    every { MyClass.start(any(), any(), any()) } returns Unit
}

@After
fun tearDown() {
    mockkObject(MyClass)
    clearAllMocks()
}
```

**Comment by aminography** [comment]
I managed to fix this with `mockkObject`, as the function I wanted to mock is in the companion object. It might help you as well.

```
@Before
fun setup() {
    mockkObject(MyClass)
    every { MyClass.start(any()) } returns Unit
}

@After
fun tearDown() {
    unmockkObject(MyClass)
}
```

**Comment by caltseng** [comment]
> Static mocks behave like spies.

This is not at all intuitive and quite confusing, especially because the syntax is so close to regular mocks with such drastically different behavior.
