### ISSUE TITLE
Bug: failure to match method with default String parameter

### ISSUE THREAD

**Issue by ghost** [mockk/mockk#312]
I'm trying to mock a feature that accepts a parameter but the parameter has a default value.

```
class SomeClass {
    fun someMethod(id: String = "nothing"): SomeOtherClass {
        ...    
    } 
}

...

every { someClass.someMethod() } answers { SomeOtherClass() }
```

### Expected Behavior

The mock works with ignoring the parameter value.

### Current Behavior

Mockk throws `io.mockk.MockKException: no aswer found for: ...`

### Workaround

`every { someClass.someMethod(any()) } answers { SomeOtherClass() }`

**Comment by oleksiyp** [comment]
Should be pretty obvious case tested by tests

**Comment by zenberg** [comment]
Can you please check this again?

**Comment by Raibaz** [comment]
This should be already covered by tests, just need to check if it can be reproduced.

**Comment by Endhuine** [comment]
Can't reproduce this issue with the last version of mockk (1.10.6)

**Comment by Raibaz** [comment]
Thanks for investigating this, I think it can be closed.
