### ISSUE TITLE
Feature: deconstruct mock for data class

### ISSUE THREAD

**Issue by vnickolov** [mockk/mockk#317]
Hi, this is not an issue, rather a question, is there an example on how we can mock Destructuring Declarations?

Thank you in advance.

**Comment by oleksiyp** [comment]
Not sure about it, rather not clear what should be mocked in destructuring declarations

**Comment by vnickolov** [comment]
Thanks for the reply.
What I was trying to do is mock a data class and have it deconstructed.
I managed to work around this by using a real instance rather than mock, I wasn't verifying anything on the class anyway.

Thanks again

**Comment by vnickolov** [comment]
The destructuring declarations can be mocked by mocking each individual components, check this https://pl.kotl.in/-3-nNXdTx
