### ISSUE TITLE
verify * wasNot Called does not behave like verifyNoMoreInteractions

### ISSUE THREAD

**Issue by stoyicker** [mockk/mockk#320]
### Expected Behavior

Mockito's verifyNoMoreInteractions allows you to check for interactions on a mock prior to verifying no more interactions on a mock. For example, let's say I have this:

```kotlin
class Foo(private val x: BarType) {
  fun bar() = x.bar()
}
```

Then I should be able to write the following test:

```kotlin
class FooTest {
  private val x = mockk<BarType>(relaxed = true)
  private lateinit var subject : Foo

  @Before
  fun setUp() {
    subject = Foo(x)
  }

  @Test
  fun myTest() {
    subject.bar()

    verify { x.bar() }
    verify { x wasNot Called }
}
```

And have it pass.

### Current Behavior

The test given above will fail because x.bar() has been called. This is kind of strange as well because in Mockito verifyZeroInteractions, which is what I thought wasNotCalled relied on is just sugar for verifyNoMoreInteractions, which would make the equivalent test pass with Mockito.

#### Steps to Reproduce

See MWE above.

**Comment by oleksiyp** [comment]
Belive https://mockk.io/#verification-confirmation is analogue verifyNoMoreInteractions. On mobile. May be inprecise

**Comment by stoyicker** [comment]
Thanks
