### ISSUE TITLE
use `delay()` in `coEvery { }`

### ISSUE THREAD

**Issue by lukaszkalnik** [mockk/mockk#330]
Is it possible to somehow use `delay()` inside of `coEvery { } answers { ... }` like this?
```
coEvery { longRunningCall() } answers {
    delay(10_000)
    response
}
```
Can it be somehow connected with `TestCoroutineDispatcher` or `TestCoroutineScope` from [kotlinx-coroutines-test](https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-test)?

**Comment by oleksiyp** [comment]
`coAnswers` ?

**Comment by lukaszkalnik** [comment]
Yes, of course... Thank you and sorry for not reading the manual!

**Comment by oleksiyp** [comment]
No worries
