### ISSUE TITLE
Feature: verify strict mocking in Mockito sense

### ISSUE THREAD

**Issue by mikezx6r** [mockk/mockk#334]
### Expected Behavior

Using Mockito with JUnit Jupiter, adding the MockitoExtension enforces strict mocks. Mockito's definition is a bit different than Mockk's definition.

Mockito's definition of strict is that all defined expectations in a test are executed. This is automatically checked by the extension at the end of the test

### Current Behavior

Mockk currently does not automatically report this when the extension is applied. I think attempting to do this manually is also not possible, or a lot of extra work.

I would like the extension to turn this feature on by default, or have Mockk provide an additional extension that can be applied that turns this feature on. JUnit Jupiter supports more than one extension, but I'm not sure if they can interact. I'm also not sure if Extensions can be 'configured' when they're applied, so not sure exactly how it can/should be implemented.

**Comment by amatkivskiy** [comment]
@mikezx6r Is it possible to have this behavior on JUnit 4?

**Comment by mikezx6r** [comment]
@amatkivskiy I believe there's a Rule for JUnit4 that does the same thing.

**Comment by mikezx6r** [comment]
@oleksiyp I've looked into the Mockito Extension code. Basically, a Mock contains a list of Stubs. Each stub object has a 'called' flag.

The Extension then just iterates through all mocks, and their stubs, and reports those that weren't 'called'.

Don't know if that fits into Mockk's approach as I haven't looked at the code yet, but at least it's not very magical.

**Comment by oleksiyp** [comment]
Yes, seems possible to add. Although as a property for extension(if possible)

**Comment by mikezx6r** [comment]
Ok, I'll take a look at it. One issue I'm running into when I try to load the project into IntelliJ. In order to import, it appears the project requires an Android SDK be available, but as I don't develop Android apps, I don't have this on my machine.

Are you able to let me know the easiest way to configure this so I can add it to the DEVELOPMENT.md, and setup my environment correctly?

**Comment by oleksiyp** [comment]
Have you checked https://github.com/mockk/mockk/wiki btw? It has some hints regarding debugging. I think you don't need Android SDK to open in IDEA. 
It should autodetect this situation: https://github.com/mockk/mockk/blob/master/settings.gradle#L1 
Check these one https://github.com/mockk/mockk/blob/master/gradle/detect-android-sdk.gradle Scripts try to find it in HOME directory. Maybe you have directory `$HOME/Android/Sdk` present. Otherwise, it is hard to say.

**Comment by mikezx6r** [comment]
Forgot about the Wiki, but unfortunately that doesn't help. It's actually a Gradle build issue as I just tried building project from CLI. Here's what I get when I try to build. An issue building the Android agent module. So perhaps having an Android SDK is not optional anymore?

* What went wrong:
A problem occurred configuring project ':mockk-agent-android'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by oleksiyp** [comment]
So. I checked. Yes this detect is to automatically detect path, not to exclude Android modules.

Just comment out everything related to Android from 'settings.xml':

![image](https://user-images.githubusercontent.com/5249932/64488089-d8981c80-d243-11e9-8940-4ebe83e0eef3.png)

**Comment by Raibaz** [comment]
This should be relatively straightforward to implement as a flag in the MockKExtension

**Comment by Raibaz** [comment]
This was fixed in v1.12.4.
