### ISSUE TITLE
Called function in verify does not return expected value

### ISSUE THREAD

**Issue by fikr4n** [mockk/mockk#341]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

This is the simplified version of the code that I wanted to test, after digging out the point that caused my test always failed.

```kotlin

object AnObject {
    fun aFun(param: Int) = Unit
    fun anotherFun() = 1
}

fun funToTest() {
    // ...
    AnObject.aFun(AnObject.anotherFun())
    // ...
}

// ...

    @Test
    fun testIt() {
        mockkObject(AnObject)
        funToTest()
        verify { AnObject.aFun(AnObject.anotherFun()) }
    }


```

I expected that mocked object's property or function return value can be used in `verify`, so the test must be successful.

### Current Behavior

Mocked object's property or function always returns the default value (e.g. `""` or `0`) in `verify`, so the output is like this:

```
java.lang.AssertionError: Verification failed: call 2 of 2: AnObject(object AnObject).aFun(eq(0))). Only one matching call to AnObject(object AnObject)/aFun(Int) happened, but arguments are not matching:
[0]: argument: 1, matcher: eq(0), result: -
```

### Failure Information (for bugs)

Not sure if this is a bug or a feature.

#### Steps to Reproduce

Write a code like above, run it.

#### Context

* MockK version: 1.9.3
* OS: macOS Mojave 10.14.5
* Kotlin version: 1.3.21
* JDK version: 1.8.0_152-release
* JUnit version: 4.12
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

```kotlin
package fikr4n.mockk

import androidx.test.ext.junit.runners.AndroidJUnit4
import io.mockk.mockkObject
import io.mockk.verify
import org.junit.Test
import org.junit.runner.RunWith

object AnObject {
    fun aFun(param: Int) = Unit
    fun anotherFun() = 1
}

fun funToTest() {
    // ...
    AnObject.aFun(AnObject.anotherFun())
    // ...
}

@RunWith(AndroidJUnit4::class)
class IssueTest {
    @Test
    fun testIt() {
        mockkObject(AnObject)
        funToTest()
        verify { AnObject.aFun(AnObject.anotherFun()) }
    }
}
```

**Comment by Kerooker** [comment]
unstale

**Comment by oleksiyp** [comment]
The problem is that mocking Int is not supported, so your chain is not actually recognized as a chain.
