### ISSUE TITLE
Spy calls real property instead of mocked one when used inside spied class

### ISSUE THREAD

**Issue by mpost** [mockk/mockk#342]
When spying an object it is possible to mock the behavior of a property. When using the spy the mocked code is only executed when invoked from outside of the object. Any mocked properties invoked from inside the spy call the real code.

### Expected Behavior

When mocking a spy property, i expect the mocked code to be executed no matter if used from the outside or inside.

### Current Behavior

Only the call from the outside invokes the mocked code, while an inside call invokes the real code.

#### Steps to Reproduce

The following test demonstrates the behavior:

```kotlin
@RunWith(AndroidJUnit4::class)
class Test {

  class Person(val name: String? = null) {
    fun hasName() = name != null
  }

  @Test
  fun `should call mocked method from inside spy`() {
    val person = spyk(Person()) {
      every { name } answers { "Bob" }
    }

    assertEquals("Bob", person.name) // correct assertion
    assertTrue(person.hasName()) // unexpectedly returns false
  }

}
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: Win10
* Kotlin version: 1.3.41
* JDK version: 8
* JUnit version: 4.12
* Type of test: unit test

**Comment by mpost** [comment]
I found this issue to still be relevant.

**Comment by oleksiyp** [comment]
Most probably it's not fixable because of rules Kotlin compiler applies. It just doesn't generate any method call which can be intercepted.

**Comment by oleksiyp** [comment]
Similar to #104, but doesn't seem to be easily achievable. Closing. Good luck
