### ISSUE TITLE
Split Ordering into "Ordered" and "All"

### ISSUE THREAD

**Issue by camsteffen** [mockk/mockk#345]
If I understand correctly, the `Ordering` enum/property is actually two boolean properties combined into one.

1. Ordered: the interactions should be in order
1. All interactions: For each mock mentioned, all interactions with the mock should be present

&nbsp;  | `ALL` | `ORDERED` | `SEQUENCE` | `UNORDERED`
--- | --- | --- | --- | ---
Ordered            | ❌ | ✅ | ✅ | ❌
All interactions | ✅ | ❌ | ✅ | ❌

In my opinion, the API would be simpler to understand and more flexible if it were designed with respect to these two distinct properties instead of the 4 `Ordering` options.

The word "sequence" would then become redundant as it just means "All AND Ordered". (`verifySequence` can be `verifyAllOrdered`)

**Proposal:**
1. Add `ordered` and `all` (or `allInteractions`?) boolean properties to the `verify()` method
1. Rename/deprecate `verifySequence` to `verifyAllOrdered`
1. Deprecate `Ordering` and usages

**Comment by oleksiyp** [comment]
Looks resonable, but belive except docs not much is possible to change in public API and already learned things in people headd

**Comment by Raibaz** [comment]
We could start implementing this as a non-breaking change by adding optional parameters to the `verify()` method and adding a `verifyAllOrdered´ method that, for now, will replicate `verifySequence`.

Then we can mark `verifySequence` and `Ordering` as deprecated and later, in a future release, remove them.

I can try putting together a PR about this if you want.

**Comment by oleksiyp** [comment]
Actually not too happy with forcing 25K people to change every test they wrote during the last 2 years. Maybe possible to have some "public discussion"(on Reddit) and if quite enough people will vote for that worth to do.

Writing more articles on this topic, making docs clear(for example create kind of infographics with clean explanation on what is what) and so on IMHO would work better.

**Comment by Raibaz** [comment]
Got it, makes sense.

**Comment by oleksiyp** [comment]
Don't think this would be ever implemented... closing
