### ISSUE TITLE
Question: What is the lifecycle of object mockks?

### ISSUE THREAD

**Issue by nieldw** [mockk/mockk#350]
What is the lifecycle of an Object mockk? Does mockking an object make my tests dependent on each other or do mockks get cleared after each test class? How about other types of mockks?

Maybe this can be added to the (already great) documentation.

**Comment by oleksiyp** [comment]
Sorry for the long response time.

No magic happens in-between tests.

`mockkObject(obj)` itself clears the state of the object.

If you would like clear additionally use `clearMocks()` and in case you want not only clear but return transformation of classes back you can do `unmockkObject`, but you need to be precise and can lost some performance.

I wouldn't complicate things, just call `mockkObject(obj)`. Coz believe it won't work in some rare cases.

**Comment by oleksiyp** [comment]
Seems answered

**Comment by nieldw** [comment]
Thank you. Just to be 100% clear, if I mockk an object in one test suite it will not be mockked in another?
