### ISSUE TITLE
Bug: mocking Android SDK objects with hidden methods is broken for Android P and newer

### ISSUE THREAD

**Issue by fkirc** [mockk/mockk#351]
**Background**
The painful interaction of Android P mocking and "hidden methods" is a known issue.
"Hidden methods" are public methods of the Android SDK, but they are made unavailable via special "security mechanism" of Android P and later.
Hidden methods are very common throughout the Android SDK.
For example, have a look at https://github.com/mockito/mockito/issues/1395 to get an idea of several mocking bugs that are related to hidden methods.
Note that I am only talking about instrumented tests that are running on an actual Android P device. These bugs should not occur for regular Java Unit tests.

**Android P bug**
Mockk has an additional bug that is related to the bugs that are already known.
Specifically, **Mockk triggers a `NoSuchMethodException` whenever some Android SDK code tries to call a hidden method on a mocked SDK object**.

**Expected behaviour**
This NoSuchMethodException should not happen.
Instead, the hidden method should return some default value.
Of course, it is already a serious problem that we are not able to stub or spy on "hidden methods".
Nevertheless, returning a default value is still better than running into Exceptions at arbitrary places within the Android SDK.

**Bug details**
The NoSuchMethodException is provoked by the Mockk Proxy implementation, which performs a reflection access that the Android P runtime does not like.
The following sample stack trace illustrates the bug for a mocked "android.nfc.Tag" object.

> Caused by: java.lang.NoSuchMethodException: android.nfc.Tag.hasTech [int]
>         at java.lang.Class.getDeclaredMethod(Class.java:2050)
>         at io.mockk.proxy.android.MethodDescriptor.getMethod(MethodDescriptor.kt:22) **// mockk provokes the NoSuchMethodException within the proxy implementation!**
>         at io.mockk.proxy.android.advice.Advice.getOrigin(Advice.kt:37)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at io.mockk.proxy.android.AndroidMockKDispatcher.getOrigin(AndroidMockKDispatcher.java:117)
>         at android.nfc.Tag.hasTech(Unknown Source:14) **// hasTech is a hidden method that is called by some Android SDK code.**

**Possible fixes**
I think that it should suffice to simply catch the NoSuchMethodException and then return a default value. This requires a change of the Mockk Proxy implementation.
However, this fix might have bad side effects for calls to actually non-existing methods.

**Future work**
Returning default values for hidden methods fixes this bug, but it is still not a good solution.
In particular, hidden methods are severely broken for "spy objects".
Instead of forwarding the call to the underlying object, a hidden method on a spy object fails to execute.

**Comment by fkirc** [comment]
@moltmann might be able to solve this issue.
After all, it should be in the interest of Google to have working Mocking frameworks.

**Comment by moltmann** [comment]
Have you looked at: https://github.com/linkedin/dexmaker/blob/master/dexmaker-mockito-inline/src/main/java/com/android/dx/mockito/inline/InlineDexmakerMockMaker.java#L120 ?

**Comment by fkirc** [comment]
Does that mean that we can simply write our own initialization method via this reflection invocation, which then fixes the issue?

**Comment by moltmann** [comment]
I don't know your code. This worked for dexmaker-mockito.

**Comment by fkirc** [comment]
It seems to me that `VmDebug.allowHiddenApiReflectionFrom(class)` enables to circumvent the hidden API limitations for instrumentation tests.

If this is true, then this is also helpful for changing private fields of SDK objects.

**Comment by duffin22** [comment]
You can work around this issue with:

```
adb shell settings put global hidden_api_policy_p_apps 1
```

**Comment by oleksiyp** [comment]
AIT is big pain in general.

Starting from the fact that there are no automatical running tests for MockK in AIT mode and the fact that dexmaker things should be synced either via diff or via full override(and applying kind of diff with MockK changes, or just rewrite it again). The good news is that this work is pretty structured and clear what should be done, so if any specialists in DEX/Android internals/just guy that do it persistent way appear, I am very welcome to volunteer and help.

**Comment by IsaacBerman** [comment]
Any update on this?

**Comment by sbecket5-ford** [comment]
Hello all, What I have observed is that this issue is associate with the version of android studio (at least I think). If I used android studio 3.4.2 I am able to mock sdk objects on API 28 and 29 (at least these are the two that I have selected in my sdk manager). However, when upgrading to android studio 3.5 I am no longer able to mock sdk objects with these APIs selected. This, I think, is because of the removal of support repository in favor of androidx. I hope this helps in the troubleshooting process.

**Comment by calvarez-ov** [comment]
>Returning default values for hidden methods fixes this bug

Any details about this workaround? 

I tried this:
```kotlin
every {mockApplication["isAutofillCompatibilityEnabled"]() } returns false
```

And I still have an issue:
```
E/TestRunner: io.mockk.MockKException: can't find function isAutofillCompatibilityEnabled() for dynamic call
        at io.mockk.InternalPlatformDsl.dynamicCall(InternalPlatformDsl.kt:122)
        at io.mockk.MockKMatcherScope$DynamicCall.invoke(API.kt:1969)
        at com.myapp.MyTestClass$myTest$1.invoke(MyTestClass.kt:72)
```

Even after doing `adb shell settings put global hidden_api_policy_p_apps 1`

**Comment by teresillaja** [comment]
Hello I'm still facing this issue, is there any estimate on when this will be resolved?

**Comment by ahmed-shakil** [comment]
> Hello I'm still facing this issue, is there any estimate on when this will be resolved?

Yes still happening as of today MAY 20, 2020.
My solution was to just use Android API 27 to run these tests.

**Comment by DutchPixels** [comment]
There are still some problems, the changes above made the normal test work again however there is another scenario where it crashes.

For example when you have a class which provides an Intent which would be mocked by Mockk in the following way:
`every { mockActivityIntentFactory.createIntent() } returns Intent()`

Even though the createIntent method is not called MockK still gets in there somehow because when running the following in the mocked Activity/Fragment it still crashes with the NoSuchMethodException.
`                startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("https://www.google.com")))`

```
Caused by: java.lang.NoSuchMethodException: android.content.Intent.migrateExtraStreamToClipData [class android.content.Context]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getDeclaredMethod(Class.java:2050)
	at io.mockk.proxy.android.MethodDescriptor.getMethod(MethodDescriptor.kt:22)
	at io.mockk.proxy.android.advice.Advice.getOrigin(Advice.kt:37)
	at java.lang.reflect.Method.invoke(Native Method)
	**at io.mockk.proxy.android.AndroidMockKDispatcher.getOrigin(AndroidMockKDispatcher.java:117)**
	at android.content.Intent.migrateExtraStreamToClipData(Unknown Source:14)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1721)
	at androidx.test.runner.MonitoringInstrumentation.execStartActivity(MonitoringInstrumentation.java:545)
	at android.app.Activity.startActivityForResult(Activity.java:5320)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
	at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:790)
	at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1258)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1246)
	at mycode.packagename.MyOwnFragment.onButtonClicked(MyOwnFragment.kt:144)
```

Even though the mocked Intent is not used, not started and never touched by the implementation it still creates this AndroidMockKDispatcher which somehow crashes. I believe this is related to the original issue so perhaps it could be re-opened.

**Comment by duffin22** [comment]
@DutchPixels which API level(s) do you see this issue on? The initial fix for this only worked for P and Q. We've added an update to make this work on Android R+ here: https://github.com/mockk/mockk/pull/568, but this has not yet been released.

**Comment by DutchPixels** [comment]
@duffin22 it just happened on API 30.

**Comment by duffin22** [comment]
@DutchPixels I would expect your sample to fail with the current release (1.10.6). This fix has merged to master so should be part of the next release.

cc @Raibaz

**Comment by DutchPixels** [comment]
@duffin22 is there a snapshot I could try?

**Comment by Raibaz** [comment]
1.10.7-SNAPSHOT has recently been uploaded to https://oss.sonatype.org/content/repositories/snapshots/, if you want to give it a try.

**Comment by DutchPixels** [comment]
@Raibaz works perfectly! Thanks for this.

Just curious, when will the full release be? We prefer not to use snapshots but want to move to MockK as soon as possible in our UI tests.

**Comment by Raibaz** [comment]
I have just been doing some more tests with the new release because it includes an upgrade to Kotlin 1.4 and wanted to make sure it did not break compatibility with 1.3.*.

I think I can confirm it now, so I will likely make a release over the next week.
