### ISSUE TITLE
Discussion: Deactive stale bot

### ISSUE THREAD

**Issue by krichter722** [mockk/mockk#356]
The project seems to use stale bot which closes important issues which hasn't been dealt with after a certain time (e.g. #280). Issues don't disappear after a time. The have to be resolved or a decision has to be made to close it. Closing them automatically is of no help for no project ever and causes the overhead that one day you have to figure out which issues are still present and need to be reopened.

**Comment by oleksiyp** [comment]
Right. Probably it can be deactivated now. The reason I done this to automatically prioritize issues. All closed is going to be reviewed at some time. I am currently very busy with my current work(we have big project to migrate to Kubernetes in a bank, so I learn every weekend new stuff), but keep an eye on issues. It is quite hard to resolve many of them in my free time. But even harder to approach 50 issues without guide which is important. Just to read and categorize takes time of weekend. So either I will find more time at some point(alike vacation) or some contributor will appear. Anyway I value all this reports as main project asset and even closed one should be dealt, there is just no time even to organize issues.

**Comment by oleksiyp** [comment]
I am doing kind of `traige` right now and the stale bot has it's value.

**Comment by Raibaz** [comment]
Closing this as stalebot is pretty valuable IMHO: there are some cases where issues are being opened with not enough information to reproduce them, or requiring some further clarifications.

Oftentimes, there is no response to the clarification request, so there is not really much that can be done on our side.

In cases like these, stalebot is valuable as it saves us the time to manually close these issues.
