### ISSUE TITLE
How to View Compiled Jar File for Top-Level Mocking?

### ISSUE THREAD

**Issue by AdamSHurwitz** [mockk/mockk#357]
**How may the compiled Jar file for an Android app built with Android Studio be accessed?** 

_Use case_ - [MockK][1] for JUnit 5 local unit testing in Kotlin, viewing the output of Kotlin  compiled to Java.

_Android Studio version_ - **3.5**

@oleksiyp, [outlines here](https://blog.kotlin-academy.com/mocking-is-not-rocket-science-mockk-advanced-features-42277e5983b5#6cb5), how top-level functions are compiled into Java in this Medium series and in this [StackOverflow post](https://stackoverflow.com/a/52894755/2253682). 

Examining how the Kotlin files are compiled into Java will allow for mocking more advanced top-level functions where the output is not as straightforward as the below.

> For instance, the following example:
>
    // Code.kt source file 
    package pkg
    fun lowercase(str: String): String {...}
    
>translates to:
>
    package pkg;
    class CodeKt {
        public static String lowercase(String str) {...}
    } 

  [1]: https://mockk.io

**Comment by oleksiyp** [comment]
Beleive in Android studio it should be done by examining APK in build outputs:

![image](https://user-images.githubusercontent.com/5249932/65812672-8a36c780-e1ca-11e9-95c5-5e9de0914799.png)

**Comment by AdamSHurwitz** [comment]
Thanks @oleksiyp, very cool to see how the Kotlin methods are transformed into Java. I outlined the full steps [here](https://stackoverflow.com/a/58152176/2253682) for anyone who is unclear.

**Comment by oleksiyp** [comment]
Thanks!

вс, 29 сент. 2019 г. в 06:13, AdamHurwitz <notifications@github.com>:
