### ISSUE TITLE
How to write unit test for function which contains delay

### ISSUE THREAD

**Issue by vikaskj** [mockk/mockk#358]
I want to write unit test for below function:

void function_name() {
 new Thread(() -> {
try {
                Thread.sleep(4000);
//some code
} catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
}

I tried using Thread provided in mockk:

@Test
   fun function_name() {
       val bundle = spyk<Bundle>()
    
       Thread {
           Thread.sleep(4000)
           presenter.navigateToScreen(bundle)
       }.start()

       verify(timeout = 5000){
          //to verify statement
       }
   }

But test fails to verify provided in verify block.

How to test above function which contains delay.

**Comment by oleksiyp** [comment]
What error message do you have?

**Comment by oleksiyp** [comment]
So when you do not put anything in `verify` block it doesn't make any sense.

Check this example:
```
    interface Abc {
        fun foo()
    }

    @Test
    fun test() {

        val mock = mockk<Abc>()

        every { mock.foo() } just Runs

        Thread {
            Thread.sleep(4000)
            mock.foo()
        }.start()

        verify(timeout = 5000){
            mock.foo()
        }
    }
```
