### ISSUE TITLE
Unresolved references to mockk objects

### ISSUE THREAD

**Issue by ChesterEcwid** [mockk/mockk#360]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

Mockk classes and methods resolved well.

### Current Behavior

Hello!
I have a multi-module gradle project and use mockk to implement tests.
In some modules mockk works like a charm, but in another I have errors while compiling project through either IntelliJ IDEA or gradle:
```
Unresolved reference: Runs
Unresolved reference: just
Cannot access class 'io.mockk.MockKStubScope'. Check your module classpath for missing or conflicting dependencies
Unresolved reference: returns
```

In include dependency on mockk as in documentation:
```
testImplementation "io.mockk:mockk:1.9.3"
```

But in some projects it doesn't work.

**Comment by oleksiyp** [comment]
Tends to be more like a problem with your local setup/intelliJ cache/maven cache/e.t.c. But even if not, out of the description it is very hard to get deeper and reproduce the problem, so you would anyway need to do it yourself and provide more information.
