### ISSUE TITLE
Handle `Sequence<*>` as parameters in `verify`

### ISSUE THREAD

**Issue by jdmwood2** [mockk/mockk#361]
Not sure if this is a bug or feature request....

UPDATE: On reflection, I guess this is more of a Kotlin "problem" (that you can't `equals()` sequences). Having said that, it would still be useful if mockk could just handle this case for a programmer, just in tests.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed

### Expected Behaviour

Would be great if you can verify `Sequence` arguments (see example code below)

### Current Behaviour

Sequences can't be verified

#### Steps to Reproduce

In the below example, you can see how it's possible to verify a `List` and `Iterable` argument, but not `Sequence`.

I can understand why this doesn't work (I guess Kotlin doesn't implement equals for Sequences), but as a convenience, would be super useful to have this work.

```
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.abundance.analytics

import io.mockk.*
import org.junit.Test

class SequenceTest {

    interface Foo {
        fun asList(sequence: List<String>)
        fun asSequence(sequence: Sequence<String>)
        fun asIterable(sequence: Iterable<String>)
    }

    val mock = mockk<Foo>()

    /** Doesn't work as you might expect **/
    @Test
    fun testSequence() {
        every { mock.asSequence(any()) } just Runs

        mock.asSequence(sequenceOf("A", "B"))

        // ***Will fail***
        verify { mock.asSequence(sequenceOf("A", "B")) }
    }

    /** OK */
    @Test
    fun testList() {
        every { mock.asList(any()) } just Runs

        mock.asList(listOf("A", "B"))

        verify { mock.asList(listOf("A", "B")) }
    }

    /** OK */
    @Test
    fun testIterable() {
        every { mock.asIterable(any()) } just Runs

        mock.asIterable(listOf("A", "B"))

        verify { mock.asIterable(listOf("A", "B")) }
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
I doubt it is really worth to hide this problem in the library.

You can achieve easy this with extension function:

```
        val mock = mockk<Abc>()

        fun MockKMatcherScope.seqEq(seq: Sequence<String>) = match<Sequence<String>> {
            it.toList() == seq.toList()
        }

        every { mock.foo(seqEq(sequenceOf("abc", "def"))) } just Runs

        mock.foo(sequenceOf("abc", "def"))

        verify { mock.foo(seqEq(sequenceOf("abc", "def"))) }
```
