### ISSUE TITLE
Update "Known issues & worth to remember" about Inline functions being unmockable

### ISSUE THREAD

**Issue by macgills** [mockk/mockk#379]
I ran afoul of this while testing some activity extension functions, as have others: #55 & #27 

It makes perfect sense if you stop and think about it but I simply didn't. I think a doc update could help prevent others from encountering this issue.

**Comment by macgills** [comment]
I think this is an easy win but `important` label is going a bit far

**Comment by CSK73** [comment]
Hi All,
Is there an alternate way to solve the static inline function mocking? I am still trying to figure out how can I achieve this.
Thanks,
CSK

**Comment by Raibaz** [comment]
@macgills you're right, it makes sense to mention it in the docs, I just added a mention.

@CSK73, currently this is not feasible, see the discussion in #27. Not sure about the future, though.
