### ISSUE TITLE
Feature request: mock all new instances of a class

### ISSUE THREAD

**Issue by dasAnderl** [mockk/mockk#381]
Hello, 
thx for your work on mockk, i really love it. but today i came across a possible limitation:
in jmockit i was easily able to define the behaviour of objects created to which i dont have access in my test. meaning that all new instances of the class would have that behavior, when mocked.
a jmockit example:
```
        @Test
	public void parse_noModelCode_throws(@Mocked InstalledBase installedBase) {
		new Expectations() {{
			installedBase.getModelDescriptions();
			result = null;
		}};
		Assertions.assertThatThrownBy(
				() -> InstalledBaseLoader.loadInstalledBases())
				.isInstanceOf(RuntimeException.class)
				.hasMessageContaining("modelDescription missing");
	}
```

however this is - to my knowledge - not possible right now.

**Comment by oleksiyp** [comment]
Isn't constructor mock ia somsthing you are searching for? It has some limmitations, but should support case of newly created instances of a class

**Comment by dasAnderl** [comment]
thx for your answer, you are absolutely right. again to stupid to read the docs :/
here a working example:

```internal class ObjTest : FreeSpec({

        "obj" {

            mockkConstructor(Obj::class)

            every { anyConstructed<Obj>().i } returns 4

            ObjProvider.obj().i shouldBe 4
        }
})

data class Obj(val i : Int = 1)

object ObjProvider {

    fun obj() = Obj()
}```

**Comment by oleksiyp** [comment]
Nws
