### ISSUE TITLE
Feature: Alternative annotation, method, etc. naming without "k"

### ISSUE THREAD

**Issue by pas2al** [mockk/mockk#382]
First of all thanks for the great library. I love using it!

In regards to naming, I would love to have an alternative way of using the library. It's completely a matter of taste, but I am not really happy of the "k" naming style. Not meant for the library itself, but for my actual implementation. I always try to make my code as readable as possible. What do you think of an alternative naming style besides the "k" naming for annotations, methods, etc.?

Like:

```
import io.mockk.mock

@InjectMocks
@Mock
@Spy 
```

Would that be something possible to integrate? I don't want to replace the "k" naming. I would love to see that people can choose what they want to use. Looking forward to what you think. If interested, I would absolutely love to help with this.

**Comment by Kerooker** [comment]
I particularly don't like the name without the extra `K` because people will get confused with other libraries.

I think `mockk` has an extra `k` on purpose, mainly to make a difference to the other libs.

An alternative for you, although you won't like it either is to use an import alias
```
import io.mockk.mockk as mock
```

**Comment by oleksiyp** [comment]
Two options would confuse people even more

**Comment by pas2al** [comment]
In some cases, it seems inconsistent to me. For example we have functions like `mockk` and `spyk` and on the other hand we have functions like `verify` (in different variations without k) and `clearMocks`. Is there a reason for that?

**Comment by oleksiyp** [comment]
Perfect is the enemy of good :smile:
