### ISSUE TITLE
[Feature request] Support capturing all values similar to Mockito's getAllValues

### ISSUE THREAD

**Issue by Ethan1983** [mockk/mockk#390]
Mockk's capture works great for capturing a value corresponding to single invocation. However, in some tests, i would like to capture values for all invocations. This would be similar to Mockito ArgumentCaptor's getAllValues.

https://static.javadoc.io/org.mockito/mockito-core/2.6.9/org/mockito/ArgumentCaptor.html

**Comment by oleksiyp** [comment]
Try using mutableListOf() for it

**Comment by Ethan1983** [comment]
Thanks did you mean to use an explicit list and add values into from answers block? While that works, i was hoping for an out of box support like CapturingSlots or something like that which returns a list of all values passed to the function.

class Sample {
    fun doSomething(value : Int) {}
}

    @Test
    fun `check multiple doSomething invocations`() {

        val obj = mockk<Sample>()
        val slot = CapturingSlot<Int>()
        every { obj.doSomething(capture(slot)) } just Runs

        obj.doSomething(5)
        obj.doSomething(7)

        assert(slot.captured == 5)
    }

**Comment by Kerooker** [comment]
```
val list = mutableListOf<String>()

every { obj.doSomething(capture(list)) } just Runs
// ...
```

**Comment by Kerooker** [comment]
There's an overload for doing the capture in a mutable list

**Comment by Ethan1983** [comment]
Gotcha, that does it. Thanks @Kerooker @oleksiyp.
