### ISSUE TITLE
Document contributing to documentation

### ISSUE THREAD

**Issue by kibertoad** [mockk/mockk#392]
Currently it is completely unclear how one can contribute to documentation provided at `https://mockk.io/`. I would like to submit some enhancements, but have no idea where and how to do that. Clarifying it in project documentation would be helpful for enabling potential contributors.

**Comment by kibertoad** [comment]
So it seems that the way to do that is by modifying `https://github.com/mockk/mockk/blob/master/README.md`.
Would be helpful to mention that explicitly.

**Comment by oleksiyp** [comment]
@kibertoad I know it may be hard first time, but in reality it's super standard approach. Don't think I should learn people how to use github. It may confuse even more. Closing for now
