### ISSUE TITLE
[Feature request] Support Mockito's MockSettings.withSettings(). extraInterfaces

### ISSUE THREAD

**Issue by hernandazevedozup** [mockk/mockk#396]
It would be great if we had the feature below to add interfaces to the mocked objects like:
```
//Creates mock with extra interfaces
   Foo mock = mock(Foo.class, withSettings()
                                .extraInterfaces(Bar.class));
```

https://javadoc.io/static/org.mockito/mockito-core/3.1.0/org/mockito/MockSettings.html

**Comment by Kerooker** [comment]
There's support for extra interfaces:

```kotlin
mockk<Foo>(moreInterfaces =Bar::class)
```

Does this solve your issue?

**Comment by hernandazevedozup** [comment]
> There's support for extra interfaces:
> 
> ```kotlin
> mockk<Foo>(moreInterfaces =Bar::class)
> ```
> 
> Does this solve your issue?

Yes. Thank you.
