### ISSUE TITLE
Update byte-buddy to 1.10.5

### ISSUE THREAD

**Issue by tmohme** [mockk/mockk#400]
Please update `byte-buddy` to 1.10.5 because this fixes a problem with JVMs that have spaces in their name (e.g. the JVM that comes with  IntelliJ 2019.3 on macOS).

For detailed information pls see the solved [`byte-buddy` issue #732](https://github.com/raphw/byte-buddy/issues/732).
Most of the comments in this issue refer to `mockito` but I have the exact same problem with `mockk` and was able to track it down to the same root-cause in `byte-buddy`.

**Comment by wongk** [comment]
I am also having this issue. I can't use mockk at all.

**Comment by ashrowty** [comment]
Burned a few hours on this. I am not sure if the project is accepting PRs, but I can submit one if committers are ok with it.

**Comment by oleksiyp** [comment]
@ashrowty I accept prs, but main thing is that I am currently not able to build it locally. So to merge build should be recovered and all tests passing

**Comment by mapoulin** [comment]
Also ran into this issue, I worked around by using a different JDK in Intellij (that doesn't have spaces in the path). Please fix :-)

**Comment by raharrison** [comment]
There is PR #426 to update ByteBuddy. Hopefully we can get this merged?

**Comment by oleksiyp** [comment]
Thanks for raising issue, upgraded to 1.10.9 with a new release
