### ISSUE TITLE
lateinit property not initalized

### ISSUE THREAD

**Issue by nschwermann** [mockk/mockk#404]
getting an error lateinit not create with @MockK annotation  Example below. If the MockKAnnotations.init call is moved inside of the runBlockingTest block the test runs fine.

```
internal class CreatePaymentViewModelTest {

    @MockK
    lateinit var decode: DecodeUri
    @MockK
    lateinit var clipboard: Clipboard
    @InjectMockKs
    lateinit var viewModel: CreatePaymentViewModel

    @Before
    fun setup() {
        MockKAnnotations.init(this)
    }

    @After
    fun tearDown() {
        clearAllMocks()
    }

    @Test
    fun plus() {
        val initState = viewModel.makeInitState()
        val lightningInvoice = RequestInvoice()
        val bitcoinUri = BitcoinUri()
        val error = "error"
        val lightningDecode = CreatePaymentViewModel.CreatePaymentState(validRequestInvoice = lightningInvoice)
        val blockChainDecode = CreatePaymentViewModel.CreatePaymentState(validRawInput = bitcoinUri)
        val errorDecode = CreatePaymentViewModel.CreatePaymentState(invalidRawInput = error)
        val inputs = listOf(DecodeUri.Results.Decoding,
                DecodeUri.Results.DecodedLightning(lightningInvoice),
                DecodeUri.Results.DecodeError(error),
                DecodeUri.Results.DecodedBitcoinUri(bitcoinUri),
                DecodeUri.Results.InvalidInput(error))
        val expected = listOf(initState, lightningDecode, errorDecode, blockChainDecode, errorDecode)
        with(viewModel) {
            val actual = inputs.map { initState + it }
            assertEquals(expected, actual)
        }
    }
}
```

kotlin.UninitializedPropertyAccessException: lateinit property viewModel has not been initialized at .CreatePaymentViewModelTest.plus(CreatePaymentViewModelTest.kt:54)

Same as this issue https://github.com/mockk/mockk/issues/47. Using 1.9.3.kotlin12

**Comment by nuhkoca** [comment]
@nschwermann did you solve this issue?

**Comment by nschwermann** [comment]
> @nschwermann did you solve this issue?

Now instead of annotation I use dependency injection

**Comment by nuhkoca** [comment]
Thanks!

**Comment by zarglayoun** [comment]
@nschwermann Could you please tell me what do you mean by using `dependency injection` instead of `annotation?`

**Comment by nschwermann** [comment]
Instead of using the annotation to creat the objects I create them with koin or dagger or manually create for each test .

**Comment by arnonuem** [comment]
I had the same issue. Dont know why the Annotation does not work. I solved it mockking it like this
`private var someRepository = mockk<SomeRepository>()`
