### ISSUE TITLE
How to return different mock data for `every` or `coEvery`

### ISSUE THREAD

**Issue by anticafe** [mockk/mockk#415]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
Sample code like:
```
every { db.loadAll() } return listData1
val items = db.loadAll()

// then run network request
// save result to database, then load data again
val newItems = db.loadAll()
```
I want to set different mock data for each `db.loadAll()` method.

### Current Behavior

It returns the same data for `db.loadAll()`

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: Windows
* Kotlin version: 1.3.61
* JDK version: 1.8
* JUnit version: 4.12
* Type of test: unit test

**Comment by oleksiyp** [comment]
Either https://mockk.io/#additional-answers or `returnsMany`

**Comment by anticafe** [comment]
Thanks @oleksiyp . It works for me.
