### ISSUE TITLE
Method in the every block being executed 

### ISSUE THREAD

**Issue by Kris-Li-lqx** [mockk/mockk#420]
Hi team,

I've commented on this issue already but not sure if that would be checked so opening a new one. https://github.com/mockk/mockk/issues/368

In short, is this a desired behavior that code in the "every" block would be executed? I have a mock and an every block to mock the return value of a function in this mock. In this function, there is a check for a local variable the mock is missing. When I run the test, the check failed within the function in the mock, causing the test failed at the "every" statement. May I know how can I set mockk to only return the value instead of actually executing the function?

Below are the exception I'm seeing and the sample code.

```
java.lang.IllegalStateException: check fails

	at myPackage.ABCCall.call(ABCCall.java:123)
	at myPackage.MyTest$mockABCCall$1$1.invoke(MyTest.kt:35)
	at myPackage.MyTest$mockABCCall$1$1.invoke(MyTest.kt:30)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:24)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithNPERethrow$1.invoke(RecordedBlockEvaluator.kt:74)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:36)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:104)


//My mockk code

@ExtendWith(MockKExtension::class)
class MyTest {									// line 30

    private val mockABCCall = mockk<ABCCall>()

    @Test
    fun test() {
    	val response = Response()
    	every { mockABCCall.call(ofType(Request::class))} returns response  //line 35

    	.....
    }
}


//Dependant Java client
public class ABCCall(Request: input) Response {
	if (some checks) {
		// test failed for this exception since some variables are missing in ABCCall mock 
                // but I don't know why this code would ever be executed in the every block
		throw new IllegalStateException("check fails");		// line 123
	}

        // do something
	return response;
}
```

Kotlin version: 1.3.61
mockk version: 1.9.3
junit version: 5.6.0

Thank you so much!

**Comment by MisterPotz** [comment]
Have the same problem here

**Comment by sbolotovms** [comment]
@Kris-Li-lqx - can you provide your JDK version? I seem to experience the same issue on JDK 9+, but with JDK 8 mockk works just fine.

**Comment by shubhamJay** [comment]
We are facing similar issue. Is there any work around to this?

**Comment by Poorva17** [comment]
We have also observed that in some cases, mockk is not behaving properly. 

**actual behaviour** 
it's calling actual method and getting actual response not the mocked one

**Expected behaviour**
It should call mocked one and return "foo"

```kotlin
val personMock: Person = mockk()
every { personMock.getName() }.answers{"foo"}
personMock.getName() 
```
Note: We are observing this with very specific mocks and are not able to figure out reason.

**Comment by oleksiyp** [comment]
Have you tried other versions of mockk? 1.10.0 for example?

**Comment by Poorva17** [comment]
> Have you tried other versions of mockk? 1.10.0 for example?

Our issue got resolved.. it was due to provided dependency on kotlin side..

**Comment by Kris-Li-lqx** [comment]
> @Kris-Li-lqx - can you provide your JDK version? I seem to experience the same issue on JDK 9+, but with JDK 8 mockk works just fine.

Hi, my JDK version is jdk1.8.0_231.jdk

**Comment by Kris-Li-lqx** [comment]
> Have you tried other versions of mockk? 1.10.0 for example?

Thanks for your response Oleksiy, we may need to go through some internal processes before I'm able to test a higher version, now I'm using the the latest approved version in company. Let me see if I can get it through.

**Comment by sbolotovms** [comment]
@oleksiyp I'm using Microsoft-hosted agents ([link](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)) to run tests. They are using [Zulu JDK builds](https://www.azul.com/downloads/zulu-community/?version=java-8-lts) for their agents. Here's the breakdown of the results on the same set of tests (Android unit tests) for MockK versions 1.10.0 and 1.9.3:

|OS|JDK version|Zulu version|Is block in `every` executed?|
|-|-|-|-|
|Windows|1.8.0.222|8.40.0.25|Sometimes|
|Mac OS|1.8.0.252|8.46.0.19|Never|

Hope this helps.

**Comment by JDAgrawal19** [comment]
Seeing this issue with JDK - 11 and with mockk-1.12.5

**Comment by tokazio** [comment]
It seems that the 'verify' is called on a standard bean, not a mockk or a spyk, then the code is executed
