### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred - spy undeterministic behavior

### ISSUE THREAD

**Issue by Nimamoh** [mockk/mockk#421]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

Test class:
```kotlin
@DataJpaTest
class MyEntityRepositoryTest(
       @Autowired val myEntityRepository: MyEntityRepository
) {

    @Test
    internal fun `repository works`() {

        every { myEntityRepository.saveAll(any<Iterable<MyEntity>>()) } throws ConcurrencyFailureException("Fake error")

        assertThrows<ConcurrencyFailureException> {
            myEntityRepository.saveAll(listOf(MyEntity()))
        }
    }

    @TestConfiguration
    class TestConf {

        @Bean
        @Primary
        fun spiedMyEntityRepository(myEntityRepository: MyEntityRepository) = spyk(myEntityRepository)
    }
}
```

### Expected Behavior

Deterministic behavior

### Current Behavior

Test is non deterministic, also, I get an `illegal reflective access operation`

### Failure Information (for bugs)

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.mockk.InternalPlatformDsl (file:/C:/****/.gradle/caches/modules-2/files-2.1/io.mockk/mockk-dsl-jvm/1.9.3/63de994ae1f30b06395325258d2e5683a8bdd525/mockk-dsl-jvm-1.9.3.jar) to field java.lang.reflect.Proxy.h
WARNING: Please consider reporting this to the maintainers of io.mockk.InternalPlatformDsl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Sometimes the test fails with this error:

```
Receiver class io.mockk.renamed.java.lang.Iterable$Subclass0 does not define or inherit an implementation of the resolved method 'abstract java.util.Iterator iterator()' of interface java.lang.Iterable.
java.lang.AbstractMethodError: Receiver class io.mockk.renamed.java.lang.Iterable$Subclass0 does not define or inherit an implementation of the resolved method 'abstract java.util.Iterator iterator()' of interface java.lang.Iterable.
```

#### Steps to Reproduce

Please see the example project attached with this issue
[illegalreflectiveaccess.zip](https://github.com/mockk/mockk/files/4368014/illegalreflectiveaccess.zip)

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.3
* OS: Windows 10
* Kotlin version: 1.3.61
* JDK version: 12
* JUnit version: 5
* Type of test: unit test

**Comment by VladSVAssets** [comment]
Hi @Nimamoh , have you found a solution/workaround for this? I have a similar issue:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.mockk.InternalPlatformDsl (file:/path/.gradle/caches/modules-2/files-2.1/io.mockk/mockk-dsl-jvm/1.12.2/ee1891316a7a5e326a1da514c6447e74579f4547/mockk-dsl-jvm-1.12.2.jar) to field java.io.File.path
WARNING: Please consider reporting this to the maintainers of io.mockk.InternalPlatformDsl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by mesquitaa** [comment]
Hi @Nimamoh @VladSVAssets, have you found a solution for this? 

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.mockk.InternalPlatformDsl (file:/Users/Hamm/gradle_home/caches/transforms-3/37d23670e5d732ac973d97e63891d81e/transformed/jetified-mockk-dsl-jvm-1.13.5.jar) to field java.util.concurrent.atomic.AtomicBoolean.value
WARNING: Please consider reporting this to the maintainers of io.mockk.InternalPlatformDsl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
``` 

MockK version: 1.13.5
Kotlin version: 1.7.20
JDK version: 11
JUnit version: 4
Type of test: unit test
