### ISSUE TITLE
Bug with coEvery, suspend fun and was not Called 

### ISSUE THREAD

**Issue by StanislavKosyakov** [mockk/mockk#424]
### Expected Behavior

Expected test will go without fail :

```
SomeClass {
    suspend fun someCall(someArg: String)
}
```

```
@Test test() {
    ....
    coEvery {
      someClass.someCall(any) was not Called 
    }
}
```

but 

```
@Test test() {
    ....
    coEvery(exactly = 0) {
      someClass.someCall(any) was not Called 
    }
}
```

work perfecto 

### Current Behavior

test fails with error if I'm using was not Called 

### Failure Information (for bugs)

java.lang.AssertionError: Verification failed: call 1 of 1: SomeClass(SomeClass#3).someCall(any(), any())) was not called

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. take any suspend fun 
2. use coVerify with "was no Called"

#### Context

* MockK version: '1.9.3'
* OS: macOS
* Kotlin version: '1.3.70'
* JDK version: '1.8.0_241'
* JUnit version: 4
* Type of test: unit

**Comment by oleksiyp** [comment]
This is not a bug. Correct way to use `was not called`:
```
    coEvery(exactly = 0) {
      someClass was not Called 
    }
```
