### ISSUE TITLE
Tests affect performance of other tests, despite unmockAll after each

### ISSUE THREAD

**Issue by rocketraman** [mockk/mockk#433]
I have an odd performance issue. I have a package with 4 unit test classes. When running all 4, one particular test takes 25 seconds to run. When running just the class which contains that test, that same test takes 1s to run. The more other tests run, the longer this one test takes.

From a profiler, looks like the perf hit isn't in the mocking process itself -- the massive bulk of time taken is in calling methods on a 3rd party library which were mocked in other tests but in this test *should* now be unmocked via `unmockAll`, which is run after every unit test.

* MockK version: 1.10.0
* OS: Linux 5.5.15
* Kotlin version: 1.3.71
* JDK version: 11.0.7 (adoptopenjdk)
* JUnit version: 5.4.2
* Type of test: Unit test

The specific 3rd party library being mocked is Aspose.Cells, but its a proprietary library so I can't create a reproducer here.

**Comment by oleksiyp** [comment]
Very weird, but hard to figure out what's happening.
Maybe you mock any of the system classes, alike HashMap?

**Comment by rocketraman** [comment]
No, at least not that I'm aware of. Aspose.Cells is compiled with all sorts of obfuscation and I've gotten bytebuddy NPEs when trying to mock other parts of it, so it's possible it's doing something weird. What can we do to dig into this further?

**Comment by wafisher** [comment]
Might be helped by this: https://github.com/mockk/mockk/issues/416
