### ISSUE TITLE
app_name string resource should be deleted from mockk-android

### ISSUE THREAD

**Issue by mnayef95** [mockk/mockk#435]
mockk/mockk/android/src/main/res/values/strings.xml

contains `app_name` which will override `app_name` in test application in multi-module projects so this should be deleted from the library or use another name because `app_name` is most used resource name by all developers as I know

**Comment by anesabml** [comment]
@Raibaz I'd like to work on this, but I am not familiar with mockk APIs so it will be super helpful if you guys could probably provide some guidance if possible.

**Comment by Raibaz** [comment]
@anesabml, thanks! It should be a matter of just removing the app_name string in the resource file (and possibly the resource file altogether), but it requires extensive testing in an android environment to make sure it doesn't break anything.

**Comment by anesabml** [comment]
@Raibaz Thank you for the explanation. I will work on it.
