### ISSUE TITLE
init {} beign called on mockk()

### ISSUE THREAD

**Issue by ivanreffatti** [mockk/mockk#437]
- [ Y ] I am running the latest version
- [ Y ] I checked the documentation and found no answer
- [ Y ] I checked to make sure that this issue has not already been filed

### Expected Behavior

Mocking an object should not call `init {} `

### Current Behavior

mockk() seems to be calling class init{} 

```kotlin
coEvery {
    httpClient.get<HttpStatement>(any<HttpRequestBuilder>())
} returns mockk()
//...
class HttpStatement(
    private val builder: HttpRequestBuilder,
    private val client: HttpClient
) {
    init {
        checkCapabilities() // this method keeps getting called when i try to create the mock
    }
//...
}
```
Error being caused due to init {} being called

java.lang.NullPointerException
    at io.ktor.client.statement.HttpStatement.checkCapabilities(HttpStatement.kt:130)
    at io.ktor.client.statement.HttpStatement.<init>(HttpStatement.kt:30)

**Comment by OliverCulleyDeLange** [comment]
+1. 
I have some generated code that loads a library inside its companion `init{}` block, which isn't available on the test classpath. Instead of mocking `System.loadLibrary` via `mockkStatic` (which has bad side effects), i'd like to find a way to mock an object without its init{} block being called. 

``` User
class User constructor (private val self: Long) {
    companion object {
        init {
            try {
                System.loadLibrary("android")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Native code library failed to load.")
                System.err.println("$e")
                exitProcess(1)
            }
        }
...
}
```

**Comment by ivanreffatti** [comment]
In my case I gave up from the issue and avoided the mock by using ktor MockEngine, but the problema still there, no way of mocking objects with init logics

**Comment by OliverCulleyDeLange** [comment]
I worked around the issue by mocking the System call in a mockkStatic block, then calling mockkClass(it) which calls init {} which calls the static system mock. Works well enough for me. 


```
fun initRustBindings(vararg rustBindings: KClass<*>) {
    mockkStatic("java.lang.System") {
        every { System.loadLibrary("android") } returns Unit
        rustBindings.forEach {
            mockkClass(it)
            println("Mocked ${it.simpleName}")
        }
    }
}

**Comment by PinkieSwirl** [comment]
My problem is that the init block calls a native method. Can those be mocked to?

**Comment by vitorhugods** [comment]
> 
> 
> I worked around the issue by mocking the System call in a mockkStatic block, then calling mockkClass(it) which calls init {} which calls the static system mock. Works well enough for me.
> 
> ```
> fun initRustBindings(vararg rustBindings: KClass<*>) {
>     mockkStatic("java.lang.System") {
>         every { System.loadLibrary("android") } returns Unit
>         rustBindings.forEach {
>             mockkClass(it)
>             println("Mocked ${it.simpleName}")
>         }
>     }
> }
> ```

@OliverCulleyDeLange I never thought I would ever need to mock `System`, but here I am. That was a real out-of-the-box thinking from my perspective. Thanks for that idea.

I needed to mock an instance of a class without going through the `System.loadLibrary` in the static initialization:

```
        mockkStatic(System::class) {
            every { System.loadLibrary(any()) } returns Unit
            myMock = mockk()
        }
``` 

Good work-around for people facing https://github.com/robolectric/robolectric/issues/1171 and/or https://github.com/mockk/mockk/issues/261.

**Comment by helder-sales** [comment]
+1 for that feature. There will be always a case that one will have to use the init block. This gets even worse when the init block is inside a object.

**Comment by poppan2** [comment]
Has anyone found a way around this? I'm also facing the issue where Mocking my Object (Kotlin) is throwing an error due to properties from inside the "init" block

**Comment by kennamatt** [comment]
As a matter of "coming from other programming languages--specifically, go" I got around this problem by creating a factory method called `new` for the class which proxies to the constructor which is then as private as possible--because `new` is easy to mock while the constructor is not.  To be clear, its a kludge, but after a while, you get used to it.

**Comment by johngray1965** [comment]
In my case, the class that had ```
static {
        System.loadLibrary("someLIbrary");
    }
``` was a third party library.   Fortunately, it's methods weren't final.   I was able to make an interface with the methods I needed, and make make a wrapper class that implement the interface, and uses the original class as its base class.

Arrange things so everything uses the interface.  It's not probably to mock the interface.
