### ISSUE TITLE
Mockk wraps kotlin.Result return value twice

### ISSUE THREAD

**Issue by azulkarnyaev** [mockk/mockk#443]
> Just be aware about usual MockK support pattern. 
> Tickets are checked from time to time, replied, discussed, labeled, e.t.c.
> But real fixes are applied in a month-two month period in a bunch.
> If you think this is unacceptable, go on, join the project, change the world.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

After adding `-Xallow-result-return-type` flag I should be able to mock objects with `kotlin.Result` return types  

### Current Behavior

Mockk wraps the result in a such a way that it returns `Result<Result<T>>`

### Failure Information (for bugs)

It fails because of `java.lang.ClassCastException`

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add `-Xallow-result-return-type` flag for Kotlin compilation
2. Create a class with a method `kotlin.Result` as a return type
3. Mock the method invocation 

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: MacOS Mojave, 10.14.6
* Kotlin version: 1.3.72
* JDK version: 1.8
* JUnit version: 5.6.1
* Type of test: unit test

#### Stack trace

```
org.opentest4j.AssertionFailedError: expected:<[]> but was:<Success([It works!])>
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
       testImplementation("io.mockk:mockk:1.10.0")
       testImplementation("io.kotest:kotest-runner-junit5-jvm:4.0.5")
       testImplementation("io.kotest:kotest-assertions-core-jvm:4.0.5")
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
class TestResultBug : StringSpec({

    class TestResult {

        fun test(): Result<List<String>> {
            TODO()
        }

    }

    "should not fail" {
        val mock = mockk<TestResult> {
            every { test() } returns Result.success(listOf("It works!"))
        }
        mock.test().getOrThrow().shouldBe(listOf())
    }

})
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by oleksiyp** [comment]
Is it inline? Duplicate https://github.com/mockk/mockk/issues/152?

**Comment by azulkarnyaev** [comment]
Yes, it's the same bug. Sorry, I couldn't find it before creating the issue.
