### ISSUE TITLE
Documentation update for Delegates

### ISSUE THREAD

**Issue by slavonnet** [mockk/mockk#455]
Need an example of how to use deligates.

I broke my head trying to figure out how to mock Kodein correctly

How right test function like this? No any exaple to mock "by" return.

```
    internal suspend fun cleanUpPersonal(): Boolean {
        val externalServiceUnitsDao by instance<ExternalServiceUnitsDao>()
        val ambulanceUnitsDao by instance<AmbulanceUnitsDao>()
        val hospitalsDao by instance<HospitalsDao>()
        val traumaCentertDao by instance<TraumaCentertDao>()
        val employeesDao by instance<EmployeesDao>()
        val clinicDao by instance<ClinicsDao>()
        val kisNotificationsDao by instance<NotificationsDao>()

        ambulanceUnitsDao.deleteAll()
        externalServiceUnitsDao.deleteAll()
        externalServiceUnitsDao.deleteAllLinks()
        hospitalsDao.deleteAll()
        hospitalsDao.deleteAllLinks()
        employeesDao.deleteAll()
        traumaCentertDao.deleteAll()
        traumaCentertDao.deleteAllLinks()
        clinicDao.deleteAll()
        clinicDao.deleteAllLinks()
        kisNotificationsDao.deleteAll()
        crewDao.deleteAll()

        WorkManager.getInstance(applicationContext).enqueueUniqueWork(
            "Dir",
            ExistingWorkPolicy.APPEND_OR_REPLACE,
            OneTimeWorkRequestBuilder<DirectoryUpdateWorker>().setInitialDelay(5, TimeUnit.SECONDS).addTag("Dir").build()
        )

        return true
    }

```

**Comment by utybo** [comment]
You could try mocking `instance` like any other function (although you may have to use a static mock `mockkStatic` for this, there's some docs for it on the MockK website).

Instead of mocking the `instance` call, you could also provide mocked instances of your injected dependencies to Kodein and have them be injected like a regular dependency, that's how I'm currently doing it with Koin, I'd assume Kodein has a similar feature.

**Comment by slavonnet** [comment]
Delegans base function and great feature of kotlin. Why don't kill billercode and don't create common mock/spy for Delegates?

like 
`mockkBy {instance<customDao>()}`
and
`val mocked: String by mockk { instance<String>("tag") }`
