### ISSUE TITLE
Mocking java.lang.reflect.Method or method returning java.lang.reflect.Method causes StackOverflowError

### ISSUE THREAD

**Issue by dyangelo-grullon** [mockk/mockk#457]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

```kotlin
val methodMock = mockk<Method>()
```

should mock the method and not throw a `StackOverflowError`

```kotlin
val method: Method = (SomeTest)::someHandler.javaMethod ?: throw IllegalStateException("handler not found")

every { handlerMethodMock.method } returns method
```

Should return the method on invocations to `handlerMethodMock.method`, not throw a `StackOverflowError` on mock definition.

### Current Behavior

Both aformentioned scenarios throw a `StackOverflowError`. I arrived at the second scenario after attempting a work-around for the first. 

### Failure Information (for bugs)

Seems to occur due to mocking of java.lang.reflect objects or methods that return such. 
I can't seem to find relevant documentation that may specify a workaround.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: Mac OSX
* Kotlin version: 1.3.61
* JDK version: 1.8.0_222 (OpenJDK Runtime Environment Corretto-8.222.10.1)
* JUnit version: 5
* Type of test: unit test

#### Failure Logs

```
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "Test worker"
```

**Comment by gustavodaquino** [comment]
I'm facing the same error.

- JUnit 5.4.2
- MockK 1.10.0
- JDK 1.8.0_252
- Kotlin 1.3.72

```
Exception in thread "Test worker" java/lang/StackOverflowError
	at java/util/HashMap.get (HashMap.java:557)
	at sun/reflect/Reflection.filterMethods (Reflection.java:291)
	at java/lang/Class.getMethodHelper (Class.java:1265)
	at java/lang/Class.getMethod (Class.java:1191)
```

**Comment by gustavodaquino** [comment]
> ### Prerequisites
> 
> Please answer the following questions for yourself before submitting an issue.
> 
>     * [x]  I am running the latest version
> 
>     * [x]  I checked the documentation and found no answer
> 
>     * [x]  I checked to make sure that this issue has not already been filed
> 
> 
> ### Expected Behavior
> 
> ```kotlin
> val methodMock = mockk<Method>()
> ```
> 
> should mock the method and not throw a `StackOverflowError`
> 
> ```kotlin
> val method: Method = (SomeTest)::someHandler.javaMethod ?: throw IllegalStateException("handler not found")
> 
> every { handlerMethodMock.method } returns method
> ```
> 
> Should return the method on invocations to `handlerMethodMock.method`, not throw a `StackOverflowError` on mock definition.
> ### Current Behavior
> 
> Both aformentioned scenarios throw a `StackOverflowError`. I arrived at the second scenario after attempting a work-around for the first.
> ### Failure Information (for bugs)
> 
> Seems to occur due to mocking of java.lang.reflect objects or methods that return such.
> I can't seem to find relevant documentation that may specify a workaround.
> #### Context
> 
> Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
> 
>     * MockK version: 1.10.0
> 
>     * OS: Mac OSX
> 
>     * Kotlin version: 1.3.61
> 
>     * JDK version: 1.8.0_222 (OpenJDK Runtime Environment Corretto-8.222.10.1)
> 
>     * JUnit version: 5
> 
>     * Type of test: unit test
> 
> 
> #### Failure Logs
> 
> ```
> Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "Test worker"
> ```

You can try change the `JVM` used in your project for an `HotSpot` implementation. My error occurred because I've tried to use an `OpenJ9` implementation.

**Comment by lukesoft** [comment]
Also having the same issue

**Comment by deveth0** [comment]
I was able to reproduce the issue running jdk-11.0.5.10-openj9 and jdk-11.0.8.10-openj9
When I switched to the "normal" jdk (11.0.7+10-post-Debian-3deb10u1 or jdk-11.0.8.10-hotspot), the error disappeared.

**Comment by krzdabrowski** [comment]
This issue also persists in older mockk version (1.8.6)

**Comment by IagoLast** [comment]
Just in case it helps someone I've just had the same issue when trying to run a ./gradlew build using the latest mockk version.

I've used [sdkman](https://sdkman.io/) and switched from 11.0.10.j9-adpt to 11.0.10.hs-adpt and the problem was solved.
