### ISSUE TITLE
Invocation.self - unexpected values

### ISSUE THREAD

**Issue by LocaFoxNick** [mockk/mockk#460]
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

I am trying to work around being unable to verify constructor arguments.  
When calling the following I expect the Invocation.self to have the same values as the constructor
```
clclass MyClass(val myVar: String) {
        fun doSomeThing() { }
    }
    
    @Test
    fun test_myClass() {
        mockkConstructor(MyClass::class)

        var ctorArg = ""
        every { anyConstructed<MyClass>().doSomeThing() } answers {
            ctorArg = (it.invocation.self as MyClass).myVar
        }

        MyClass("Hello, World!").doSomeThing()

        assertEquals("Hello, World!", ctorArg)
    }
```
### Current Behavior

All members of `it.invocation.self.myVar` is null

**Comment by SamerAdra** [comment]
I am having the same issue.
