### ISSUE TITLE
How to verify inner property invokes method?

### ISSUE THREAD

**Issue by anticafe** [mockk/mockk#464]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior
Here the is original class
```
class CarManager(id: String) {
    val carItem = CarItem.create(id)

    fun showName(name: String) {
        if(name.isNotEmpty()) {
            carItem.showCarName()
        }
    }
}

data class CarItem(private val name: String) {
    fun showCarName() {
        println(name)
    }
    companion object {
        fun create(id: String): CarItem {
            return CarItem("Car $id");
        }
    }
}
```
I want to be able to verify the action `carItem.showCarName()`. So, the test would be like this:
```
class CarManagerTest {
    private val carManager = mockk(CarManager("BMW"))
    @Test
    fun verifyShowName() {
        val carItem = spyk(carManager.carItem)
        justRun { carItem.showCarName() }

        carManager.showName("")
        verify { carItem.showCarName() }
    }
}
```

### Current Behavior

The above test doesn't work. It returns error: `Verification failed: call 1 of 1: CarItem(#2).showCarName()) was not called`.

So, is it possible to verify that the property invokes its method inside?

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* Kotlin version: 1.3.72
* JUnit version: 4
* Type of test: Unit Test

**Comment by anticafe** [comment]
Any comment on this issue? :(

**Comment by Raibaz** [comment]
I have been able to get this test to run by writing it as follows:

package io.mockk.gh

```
class Issue464Test {

    class CarManager(id: String) {
        private val carItem = CarItem.create(id)

        fun showName(name: String) {
            if(name.isNotEmpty()) {
                carItem.showCarName()
            }
        }
    }

    data class CarItem(private val name: String) {
        fun showCarName() {
            println(name)
        }
        companion object Factory {
            fun create(id: String): CarItem {
                return CarItem("Car $id");
            }
        }
    }

    @Test
    fun test() {
        mockkObject(CarItem.Factory)
        val carItemMock = mockk<CarItem>()
        justRun { carItemMock.showCarName() }
        every { CarItem.create(any()) } returns carItemMock

        val carManager = CarManager("bmw")
        carManager.showName("test")
        verify { carItemMock.showCarName() }
    }

}
```

Notice that i gave a name to the companion object to be able to mock it with `mockkObject` and then mocked `CarItem.create(any())` to return a mock to run verifications onto.

**Comment by anticafe** [comment]
Thanks @Raibaz . The magic is in `companion object Factory` 💯
