### ISSUE TITLE
Lazy delegates on spied objects don't use the mocked values.

### ISSUE THREAD

**Issue by krodyrobi** [mockk/mockk#468]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

That I am able to spy mock functions used by a lazy delegate block.

### Current Behavior

Lazy block seems to call original function and not mocked version.
Calling the function directly produces correct result.

#### Context

* MockK version: 1.10.0
* OS: macOS 10.15.6
* Kotlin version: 1.3.72
* JDK version: 11
* JUnit version: 5.6.1
* Type of test: unit test

#### STR
```kotlin

class Spied {
    val a by lazy { config() }

    val b get() = config()

    fun config(): String = "bar"
    fun usingCallA() = a.toUpperCase()
    fun usingCallB() = b.toUpperCase()
}

internal class SpiedTest {
    @Test
    fun a() {
        val spied = spyk(Spied())
        every { spied.config() } returns "foo"
        assertEquals("foo", spied.config())
        assertEquals("FOO", spied.usingCallA())
    }

    @Test
    fun b() {
        val spied = spyk(Spied())
        every { spied.config() } returns "foo"
        assertEquals("foo", spied.config())
        assertEquals("FOO", spied.usingCallB())
    }
}
```
#### Failure Logs

Test a() fails with
```
expected: <FOO> but was: <BAR>
Expected :FOO
Actual   :BAR
```

**Comment by SamerAdra** [comment]
I encountered the same issue. I was able to work around it by replacing "by lazy" with "by resettableLazy(this)"; this depends on the following implementation of a resettable lazy:

`import java.util.*
import kotlin.reflect.KProperty

/**
 * Like lazy but with the ability to reset
 */
class ResettableLazyManager {
    // we synchronize to make sure the timing of a reset() call and new inits do not collide
    private val managedDelegates = LinkedList<Resettable>()

    fun register(managed: Resettable) {
        synchronized (managedDelegates) {
            managedDelegates.add(managed)
        }
    }

    fun reset() {
        synchronized (managedDelegates) {
            managedDelegates.forEach { it.reset() }
            managedDelegates.clear()
        }
    }

    companion object
}

interface Resettable {
    fun reset()
}

class ResettableLazy<PROPTYPE>(private val manager: ResettableLazyManager, var init: ()->PROPTYPE): Resettable {
    @Volatile var lazyHolder: Lazy<PROPTYPE> = makeInitBlock()

    operator fun getValue(thisRef: Any?, property: KProperty<*>): PROPTYPE {
        return lazyHolder.value
    }

    operator fun setValue(managingClass: Any, property: KProperty<*>, value: PROPTYPE) {
        lazyHolder = lazy { value }
    }

    override fun reset() {
        lazyHolder = makeInitBlock()
    }

    private fun makeInitBlock(): Lazy<PROPTYPE> {
        return lazy {
            manager.register(this)
            init()
        }
    }
}

fun <PROPTYPE> resettableLazy(managingClass: Any, init: ()->PROPTYPE): ResettableLazy<PROPTYPE> {
    return ResettableLazy(getManagerForClass(managingClass), init)
}

fun resetAllLaziesInClass(managingClass: Any) {
    synchronized(ResettableLazyManager) {
        managingClassToResettableLazyManagers[managingClass]?.reset()
        managingClassToResettableLazyManagers.remove(managingClass)
    }
}

private val managingClassToResettableLazyManagers = mutableMapOf<Any, ResettableLazyManager>()

private fun getManagerForClass(managingClass: Any): ResettableLazyManager {
    synchronized(ResettableLazyManager) {
        if (!managingClassToResettableLazyManagers.containsKey(managingClass)) {
            managingClassToResettableLazyManagers[managingClass] = resettableManager()
        }
        return managingClassToResettableLazyManagers.getValue(managingClass)
    }
}

private fun resettableManager(): ResettableLazyManager = ResettableLazyManager()
`

**Comment by sschuberth** [comment]
Please reopen; this should work out of the box IMO.
