### ISSUE TITLE
Add possibility to pass class into MockKMatcherScope's match

### ISSUE THREAD

**Issue by uvalashchuk** [mockk/mockk#470]
### Expected Behavior

It would be great to have opportunity of calling `MockKMatcherScope.match(...)` with parameter of `KClass`. This will allow creating generic parameterized tests.

### Current Behavior

Currently `MockKMatcherScope` exposes API only with reified parameters.

```
inline fun <reified T : Any> match(matcher: Matcher<T>): T {
    return callRecorder.matcher(matcher, T::class)
}
```

#### Context

* MockK version: 1.9.3
* Type of test: unit test

### Solution

Adding function to `MockKMatcherScope`
```
inline fun <T : Any> match(matcher: Matcher<T>, clazz: KClass<T>): T {
    return callRecorder.matcher(matcher, clazz)
}
```

**Comment by fxshlein** [comment]
Hey, sorry to push this back up - did this ever get solved?
