### ISSUE TITLE
Upgrade to Kotlin 1.4 and support the new IR backend

### ISSUE THREAD

**Issue by pusolito** [mockk/mockk#475]
Libraries that depend on Mockk and want to leverage the new [IR backend](https://kotlinlang.org/docs/reference/whatsnew14.html#unified-backends-and-extensibility) offered by Kotlin 1.4 cannot do so without changes to Mockk. For example, I'd love to upgrade [Doodle](https://nacular.github.io/doodle/) and [Measured](https://nacular.github.io/measured/) to the new backend to improve JS bundle size. 

The changes to Mockk include upgrading to Kotlin 1.4 and building with the new `kotlin.js.compiler` option set to `ir`, or `both`.

_Originally posted by @pusolito in https://github.com/mockk/mockk/issues/374#issuecomment-678993554_

**Comment by oleksiyp** [comment]
I see. Yes, this needs to be done. Hope to allocate some time to rebuild next weekend. 

Hope the new Gradle doesn't brake build, so badly as it was the previous time, requiring few days to recover it.

**Comment by pusolito** [comment]
Are you also planning on unifying (or upgrading) the mockk-js library: #100?

**Comment by pusolito** [comment]
@oleksiyp, did you find time to look into this yet?

**Comment by pusolito** [comment]
ping

**Comment by pusolito** [comment]
Glad to see the new version updates. @oleksiyp, did you find a path forward on this issue?

**Comment by pusolito** [comment]
It looks like Kotlin 1.4 support recently got merged. This is awesome! Will there be IR support as well? How about updating the JS support?

**Comment by Raibaz** [comment]
I'm not familiar yet with the js implementation, so I don't have an ETA for the IR support at the moment.

Sorry about this.

**Comment by pusolito** [comment]
Any updates on IR support and JS lib?

**Comment by Raibaz** [comment]
I recently added a build matrix to test different Kotlin versions and IR support; I still need to find a reliable way to test importing MockK as a dependency in projects with different Kotlin versions, since the last time I released 1.4 support it broke applications running on 1.3.x.

**Comment by pusolito** [comment]
Glad to hear you're making progress on this. Happy to test things out early in [Doodle](https://github.com/nacular/doodle) or [Measured](https://github.com/nacular/measured) if that would help.

**Comment by Raibaz** [comment]
@pusolito i just uploaded 1.10.7-SNAPSHOT, built with Kotlin 1.4.30 and the new IR backend, to https://oss.sonatype.org/content/repositories/snapshots

If you can give a try importing it in a project built with Kotlin 1.3.* and see what happens, that'd be very helpful.

I've been doing some tests on my own projects, but I'd rather be really sure not to break anything before releasing a version built with 1.4.20.

**Comment by pusolito** [comment]
Awesome! I'll try to test this out. Will it also cover Javascript?

**Comment by pusolito** [comment]
@Raibaz, I just confirmed that a new project using Kotlin **1.3.72** works with 1.10.7-SNAPSHOT. I created a simple class in `common` and wrote a test in `commonTest`. Here's what it looks like:

**build.gradle.kts**

```kotlin
plugins {
    kotlin("multiplatform") version "1.3.72"
}

group   = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven       { url = uri("https://oss.sonatype.org/content/repositories/snapshots") }
}

kotlin {
    jvm {
        compilations.all {
            kotlinOptions {
                jvmTarget = "1.8"
            }
        }
    }

    js {
        compilations.all {
            kotlinOptions {
                moduleKind            = "umd"
                sourceMap             = true
                sourceMapEmbedSources = "always"
            }
        }
        browser {
            testTask {
                enabled = false
            }
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(kotlin("stdlib-common"))
            }
        }
        commonTest {
            dependencies {
                implementation(kotlin("test-common")                  )
                implementation(kotlin("test-annotations-common")      )
                implementation("io.mockk:mockk-common:1.10.7-SNAPSHOT")
            }
        }
        jvm().compilations["main"].defaultSourceSet {
            dependencies {
                implementation(kotlin("stdlib-jdk8"))
            }
        }
        jvm().compilations["test"].defaultSourceSet {
            dependencies {
                implementation("junit:junit:4.12")
                implementation(kotlin("test-junit"))
                implementation("io.mockk:mockk:1.10.7-SNAPSHOT")
            }
        }
        js().compilations["main"].defaultSourceSet {
            dependencies {
                implementation(kotlin("stdlib-js"))
            }
        }
        js().compilations["test"].defaultSourceSet {
            dependencies {
                implementation(kotlin("test-js"))
                implementation("io.mockk:mockk-js:1.7.17")
            }
        }
    }
}
```

**MyClass.kt**
```kotlin
interface Counter {
    fun next(): Int
}

class MyClass(private val counter: Counter) {
    fun doSomething(): Int {
        return counter.next()
    }
}
```

**MyClassTests.kt**

```kotlin
import io.mockk.every
import io.mockk.mockk
import kotlin.js.JsName
import kotlin.test.Test
import kotlin.test.expect

class MyClassTests {
    @Test @JsName("doesSomething")
    fun `does something`() {
        val counter = mockk<Counter>().apply {
            every { next() } returns 347
        }

        expect(counter.next()) { 347 }
        expect(counter.next()) { MyClass(counter).doSomething() }
    }
}
```

**Comment by Raibaz** [comment]
Awesome, thanks a lot for trying this out.

I have been doing some more extensive tests and looks like issues like #553 are not happening with 1.10.7-SNAPSHOT, so I will likely make a release over the next week.

**Comment by pusolito** [comment]
What's the plan for JS? Does this release cover it?

**Comment by Raibaz** [comment]
Nope, JS support has been disabled some releases ago and it basically needs to be reimplemented, because the gradle plugin it was using has now been deprecated :(

**Comment by pusolito** [comment]
@Raibaz, glad to see the release! Is there an issue tracking JS support?

**Comment by Raibaz** [comment]
Yep, #100 is about Kotlin/JS.
