### ISSUE TITLE
Bug: Unable to mock companion field

### ISSUE THREAD

**Issue by GregHib** [mockk/mockk#481]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Able mock variables within companion objects as well as functions

Relates to [#136](https://github.com/mockk/mockk/issues/136#issuecomment-419760399)

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: Windows 10 Home 19041.450
* Kotlin version: 1.3.72
* JDK version: 11
* JUnit version: jupiter 5.6.2
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

```gradle
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.2'
    testImplementation 'io.mockk:mockk:1.10.0'
}
```
```kotlin
class Util {

    fun getMessage(): String {
        return message
    }

    companion object {
        val message = "failure"
    }
}
```
```kotlin
package io.mockk.gh

import io.mockk.every
import io.mockk.mockkObject
import io.mockk.mockkStatic
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class UtilTest {
    @Test
    fun test() {
        val util = Util()
        mockkStatic(Util::class)
        mockkObject(Util)

        every { Util.message } returns "success"

        val result = util.getMessage()

        assertEquals("success", result)
    }
}
```

**Comment by afaucogney** [comment]
@GregHib You should use  mockkObject(Util.Companion). With you code, you target the class, not the object of the class (aka companion object)

**Comment by GregHib** [comment]
> mockkObject(Util.Companion)

Thanks for the input @afaucogney , as mentioned in [the related issue](https://github.com/mockk/mockk/issues/136#issuecomment-419879755) `mockkObject(Util)` is complied to `mockkObject(Util.Companion)` so it makes no difference, I've tried with one the other and both and the test always fails.

**Comment by GregHib** [comment]
Re-tested with JDK 14, Kotlin 1.4.10, Mockk 1.10.3 and JUnit 5.7.0.

**Comment by GregHib** [comment]
Re-tested with JDK 15.0.2, Kotlin 1.4.30, Mockk 1.10.5 and JUnit 5.7.1, can we get this re-opened @oleksiyp? Thanks in advance.

**Comment by winniegr** [comment]
I also met this issue in JDK 17, kotlin 1.9.0, Mokk 1.13.10, and JUnit 4.13.2. Could you reopen the issue?
