### ISSUE TITLE
MockKException: Class cast exception happened while mocking generic class

### ISSUE THREAD

**Issue by ganadist** [mockk/mockk#492]
### Expected Behavior

mock class

### Current Behavior

`every` block raise `io.mockk.MockKException: Class cast exception happened.`

#### Steps to Reproduce
Preparing
```
$ git clone https://github.com/ganadist/VersionCodeDemo test -b mockk_cast_exception_robolectric_4.4
$ cd test
```
On java 8, it has no problem
```
$ /usr/lib/jvm/java-8-openjdk/bin/java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

$ git checkout origin/mockk_cast_exception_robolectric_4.4~2

### pass with java8 + robolectric 4.3.1 + mockk 1.10.0
$ ./gradlew clean
$ env JAVA_HOME=/usr/lib/jvm/java-8-openjdk ./gradlew :app:testDevelopDebugUnitTest --no-build-cache

$ git checkout origin/mockk_cast_exception_robolectric_4.4~1

### pass with java8 + robolectric 4.4 + mockk 1.10.0
$ ./gradlew clean
$ env JAVA_HOME=/usr/lib/jvm/java-8-openjdk ./gradlew :app:testDevelopDebugUnitTest --no-build-cache

$ git checkout origin/mockk_cast_exception_robolectric_4.4

### pass with java8 + robolectric 4.4 + mockk 1.10.1-SNAPSHOT
$ ./gradlew clean
$ env JAVA_HOME=/usr/lib/jvm/java-8-openjdk ./gradlew :app:testDevelopDebugUnitTest --no-build-cache

```
On java 11 + Robolectric 4.4, mockk raise `io.mockk.MockKException: Class cast exception happened.`
```
$ /usr/lib/jvm/java-11-openjdk/bin/java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10)
OpenJDK 64-Bit Server VM (build 11.0.8+10, mixed mode)

$ git checkout origin/mockk_cast_exception_robolectric_4.4~2

### pass with java11 + robolectric 4.3.1 + mockk 1.10.0
$ ./gradlew clean
$ env JAVA_HOME=/usr/lib/jvm/java-11-openjdk ./gradlew :app:testDevelopDebugUnitTest --no-build-cache

$ git checkout origin/mockk_cast_exception_robolectric_4.4~1

### fail with java11 + robolectric 4.4 + mockk 1.10.0
$ ./gradlew clean
$ env JAVA_HOME=/usr/lib/jvm/java-11-openjdk ./gradlew :app:testDevelopDebugUnitTest --no-build-cache

$ git checkout origin/mockk_cast_exception_robolectric_4.4

### fail with java11 + robolectric 4.4 + mockk 1.10.1-SNAPSHOT
$ ./gradlew clean
$ env JAVA_HOME=/usr/lib/jvm/java-11-openjdk ./gradlew :app:testDevelopDebugUnitTest --no-build-cache

```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0, 1.10.1-SNAPSHOT (https://github.com/mockk/mockk/commit/10f17de9645f71245e8f3e11e25f9424ab911f0d)
* OS: Linux
* Kotlin version: 1.3.72
* JDK version: OpenJDK 11 (build 11.0.8+10)
* JUnit version: 4.12
* Type of test: unit test OR android instrumented test : Unittest with robolectric 4.4

It seems similar with #321, but this issue is not about chained call.

#### Failure Logs
https://scans.gradle.com/s/5e26rzx5n36zs/console-log#L38

#### Stack trace
https://scans.gradle.com/s/5e26rzx5n36zs/tests/:app:testDevelopDebugUnitTest/com.example.myapplication.UnitTest2/test1#1

#### Minimal reproducible code (the gist of this issue)
https://github.com/ganadist/VersionCodeDemo/blob/mockk_cast_exception_robolectric_4.4/app/src/test/java/com/example/myapplication/UnitTest2.kt#L28-L30

**Comment by alixwar** [comment]
This is still an issue and I argue that it's an important one since it affects all modern Android development projects

**Comment by oboenikui** [comment]
The bug is caused because the class loader of the test class (org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader) and that of JvmAutoHinter (jdk.internal.loader.ClassLoders$AppClassLoader) is different. I think this bug is not occured when JvmAutoHinter use the class loader of test class at `Class.forName`.

I made the PR about this bug, but my fix may be not a pretty code, so please make additional changes.

Other solution (workaround) is to use hint method like this

```kotlin
every {
    hint(SomeExtensionModule::class)
    SomeExtensionAccess.getExtensionModule()
} returns module
```

**Comment by alwa** [comment]
Still a problem. Please add the "important" label

**Comment by Raibaz** [comment]
There are already several issues open about the incompatibility between mockk and robolectric 4.4.

There is some discussion open in the [robolectric repo](https://github.com/robolectric/robolectric/issues/5994) on how to address this, no need to reopen this issue.

**Comment by alwa** [comment]
> There are already several issues open about the incompatibility between mockk and robolectric 4.4.
> 
> There is some discussion open in the [robolectric repo](https://github.com/robolectric/robolectric/issues/5994) on how to address this, no need to reopen this issue.

The discussion that you referred to is about problems using mockStatic() and not a general discussion about interoperability with Robolectric. But if you think this will be handled automatically in that issue, then I suppose we can keep this closed.

**Comment by SnexusG** [comment]
since the issue is not resolved yet, could someone tell me what might be the best workaround for this?

**Comment by xyzwilliamxyz** [comment]
I had this issue and using hint also solved it for me. In my case I had a method which received a generic type and using hint before it apparently made it possible for the JVM to properly identify it. For reference:

```
every {
    *hint(MyClass::class)*
    MyConverterClass.someMethod(MyClass::class.java)
} returns module
```

**Comment by asljuxt** [comment]
Issue is ongoing with v1.11.0

**Comment by alwa** [comment]
> I had this issue and using hint also solved it for me. In my case I had a method which received a generic type and using hint before it apparently made it possible for the JVM to properly identify it. For reference:
> 
> ```kotlin
> every {
>     hint(MyClass::class)
>     MyConverterClass.someMethod(MyClass::class.java)
> } returns module
> ```

Where do you get hold of "module"?

**Comment by xyzwilliamxyz** [comment]
@alwa yeah, it's actually mock. Edited the previous comment.

**Comment by mecoFarid** [comment]
@Raibaz Didn't get why this issue is closed, it still happens in mockk `1.12.3` even with the `hint`

**Comment by mecoFarid** [comment]
@Raibaz Why is this issue closed? It keeps crashing in mocck `1.12.0` even with the `hint` mentioned here [https://mockk.io/#chained-calls](https://mockk.io/#chained-calls)

**Comment by odfsoft** [comment]
I still can experience this issue, does someone here knows a possible solution?

**Comment by kylooh** [comment]
> I still can experience this issue, does someone here knows a possible solution?

I have same one, but this one is more wired. I passed my tests days ago, but tests failed at this time, even I did not change them. After some checks, I found **somehow I used IBM's JVM (which use OpenJ9 as VM)**. Hope it helps.

**Comment by rupert-jung-mw** [comment]
Same problem here on a verify call

```
io.mockk.MockKException: Class cast exception happened.
Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method.
```

**Comment by himanshusprinto** [comment]
Any update? i am using JAVA 17
