### ISSUE TITLE
MockKException: No other calls allowed in stdObjectAnswer than equals/hashCode/toString on trying to static mock Android TextUtils.isEmpty()

### ISSUE THREAD

**Issue by vitaliyistomov** [mockk/mockk#494]
### Expected Behavior

I am trying to mock an interface method, which returns `GoogleSignInOptions`, where Android `TextUtils` are used internally.

### Current Behavior

Statick mocking `TextUtils` causes MockK exception.

#### Context

* MockK version: 1.10.0
* OS: MacOS 10.15.6
* Kotlin version: 1.4.10
* JDK version: openjdk version "1.8.0_265
* JUnit version: 5.6.2
* Type of test: Unit test

#### Stack trace

```
Caused by: io.mockk.MockKException: No other calls allowed in stdObjectAnswer than equals/hashCode/toString
	at io.mockk.impl.stub.MockKStub.stdObjectAnswer(MockKStub.kt:78)
	at io.mockk.impl.recording.states.SafeLoggingState.call(SafeLoggingState.kt:9)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at android.text.TextUtils.isEmpty(TextUtils.java)
	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@17.1.1:7)
	at com.google.android.gms.common.api.Scope.<init>(com.google.android.gms:play-services-basement@@17.1.1:2)
	at com.google.android.gms.common.api.Scope.<init>(com.google.android.gms:play-services-basement@@17.1.1:6)
	at com.google.android.gms.auth.api.signin.GoogleSignInOptions.<clinit>(com.google.android.gms:play-services-base@@17.1.0:151)
	... 97 more
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------

classpath 'com.google.gms:google-services:4.3.3'

dependencies {
       testImplementation "io.mockk:mockk:1.10.0"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------

interface AuthService {
    fun getGoogleSignInOptions(): GoogleSignInOptions
}

class SomeViewModel(
    private val authService: AuthService
) : ViewModel() {

    fun getGoogleSignInOptions(): GoogleSignInOptions = authService.getGoogleSignInOptions()
}


class MockingTextUtilsInGoogleSignInOptionsTest {

    private val authService = mockk<AuthService>().apply {
        every { getGoogleSignInOptions() } returns mockk()
    }
    private val vm = SomeViewModel(authService)

    @Test
    fun getGoogleSignInOptions() {
        mockkStatic(TextUtils::class)
        every { TextUtils.isEmpty(any()) } returns false

        vm.getGoogleSignInOptions()
        verify(atMost = 1) { authService.getGoogleSignInOptions() }
    }
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by qustom-dev** [comment]
This is still occurring.

**Comment by elue** [comment]
any update on this one?

**Comment by anticafe** [comment]
I still see this issue in mockk v1.13.2.

**Comment by omesquita** [comment]
> I still see this issue in mockk v1.13.2.

Me too. Does someone find a solution?

**Comment by omesquita** [comment]
It's a not stale problem. 
Someone found a solution to this?

**Comment by p-bril** [comment]
I have same issue(((

**Comment by vladut-dascalescu-rs** [comment]
+1, this issue had the first occurrence on my project starting with version 1.13.3 ...

**Comment by tonisives** [comment]
My issue was that one of my dependency had
`implementation "org.slf4j:slf4j-simple:1.7.32"`
The Mockk error doesn't direct me towards this problem in any way. However, the dependency shouldn't include slf4j implementation in the first place

**Comment by omesquita** [comment]
> My issue was that one of my dependency had `implementation "org.slf4j:slf4j-simple:1.7.32"` The Mockk error doesn't direct me towards this problem in any way. However, the dependency shouldn't include slf4j implementation in the first place

@tonisives , do you fixed it in your project?

**Comment by mateusz-rutski-red** [comment]
I did some debugging and it looks like `state` field of `CommonCallRecorder` transitions to `SafeLoggingState` (initiated by `SafeLogger`) but doesn't return back to the initial `StubbingState` before mocked block `TextUtils.isEmpty(any())` is called. 

Not sure what's the cause of the invalid CallRecorder state and I don't see a workaround.

Maybe wrapping the mocked class with your own wrapper class and mocking that instead could work?
```
class TextUtilsWrapper {
  fun isEmpty(text: string) = TextUtils.isEmpty(text))
}

...

mockkStatic(TextUtilsWrapper::class)
every { TextUtilsWrapper.isEmpty(any()) } returns false

```

**Comment by sergio-jt** [comment]
It's happening with,
`testImplementation("io.mockk:mockk:1.13.12")`
`mockkStatic(LocalDateTime::class, Instant::class)`
