### ISSUE TITLE
Throw error when trying to mock final methods

### ISSUE THREAD

**Issue by idoflax** [mockk/mockk#495]
### Expected Behavior

When mocking a final method, should throw an error indicating that it is not allowed

### Current Behavior

When mocking a final method, the actual method is being called, with no indication as to why

#### Steps to Reproduce

create a component
create a final method within the component
create a test with a mock of the component
mock the method ising `every{}`
#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.0
* OS: macOS Mojave 10.14.6
* Kotlin version: 1.3.11
* JDK version: 8
* JUnit version: 5
* Type of test: unit test

**Comment by TopHatCroat** [comment]
I've tried replicating this issue, but the following test ran well, mocking the final method as well:
```
class Issue495Test {
    class MockCls {
        final fun op() = 1
    }

    val mock = mockk<MockCls>()

    @Test
    fun shouldThrowWhenMockingFinal() {
        every { mock.op() } answers { 10 }
        assertEquals(10, mock.op())
    }
}
```
@Raibaz  I'm I testing this wrong?

**Comment by Raibaz** [comment]
@TopHatCroat you're right, seems like this is behaving correctly. Closing the issue for now.
