### ISSUE TITLE
io.mockk.MockKException: Failed to build static proxy

### ISSUE THREAD

**Issue by ZhangHeYue** [mockk/mockk#496]
#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.9.2
* OS: macOS 10.15.6 
* Kotlin version: 1.3.31
* JDK version: 1.8
* JUnit version: 4.12
* Type of test:  android instrumented test

#### Stack trace`

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io.mockk.MockKException: Failed to build static proxy
at io.mockk.impl.instantiation.JvmStaticMockFactory.staticMockk(JvmStaticMockFactory.kt:41)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    androidTestImplementation ('io.mockk:mockk-android:1.9.3') {exclude module: 'objenesis'}
    androidTestImplementation 'org.objenesis:objenesis:2.6'
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
class AAA {

}

class Test {

    companion object {
        @BeforeClass
        @JvmStatic
        internal fun before() {
            val aaa = mockk<AAA>()
            mockkStatic(AAA::class) {
                every { AAA.getInstance() } returns aaa
            }

        }
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by knyttl** [comment]
I would believe, this might be related to https://github.com/mockk/mockk/issues/534 as both concern `mockStatic` and `returns`

**Comment by Raibaz** [comment]
What exactly are you trying to test here? Your class `AAA` does not have a `getInstance` function so it's hard for me to understand what your expected behavior would be.
