### ISSUE TITLE
Unresolved reference io.mockk.every, mockk, verify

### ISSUE THREAD

**Issue by jmfayard** [mockk/mockk#498]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I should be able to import `io.mockk.{verify,every,verify}`
 
### Current Behavior

I have the compiler throwing me errors

#### Steps to Reproduce

1. Open this commit https://github.com/LouisCAD/kotlin-libraries-playground/commit/04eeead8c769d4e3fd8c79f55efa14e3b359911a?branch=04eeead8c769d4e3fd8c79f55efa14e3b359911a&diff=split
2. `cd kotlin-jvm ; ./gradlew compileTestKotlin`
3. you get it...

If you open `kotlin-jvm/src/test/kotlin/framework/mockk/PresenterTest.kt` you can see that IntelliJ finds the imports, but the compiler throws errors

```
./gradlew compileTestKotlin
:compileTestKotlin FAILED
e: PresenterTest.kt: (55, 9): Unresolved reference: every |  
e: mockk/PresenterTest.kt: (61, 9): Unresolved reference: verify |  
public inline fun CharArray.any(predicate: (Char) -> Boolean): Boolean defined in kotlin.collections
public fun CharSequence.any(): Boolean defined in kotlin.text
public inline fun CharSequence.any(predicate: (Char) -> Boolean): Boolean defined in kotlin.text
// many more
Execution failed for task ':compileTestKotlin'.
```

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.2
* OS: 10.15.6
* Kotlin version: 1.4.10
* JDK version: 1.8
* JUnit version: 5.7.0
* Type of test: unit test 

#### Failure Logs

https://scans.gradle.com/s/iyf33spew6as2/console-log#L10

**Comment by jmfayard** [comment]
Never mind, it was only on my machine that it didn't work

**Comment by victorpaleologue** [comment]
> Never mind, it was only on my machine that it didn't work

How did you fix it on your machine? I tried invalidating the caches and clearing the build, in vain.
