### ISSUE TITLE
Observation: Latest release

### ISSUE THREAD

**Issue by andreschaffer** [mockk/mockk#505]
Hi,
This is more of an observation: the official site https://mockk.io/ announces the newest release 1.10.2, although here on GitHub it shows 1.10.0 as the latest release. This was somewhat confusing. Maybe something to align?
Thanks for the cool project, btw.
Cheers

**Comment by jbebar** [comment]
Looks liked it's solved 
![image](https://user-images.githubusercontent.com/36046678/95907389-be603480-0d9b-11eb-8491-4a82e652464b.png)

**Comment by andreschaffer** [comment]
The newer tags do exist, but 1.10.0 still shows as the latest release: https://github.com/mockk/mockk/releases
