### ISSUE TITLE
Capture receiver

### ISSUE THREAD

**Issue by johnhenaot** [mockk/mockk#512]
> Just be aware about usual MockK support pattern. 
> Tickets are checked from time to time, replied, discussed, labeled, e.t.c.
> But real fixes are applied in a month-two month period in a bunch.
> If you think this is unacceptable, go on, join the project, change the world.

## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Expected Behavior

For a function:
```
fun DefinedType.function() =
    implementation
```

want to be able to:

every { capture(her).function } do something

### Current Behavior

What is the current behavior?

Error

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Define a slot to store a receiver
2. Mock the file containing the function
3. define a val as slot<theReceiverType>
4. Mock behavior with every { capture(your_val).yourFunction() } just Runs //or any behavior

**Comment by Raibaz** [comment]
Not sure exactly what you are trying to achieve here. Can you please provide a full snippet of code with your expected behavior?

**Comment by johnhenaot** [comment]
Sure,

```
...
val theSlot = slot<String>()

every { capture(theSlot).split(",") } returns defaultValue

"do something" {
     theSlot.captured shouldBe expectedValue
}
```

Of course this is not the actual context, but I cannot capture the receiver. The context is, I have a function that creates a spark dataset, perform some transformations, and then writes this dataset somewhere. I want to be able to validate different behaviors in the transformation by capturing the FINAL dataset just before writing it, but keep running so I can perform validations in the writing.

More context, we solved the problem by creating a new function, for example in the above case:
```
fun Split(theString String, sep String) =
      theString.split(sep)
```

Now it is possible via:
```
...
val theSlot = slot<String>()

every { split(capture(theSlot), ",") } returns defaultValue <------ new function

"do something" {
     theSlot.captured shouldBe expectedValue
}
```

**Comment by Raibaz** [comment]
Ok i see what you mean now.

Thing is, slots are not meant to be used in `every` blocks, but in `verify` blocks.

Your test then should be something like this:

```
every { split(any(), ",") } returns defaultValue

// some code that calls split

val theSlot = slot<String>()
verify {
    split(capture(theSlot), ",")
}

// perform assertions on slot.captured
```

Does this make sense to you?

**Comment by cpele** [comment]
As per [the documentation](https://mockk.io/#:~:text=every%20%7B%0A%20%20%20%20car.recordTelemetry(%0A%20%20%20%20%20%20%20%20speed%20%3D%20capture,captured%7D%2C%20roadType%3A%20%24%7BroadTypeSlot.captured%7D%22)%0A%0A%20%20%20%20RecordingOutcome.RECORDED%0A%7D), I believe it is now possible to use `capture` in `every` block:
```kotlin
every {
    car.recordTelemetry(
        speed = capture(speedSlot),
        direction = Direction.NORTH
        roadType = captureNullable(roadTypeSlot),
    )
} answers {
    // ...
}
```
But @Raibaz I think @johnhenaot was instead asking how to capture e.g. `str` in the following `split` extension-function call:
```kotlin
str.split(",")
```
(That's what I'm trying to do too)

**Comment by cpele** [comment]
... And according to my tests the following approach now works:

> ```
> val theSlot = slot<String>()
> 
> every { capture(theSlot).split(",") } returns defaultValue
> 
> "do something" {
>      theSlot.captured shouldBe expectedValue
> }
> ```

No need to create a top-level function.
