### ISSUE TITLE
Code inspection and syntax highlighting is not working for Kotlin Multiplatform code on Android Studio 4.1

### ISSUE THREAD

**Issue by canuludag** [mockk/mockk#513]
### Prerequisites
Please answer the following questions for yourself before submitting an issue.
- [√] I am running the latest version
- [√] I checked the documentation and found no answer
- [√] I checked to make sure that this issue has not already been filed

### Current Behavior
We have code that created for Kotlin Multiplatform on Android project. And we are using Mockk version 1.10.+ for our Kotlin Multiplatform unit tests. 

### Failure Information (for bugs)
After updating to Android Studio 4.1, code inspection and syntax highlighting or navigating between code stopped. We are not able to use our tests. Debugger is not working. But that happens only for Kotlin Multiplatform code. Since regular Android modules are not using Mockk, Android Studio inspecting code without issue.
On the other hand, if we downgrade our Mockk version to 1.9.2, it works perfectly. Code inspection and syntax highlighting starts working again.

#### Steps to Reproduce
1. Update to Android Studio 4.1
2. Create Kotlin Multiplatform project.
3. Create new module that contains Kotlin shared code.
4. Add dependency of Mockk 1.10.+ version for unit test (We both tried 1.10.1 and 1.10.2)
5. Sync gradle.
6. Check your Kotlin code, it won't syntax highlighting and code inspections stops.

#### Context
* MockK version: 1.10.+
* OS: MacOS Catalina
* Kotlin version: 1.4.10
* JDK version: 8
* JUnit version: 
* Type of test: unit test for Kotlin Multiplatform
* Dependencies we use:
```
commonTest {
            dependencies {
                implementation kotlin('test-common')
                implementation kotlin('test-annotations-common')
                implementation kotlin('test-junit')
                implementation 'io.mockk:mockk:1.10.0' 
            }
        }
```

#### Failure Logs

Screenshot: 
<img width="368" alt="Screen Shot 2020-10-19 at 16 08 43" src="https://user-images.githubusercontent.com/1974656/96558131-ec75d500-12c3-11eb-9729-1ae78c454822.png">

#### Stack trace
```
Unable to build Kotlin project configuration</b><eol>Details: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find mockk-1.10.0-samplessources.jar (io.mockk:mockk:1.10.0).<eol>Searched in the following locations:<eol>    https://jcenter.bintray.com/io/mockk/mockk/1.10.0/mockk-1.10.0-samplessources.jar</i>
```

**Comment by jovikao-hy** [comment]
I have the same issue.
This will cause the Android studio becomes not able to identify mpp project correctly.
Without mockk dependency.
<img width="460" alt="螢幕截圖 2020-12-18 下午3 20 32" src="https://user-images.githubusercontent.com/56578647/102586268-c85c3600-4144-11eb-8979-e48c9391ecda.png">
With mockk dependency.
<img width="457" alt="螢幕截圖 2020-12-18 下午3 20 49" src="https://user-images.githubusercontent.com/56578647/102586289-d27e3480-4144-11eb-95fb-e410e2e426b4.png">

**Comment by TomWayne98** [comment]
This happens to me in my app project too with multiple libraries... Did you guys find some solution?

**Comment by evertsmits** [comment]
I have the same issue, for me this results in not being able to perform unit tests. Also this is in a Kotlin multiplatform project. Also it is very strange that the maven repo does not even contain a samplessources.jar. So why does the dependency even bother looking for that jar?
https://repo1.maven.org/maven2/io/mockk/mockk/1.10.6/

**Comment by ovitrif** [comment]
I have the same issue on mockk 1.10.6..

**Comment by rocketraman** [comment]
Same here also -- it prevents the source folders in the shared module from being marked as sources, which is a big problem. For me the problem goes away when I remove the `implementation("io.mockk:mockk:1.10.6")` dependency from `commonTest` (leaving only `implementation("io.mockk:mockk-common:1.10.6")`), however doing that means we run into https://github.com/mockk/mockk/issues/322 instead. Argh.

**Comment by rocketraman** [comment]
FYI, I created https://youtrack.jetbrains.com/issue/KT-46153.
