### ISSUE TITLE
Bug: Mocking varargs

### ISSUE THREAD

**Issue by UlfHesselbarth** [mockk/mockk#52]
In Mockito there is `anyVararg()` but mockk does not have this.
Consider the following example:
```
interface Foo {
   fun foo(vararg args: String, otherArg: String)
   fun foo(args: List<String>, otherArg: String)
}

@Test
fun varargTest() {
   val mock = mockk<Foo>()
   // this works as expected, matching the List<String> version
   every { mock.foo(args = any<List<String>>(), otherArg = any()) } just Runs

   // this does not work, compiles but fails at runtime with:
   // io.mockk.MockKException: Failed matching mocking signature for
   // Foo(#1).foo([529c407ddf5619f7], -4522a650db14c274)
   // left matchers: [any()]
   every { mock.foo(args = *arrayOf(any()), otherArg = any()) } just Runs
}
```

Is there another way to mock the vararg version of `foo`?

**Comment by oleksiyp** [comment]
Look like issue is appearing when using `interface` or `abstract class`. When using simple class it is passing:
```
    class Foo {
        fun foo(vararg args: String, otherArg: String) {

        }
        fun foo(args: List<String>, otherArg: String) {
            
        }
    }
```
I've checked underlying reflection call and seems Kotlin is just not returning correct value. So it is a Kotlin reflection API bug

**Comment by oleksiyp** [comment]
After additional checking, it appears that pure interface is working. So it is related to metadata propagation i.e. while using interface MockK needs to create a proxy subclass and Kotlin metadata is not copied to that subclass.

**Comment by gildor** [comment]
@oleksiyp I cannot verify vararg, method with vararg always faile verification

**Comment by oleksiyp** [comment]
Very probable that this is related. 
Fix/workaround is making MockK slow, so it was not merged. 
Some caching to be applied. 
Or maybe other ways to fix it.

Right now(one/two weeks) I'm quite free for doing MockK improvements/fixes but focused on Android instrumentation test which is a big feature. Will get back to such not very big things after releasing it.

**Comment by oleksiyp** [comment]
Seems it was fixed, reopen if it is not

**Comment by darrenhaken** [comment]
@oleksiyp new issue opened at https://github.com/mockk/mockk/issues/224
