### ISSUE TITLE
Mock top level functions

### ISSUE THREAD

**Issue by carloschameleon** [mockk/mockk#524]
I started to work with top level functions in Kotlin in my first approach to functional programming and found a way to mock functions that is, I think, effective but wasn't that obvious at first sight.

```kotlin
// This is inside my test file
import top.level.functions.fooFun

mockkStatic(fooFun.javaMethod!!.declaringClass.kotlin)
```

So I was thinking it would be nice to have a function that make it easier to mockk that top level function so you don't have to implement a solution yourself

```kotlin
// This could be a function inside io.mockk.MockK.kt
fun mockkFunction(kfun: KFunction<*>) = mockkStatic(kfun.javaMethod!!.declaringClass.kotlin)
```

The good thing about this approach is that is not a String like when you mockk a file (mockkStatic("my.package.MyFileKt") ) but you pass the name of the method so if you refactor or you change the name of the method tests and compiler will be aware.

If we add that function to MockK.kt the use of this inside a test will be something like this:
```kotlin
import top.level.functions.fooFun
import io.kotest.core.spec.style.FunSpec
import io.mockk.every

class DummyTest : FunSpec({
    mockkFunction(::fooFun)
   
   test("get suggested labels") {
        every { fooFun("foo") } returns "bar"

        // Do your test here
    }
}
```

**Comment by Endhuine** [comment]
There is already a 
```kotlin
fun mockkStatic(vararg functions: KFunction<*>)
```
which you can already use to mock a top-level function in kotlin targeting the jvm

**Comment by Raibaz** [comment]
Yep you're right, I think this can be closed.
