### ISSUE TITLE
mockkStatic strange behaviour

### ISSUE THREAD

**Issue by knyttl** [mockk/mockk#534]
Consider following minimum example:

```kotlin
import io.mockk.every
import io.mockk.mockkStatic
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.time.Instant
import java.time.ZonedDateTime

data class Response(val timestamp: Instant = Instant.now())

class Repository {
    fun getResponse() = Response()
}

class MockNowTest {
    private val repository = Repository()

    @BeforeEach
    fun beforeEach() {
        val zonedDateTime = ZonedDateTime.parse("2020-01-01T00:00:00Z")
        mockkStatic(Instant::class)
        every { Instant.now() }.returns(zonedDateTime.toInstant())
    }

    @Test
    fun testPassing1() {
        println(Response())
    }

    @Test
    fun testPassing2() {
        println(Instant.now())
    }

    @Test
    fun testFailing1() {
        every { repository.getResponse() } returns Response()
    }

    @Test
    fun testFailing2() {
        clearAllMocks()
        every { repository.getResponse() } returns Response()
    }
}
```

### Expected Behavior

I expect all the `@Test` functions to run correctly.

### Current Behavior

Only the two `testPassingX` run correctly and print mocked timestamp value.

The `testFailing1` fails with:

```
no answer provided for class java.time.Instant.now())
io.mockk.MockKException: no answer provided for class java.time.Instant.now())
	at io.mockk.impl.stub.AnswerAnsweringOpportunity.getAnswer(AnswerAnsweringOpportunity.kt:12)
	at io.mockk.impl.stub.AnswerAnsweringOpportunity.answer(AnswerAnsweringOpportunity.kt:14)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:54)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at java.base/java.time.Instant.now(Instant.java:273)
	at hero.user.service.Response.<init>(MockNowTest.kt:10)
	at hero.user.service.MockNowTest.testMockNow1(MockNowTest.kt:28)
```

Then, the `testFailing2` - I tried to overcome the `mockNow` issue with `clearAllMocks`, but it seems it has no effect and the test fails as well.

You can see that one call to `Instant.now()` passes correctly, the second does not. What is the difference between response of `every`?

#### Steps to Reproduce

Get the code above and run it.

#### Context

* MockK version: 1.10.2
* OS: OSX Big Sur
* Kotlin version: 1.4.20
* JDK version: 11
* JUnit version: 2
* Type of test: unit test

**Comment by Raibaz** [comment]
The reason why your `repository` is not behaving as you describe in your `every { }` blocks is that it's not a mock.

By changing the declaration to  `private val repository = mockk<Repository>()`, all tests pass correctly.

**Comment by knyttl** [comment]
Okay, but in other cases this works correctly so it was hard to understand the cause. Wouldn't it be better to throw something like `Cannot use 'every' with not mocked block.`

**Comment by Raibaz** [comment]
You're right, I submitted #538 to keep track of this.

**Comment by knyttl** [comment]
Thanks.
