### ISSUE TITLE
Throw an exception when a non-stubbed class is used in an every {} block

### ISSUE THREAD

**Issue by Raibaz** [mockk/mockk#538]
It is possible to put inside an `every` block calls to an object that hasn't been stubbed:

```
val foo = SomeClass() // should be mockk<SomeClass>()

every {
    foo.bar()
} returns "baz"
```

It won't work, because `foo` is not a mockk, but it doesn't return a meaningful error message explaining why and how to fix it.

Ideally, an exception should be thrown with a meaningful error message.

**Comment by senioroman4uk** [comment]
I will take a look at this one on weekend
