### ISSUE TITLE
Version 1.10.3 is not compatible with Java 8 runtime

### ISSUE THREAD

**Issue by kilink** [mockk/mockk#539]
Trying to run a test with mockK 1.10.3 results in the following exception being thrown:

```
io/mockk/proxy/jvm/dispatcher/JvmMockKDispatcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
java.lang.UnsupportedClassVersionError: io/mockk/proxy/jvm/dispatcher/JvmMockKDispatcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1008)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:407)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at io.mockk.proxy.jvm.dispatcher.BootJarLoader.loadBootJar(BootJarLoader.kt:32)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.initInstrumentation(JvmMockKAgentFactory.kt:146)
	at io.mockk.proxy.jvm.JvmMockKAgentFactory.init(JvmMockKAgentFactory.kt:34)
	at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
	at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:172)
```

Downloading the mockk-agent-jvm-1.10.3.jar artifact from bintray, and running the following command confirms that JvmMockKDispatcher is using the Java 11 class file format (version 55):

```
javap -verbose JvmMockKDispatcher.class | grep version
  minor version: 0
  major version: 55
```

**Comment by oleksiyp** [comment]
@kilink thanks for the report.
Believe the same stuff happened to me when I was releasing 1.10.1 and built it using 11 compiler. 
Although in IDE all settings were set to use 1.8 Gradle somehow found 11.
I needed to do it from the command line a second time (to releaese 1.10.2)

**Comment by Raibaz** [comment]
Thanks for spotting this, going to run some tests and then release a Java 8 compatible version soon.

**Comment by OmarBeshary** [comment]
I'm using mockk with kotlin_version **1.4.20** and faced the same exception with version **1.10.3**. used **1.9.3** and it's working fine.

**Comment by ashutoshgngwr** [comment]
@OmarBeshary Use [**1.10.3-jdk8**](https://github.com/mockk/mockk/releases/tag/1.10.3-jdk8) instead of **1.10.3**.

**Comment by OmarBeshary** [comment]
@ashutoshgngwr i updated to **1.10.3-jdk8** and had the same issue so i had to rollback to **1.9.3**

**Comment by ashutoshgngwr** [comment]
@OmarBeshary It's hard to guess what might be the problem. I had the same issue and it was fixed in the said release. Here's my [build.gradle](https://github.com/ashutoshgngwr/noice/blob/master/app/build.gradle).
