### ISSUE TITLE
Mocking unsigned Kotlin types ends in `java.lang.ClassCastException`

### ISSUE THREAD

**Issue by bio007** [mockk/mockk#544]
I'm mocking simple function returning `UInt` but after that method is executed in the test it crashes with `java.lang.ClassCastException`.
```
every { calculator.compute(any()) } returns 23859762u
```

### Expected Behavior

No crash, mocked function returns unsigned number result.

### Current Behavior

Exception `java.lang.ClassCastException: kotlin.UInt cannot be cast to java.lang.Integer` is thrown in case of UInt return type.

#### Steps to Reproduce

1. Write mockk `every` function for a method returning unsigned number like UInt 
2. Call this function in the test
3. Exception is thrown

#### Context

* MockK version: 1.10.0
* OS: macOS Catalina
* Kotlin version: 1.3.72
* JUnit version: 4.12
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

```kotlin
    every { calculator.compute(any()) } returns 23859762u
    assertEquals(23859762u, calculator.compute(42))
```

**Comment by d35h** [comment]
Looks like something not related to mockk itself as mockk calls byte-buddy under the hood and then byte-buddy delegates getting declaration of methods to Class from jdk: ByteBuddy::MethodList::type::getDeclaredMethods, which returns int instead of UInt. I'd say that Kotlin's UInt is not interpolated correctly by this method making UInt as Int

**Comment by ianbrandt** [comment]
I ran into what may be the same issue trying to verify behavior on a mock with a method that takes a `UShortArray` as an input parameter.

```
interface MyInterface {
    suspend fun myMethod(arg1: UShortArray, arg2: Int, arg3: Int)
}
```

```
runBlockingTest {

    val mockMyInterface = mockk<MyInterface>()
    ...
    coVerify {
        mockMyInterface.myMethod(any(), any(), any())
    }
}
```

The error refers to trying to match a signature with `ShortArray` instead of `UShortArray`:
```
Failed matching mocking signature for
SignedCall(retValue=, isRetValueMock=true, retType=class kotlin.Any, self=MyInterface(#1), method=myMethod-GWzLcNs(ShortArray, Int, Int, Continuation), args=[null, 866937822, -1738456294, Continuation at my.package.MyTest$test my method$1$1.invokeSuspend(MyTest.kt:10)], invocationStr=MyInterface(#1).myMethod-GWzLcNs(null, 866937822, -1738456294, continuation {}))
left matchers: [any()]
```

**Comment by Raibaz** [comment]
Unsigned integer support in Kotlin is [still in beta](https://kotlinlang.org/docs/basic-types.html#beta-status-of-unsigned-integers), so I guess @d35h is right.

**Comment by Kantis** [comment]
I guess #633 might resolve this, since unsigned types are implemented using value classes

**Comment by nosideeffects** [comment]
Does not look like #633 solved this issue. Any idea the scope of work to get this to work?

**Comment by vonnagy** [comment]
I also see the same issue where mocking a class and method with unsigned values, ignore the _every_ setup and returns a safe default. Here is an example:

```
class MyClass  {

    fun doSomethingULong(customerId: ULong) :  String? {
        // Dummy functionality 
       return if (customerId > 0) {
           "e-1234"
       } else {
           null
       }
    }

    fun doSomethingLong(customerId: Long) :  String? {
        // Dummy functionality 
       return if (customerId > 0) {
           "e-1234"
       } else {
           null
       }
    }
}

val mockedService = mockk<MyClass>(relaxed = true) {
    every { doSomethingULong(any()) } returns null
    every { doSomethingLong(any()) } returns null
}

```

- When calling _ mockedService. doSomethingLong(999)_ the correct null is returned.
- When calling _ mockedService. doSomethingULong((999).toULong())_ the real method is called.

**Comment by migueltorcha** [comment]
Same issue here trying to mock a `UByte`:
`
interface MyInterface {
  suspend fun myMethod(): UByte?
}

....

coEvery { myInterface.myMethod() } returns Random.nextInt().toUByte()
`

As result, I have the next:
`class java.lang.Byte cannot be cast to class kotlin.UByte (java.lang.Byte is in module java.base of loader 'bootstrap'; kotlin.UByte is in unnamed module of loader 'app')
java.lang.ClassCastException: class java.lang.Byte cannot be cast to class kotlin.UByte (java.lang.Byte is in module java.base of loader 'bootstrap'; kotlin.UByte is in unnamed module of loader 'app')`

**Comment by cdprete** [comment]
I do have the same issue even with version `1.12.5` on a `@RelaxedMockK` with a `UInt` **nullable** field.

**Comment by cdprete** [comment]
I can confirm the same issue is present even with version `1.13.3` and Kotlin `1.8`

**Comment by zTrap** [comment]
Problem still here. mockk `1.13.8`, koltin `1.9.10`

**Comment by brian-livefront** [comment]
This issue still seems to be present on `1.13.10`. See https://github.com/mockk/mockk/issues/1226
