### ISSUE TITLE
Generic Map Usage in Chained Calls

### ISSUE THREAD

**Issue by piacenti** [mockk/mockk#545]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Chained calls should work if a generic map is part of the chain

### Current Behavior

Non specific maps such as Map<String,String> (interface), as opposed to HashMap<String,String>,  cannot be used in a chained call even when type hinting is provided. They work correctly for hierarchical mocks.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. attempt to use an object of interface type Map<T,R> as part of an `every` chain where the chain doesn't end with the map object
#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.3-jdk8
* OS: MacOS
* Kotlin version: 1.4.20
* JDK version: 11.0.5
* JUnit version: 5.6.2
* Type of test: unit test 

#### Stack trace

```

Failed matching mocking signature for
io.mockk.MockKException: Failed matching mocking signature for
SignedCall(retValue={}, isRetValueMock=false, retType=class kotlin.collections.Map, self=A(#4), method=getMap(), args=[], invocationStr=A(#4).getMap())
left matchers: [any()]
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:59)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)

```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "io.mockk:mockk:1.10.3-jdk8"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.mockk.every
import io.mockk.mockk
import kotlin.test.Test

class A(val map: Map<String, String>)
class MapInChainedMockTest {

    @Test
    fun test() {
        mockk<A> { every { map.hint(mapOf<String,String>()::class)[any()] } returns "test" }
      //mockk<A> { every { map[any()] } returns "test" } also fails
    }

}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by Raibaz** [comment]
Ok i can reproduce this, thanks for submitting it.

In the meantime, as a workaround, you can achieve the behavior you would like by doing:

```
class A(val map: Map<String, String>)

val a = mockk<A>()
val mockMap = mockk<Map<String, String>>()
every { mockMap[any()] } returns "test"
every { a.map } returns mockMap
```

**Comment by piacenti** [comment]
Still an issue although there is a workaround
