### ISSUE TITLE
lateinit property has not been initialized

### ISSUE THREAD

**Issue by zarglayoun** [mockk/mockk#546]
Hello,

I have the following class 

```kotlin 
@Path("/canceling")
class CancelResource {

  @Inject
  lateinit var cancelManager: CancelManager

  @POST
  @Path("{id}")
  fun cancelItem(@PathParam("id") id: String){
    cancelManager.addItem(id)
  }
}
```
A `CancelManager` which is an `@ApplicationScoped` class 

```kotlin
@ApplicationScoped
class CancelManager {
  var ids = setOf<String>()

  fun addItem(id: String) {
    ids = ids.plus(id)
  }
}
```

To test the `CancelResource` I need to mock the `CancelManager`. I did the following:

### Test :
```kotlin
internal class CancelResourceTest {
  @MockK
  lateinit var cancelManager: CancelManager

  @InjectMockKs
  lateinit var service: CancelResource

  @BeforeEach
  fun init() {
    MockKAnnotations.init(this)
    service = CancelResource()
  }

  @Test
  fun runTest() {
    val id = "dummy item"
    justRun { cancelManager.addItem(id) }

    service.cancelItem(id)

    verify { cancelManager.addItem(id) }
  }
}
```
**Expected behavior:** 
Correcly mocking the injection 

**Current behavior** 
It gives the following error 
`kotlin.UninitializedPropertyAccessException: lateinit property cancelManager has not been initialized`

## What's wrong?

----
MockK version: 1.10.0
Kotlin version: 1.3.72
JUnit5: junit-jupiter: 5.7.0 and junit-platform: 1.7.0

**Comment by zarglayoun** [comment]
The following has also been tested: 
```kotlin
  @InjectMockKs
  var canceledProblemsHandler: CanceledProblemsHandler = CanceledProblemsHandler()
``` 
which gives `io.mockk.MockKException: Missing calls inside every { ... } block`.

**Comment by Raibaz** [comment]
I think your `CancelManager` should be annotated with `@MockK`, as it's the class you're mocking, and `service` should be annotated with `@InjectMocks`, as it's the class you're injecting mocks into.

And yes, you need to call `MockKAnnotations.init(this)` in your init function for the annotations to be initialized.

Hope this helps

**Comment by zarglayoun** [comment]
> I think your `CancelManager` should be annotated with `@MockK`, as it's the class you're mocking, and `service` should be annotated with `@InjectMocks`, as it's the class you're injecting mocks into.
> 
> And yes, you need to call `MockKAnnotations.init(this)` in your init function for the annotations to be initialized.
> 
> Hope this helps

@Raibaz I tested your suggestion, stills throwing the exception `kotlin.UninitializedPropertyAccessException: lateinit property cancelManager has not been initialized
`

**Comment by zarglayoun** [comment]
Is there a solution? I really don't want to change the library :/

**Comment by Daniel-Jacob** [comment]
What about the init method? Don't you need to pass the cancelmanager as a dependency to the cancelResource?

**Comment by d35h** [comment]
I think that your problem is due to the fact that you're trying to initialize ```CancelResource``` yourself, which should be the responsibility of the code you call in ```@BeforeEach``` block that is ```MockKAnnotations.init(this)```

Delegate the initiation of mocks to the MockK framework, this code should work:
```
  @MockK
  lateinit var cancelManager: CancelManager

  @InjectMockKs
  lateinit var service: CancelResource

 @BeforeEach
  fun init() {
    MockKAnnotations.init(this)
  }

  @Test
  fun runTest() {
    val id = "dummy item"
    justRun { cancelManager.addItem(id) }

    service.cancelItem(id)

    verify { cancelManager.addItem(id) }
  }
```

Also, I would highly recommend you to go over the best practices for unit testing in Kotlin, in your case specifically the ```Create Mocks Once``` chapter, which suggests to get rid of vars and recreation of mocks for each tests and clear all mocks before a test instead: https://phauer.com/2018/best-practices-unit-testing-kotlin/#create-mocks-once

This being said, I would suggest to make a refactoring of your code (I hope you don't mind) the following way, so that the ideas in the guide above can be applied:
```
open class CancelResourceTest {

    private val cancelManager: CancelManager = mockk(relaxed = true)

    private val service: CancelResource = CancelResource(cancelManager)

    @BeforeEach
    fun setUp() {
        clearAllMocks()
    }

    @Test
    fun runTest() {
        val id = "dummy item"
        cancelManager.addItem(id)

        service.cancelItem(id)

        verify { cancelManager.addItem(id) }
    }
}

@Path("/canceling")
class CancelResource(@Inject val cancelManager: CancelManager) {

    @POST
    @Path("{id}")
    fun cancelItem(@PathParam("id") id: String){
        cancelManager.addItem(id)
    }
}

@ApplicationScoped
class CancelManager {
    var ids = setOf<String>()

    fun addItem(id: String) {
        ids = ids.plus(id)
    }
}
```

I hope it helps

**Comment by Daniel-Jacob** [comment]
Could you show me your import statements? I have had this exception once before when I was using the wrong @Test annotation. Also, do you have @RunWith or @ExtendsWith annotation on your class?
