### ISSUE TITLE
Ques: Verify constructor lambda

### ISSUE THREAD

**Issue by kdani41** [mockk/mockk#556]
I want to verify the number of calls being invoked by the lambda.

This lambda serves as a callback to deliver the state changes. I want to constraint the lambda to be used only via constructor.

Is there any way to test this when lambda is in constructor param?

Tried the following but this doesn't seem to work.

```kt
class SampleTest {

    private lateinit var sut: Sample

    @Test
    fun `test lambda is called`() {
        val captureCallback = slot<(String) -> Unit>()
        every {
            sut = Sample(capture(captureCallback))
        } answers {
            captureCallback.captured("")
        }
        verify(exactly = 1) {
            captureCallback.captured("")
        }
    }
}

class Sample(val onClick: (String) -> Unit) {

    init {
        triggerLambda()
    }

    private fun triggerLambda() {
        onClick("")
    }
}

**Comment by dnmolchanov** [comment]
If you only care about checking if the lambda is called or not and don't care about verifying the param, how about doing this instead:
```kotlin
class SampleTest {

    private val callback: (String) -> Unit = mockk(relaxed = true)

    @Test
    fun `test lambda is called`() {
        Sample(callback)
        verify(exactly = 1) { callback.invoke(any()) }
    }
}
```

**Comment by Raibaz** [comment]
If you want to verify that your callback is only called once when you instantiate a `Sample` object, then what @dnmolchanov suggests is correct.

**Comment by kdani41** [comment]
@dnmolchanov  @Raibaz  Thanks this makes sense. Is there any way to verify the param as well?

**Comment by dnmolchanov** [comment]
> @dnmolchanov @Raibaz Thanks this makes sense. Is there any way to verify the param as well?

Just replace `any()` with `eq("")`.
