### ISSUE TITLE
Static: Mock Module wide Extension Method from Different Module

### ISSUE THREAD

**Issue by vander2675** [mockk/mockk#56]
Hi,

Let's say I have an Module wide free Function in one Module:
```Kotlin

fun getValue(): Int {
    return 1
}
```
With a package Path: com.company.module1
And File name FreeFunctions.kt

And I want to Mock the Response from a Test Class in another Module. 
With package Path: com.company.module2

Is this possible?
I tried:
```Kotlin
staticMockk("com.company.module1.FreeFunctions.kt").use {
    every{ getValue() } returns 1
}
```
But the mock is not used. Any help appreciated!

**Comment by oleksiyp** [comment]
Note to use class name and not file name:
```
staticMockk("com.company.module1.FreeFunctionsKt").use {
    every{ getValue() } returns 1
}
```

**Comment by oleksiyp** [comment]
That's why you need `staticMockk`, Kotlin builds class FreeFunctionsKt with static methods out of such functions.

**Comment by vander2675** [comment]
Okay thank you very much so far. Did get it working. Is it only possible to mock static functions inside the .use{} closure?

**Comment by vander2675** [comment]
And one more question:
I have an extension Function on the Abstract class io.reactivex.Observable
```Kotlin
fun Observable<TestObject>.insert(): Completable {
    return this
                  .map {
                      it.insert()
                  }
                  .ignoreElements()
}
```
I can't mock this Extension, because its an abstract class. And I cannot create an Object of Observable<TestObject> like

```Kotlin
staticMockk("com.company.module1.ExtensionKt").use {
    every { Observable<TestObject>().insert() } returns Completable.complete()
}
```
Do you have any thoughts on that?

**Comment by oleksiyp** [comment]
```
staticMockk("com.company.module1.ExtensionKt").use {
    every { any<TestObject>().insert() } returns Completable.complete()
}
```

**Comment by oleksiyp** [comment]
Something like that should be possible

**Comment by vander2675** [comment]
I see, does any only mock this one extension Function of the Object and the rest behaves normally?
Using this Technique gives me undefined Behavior.
I got it compiling with:
```Kotlin
staticMockk("com.company.module1.ExtensionsKt").use {
    every {.any<Observable<TestObject>>().insert() } returns Completable.complete()
}
```
But this seems to interfere with my Observable chain.

**Comment by oleksiyp** [comment]
Just in case you still have an issue please report it again with stack traces, examples and more details. Closing this one
