### ISSUE TITLE
Mocking of Android SDK objects with hidden methods broken from Android R

### ISSUE THREAD

**Issue by duffin22** [mockk/mockk#563]
This follows on from issues https://github.com/mockk/mockk/issues/351 and https://github.com/mockk/mockk/issues/519. 

With the [restrictions on non-SDK interfaces](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces) added from Android P, the reflection used when creating mocks of Android SDK objects fails. For Android P and Q, this could be fixed by calling `dalvik.system.VMRuntime#setHiddenApiExemptions` via meta-reflection (added in https://github.com/mockk/mockk/pull/442). This workaround has been closed up by the Android team from Android R as seen in the [source code for VMRuntime](https://android.googlesource.com/platform/libcore/+/master/libart/src/main/java/dalvik/system/VMRuntime.java#70).

### Prerequisites

- [✓] I am running the latest version
- [✓] I checked the documentation and found no answer
- [✓] I checked to make sure that this issue has not already been filed

### Expected Behavior

Android SDK objects can be mocked in instrumented tests.

### Current Behavior

Android instrument tests fail when trying to mock Android SDK objects.

#### Stack trace

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:606)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	... 1 more
Caused by: java.lang.NoSuchMethodException: android.view.View.invalidateInternal [int, int, int, int, boolean, boolean]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getDeclaredMethod(Class.java:2050)
	at io.mockk.proxy.android.MethodDescriptor.getMethod(MethodDescriptor.kt:22)
```

#### Minimal reproducible code (the gist of this issue)

The issue only reproduces if you are using real Android SDK objects along with mocked ones, for example:

```kotlin
    @get:Rule
    var rule = ActivityScenarioRule(MainActivity::class.java)

    @Test
    fun testFrameLayout() {
        val mockFrameLayout = mockk<FrameLayout>() // this crashes with the above stack trace
    }
```

**Comment by duffin22** [comment]
@oleksiyp @Raibaz it looks as though there might be a related workaround for this issue where you can allow access to hidden apis from specific classes. This has been applied in dexmaker inline here: https://github.com/linkedin/dexmaker/commit/4618994794bc3b2ae20ec44efb9d3f037ca7f340

I'm not familiar with the internals of MockK, would either of you be able to point me to the class(es) where reflection is used to access methods of classes that are being mocked so that I can try to apply something similar?

**Comment by Raibaz** [comment]
I think the right place to start looking may be [this](https://github.com/mockk/mockk/blob/master/agent/android/src/main/kotlin/io/mockk/proxy/android/advice/Advice.kt)

**Comment by duffin22** [comment]
Fixed by https://github.com/mockk/mockk/pull/568
