### ISSUE TITLE
Missing calls inside every { ... } when using spyk on an Android ViewModel 

### ISSUE THREAD

**Issue by pedronveloso** [mockk/mockk#564]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Can mock private property

### Current Behavior

Get the following error:

```
io.mockk.MockKException: Missing calls inside every { ... } block.

	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
```

#### Steps to Reproduce

I'm trying to use spyk on an Android ViewModel, but getting a weird issue for which I'm having trouble making sense.
`` viewModel = spyk(ConversationLifecycleViewModel(..), recordPrivateCalls = true)

and later on I do 

```every { viewModel getProperty "lastMessageReceivedId" } returns lastMessageSeenId```

This will throw this error: io.mockk.MockKException: Missing calls inside every { ... } block.

`lastMessageReceivedId` is defined as ```private var lastMessageReceivedId = ""```

**Comment by wp292519413** [comment]
I also encountered the same problem, I have spent half a day researching it, but I did not solve it.. 😿

**Comment by AyoolaAjebeku-tomtom** [comment]
I have the same issue too. Any solution?

**Comment by MarekMacko** [comment]
Same here

**Comment by yoviekaputra** [comment]
hi @pedronveloso, can maybe i look your viewmodel code?
bcz, i have the same issue as well, after a add an interface to my viewmodel. so that i removed the interface.
i still don't know why it happen
