### ISSUE TITLE
Mocking map invocation via chained call stopped working

### ISSUE THREAD

**Issue by cbxp** [mockk/mockk#565]
Mockk version: 1.10.5
Kotlin version: 1.4.21
OS: MacOS Big Sur 11.2
JVM: adopt-openjdk-11 version 11.0.10

Java class under test:
```
import java.util.Map;

public interface Bar {
  Map<String, Integer> getAttributes();
}

```

Test:
```
val bar = mockk<Bar>(relaxed = true)
every { bar.attributes["foo"] } returns null
bar.attributes["foo"]
```

Expected (as in version 1.9.3)
`bar.attributes` should return a `Map`

Actual
`NullPointerException` because `bar.attributes` is null

**Comment by Raibaz** [comment]
Does this still happen if you declare your mock as a relaxed mock, i.e. `val bar = mockk<Bar>(relaxed  = true)`?

**Comment by cbxp** [comment]
@Raibaz It still fails. I will update the example

**Comment by omesquita** [comment]
I have a same problem when i use `val bar = mockk<Bar>(relaxed = true) `and `every { bar.list.isEmpty() } returns false`. 
Someone find a solution?

**Comment by Raibaz** [comment]
This looks like a bug in the `AnyValueGenerator`; it should be returning an empty map for `bar.attributes` if the mock is relaxed, yet it seems like it's returning null.

**Comment by omesquita** [comment]
Thank you @Raibaz.  Can you me say how i fix it?

**Comment by pedrofsn** [comment]
Hello guys. Any updates about this issue?

**Comment by omesquita** [comment]
Hi! Anyone have a solution for this issue?
