### ISSUE TITLE
Is there something like verifyEither or verify{...}.or().verify{...}?

### ISSUE THREAD

**Issue by spyro2000** [mockk/mockk#572]
Hi there,

I wonder if I could verify that EITHER one or another all happend inside my tested class. Something like

```kotlin
verifyEither({mockA.wasCalled()}, {mockB.wasCalled()})

// --- alternative ---

verify{mockA.someFunc()}
.or()
.verify{mockA.someAlternative()}
````

Is this actually possible?

**Comment by Raibaz** [comment]
Not at the moment: #196 is about the same issue, so I'm going to close this for now.
