### ISSUE TITLE
Update on never version of dexmaker to avoid dependency on JCenter repo

### ISSUE THREAD

**Issue by gildor** [mockk/mockk#575]
Currently, mockk depend on dexmaker 2.21.0, this version available on JCentral, which will be shut down next year.
Dexmaker already released on Maven Central, but only version 2.28.1 (see https://github.com/linkedin/dexmaker/issues/172#issuecomment-786364510)

**Comment by Raibaz** [comment]
Thanks for sending this through, I upgraded the dependency, it will be used from the next release onwards.
