### ISSUE TITLE
How to mock an inner class constructor

### ISSUE THREAD

**Issue by charlesritchea** [mockk/mockk#578]
Imagine I have a class `FooService` with an inner class `FooService.Bar` that has a constructor `FooService.Bar(baz: Baz, qux: Qux)`
This service is used as a mock, i.e. `val fooService = mockk<FooService>()`

Currently, when this constructor is used, it's actually run, and using mockkConstructor or just `every { fooService.Bar(any(), any())} returns mockk<FooService.Bar>()` doesn't work.

Is there a supported way to mock inner constructors?

I know I can wrap it with a factory method that I can mock, but would rather not.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by Raibaz** [comment]
Not sure if it will work, but have you tried doing `mockkConstructor(FooService.Bar)` and then mocking your `fooService` behavior with `every { anyConstructed<FooService.Bar>().someMethod() } returns something`?

**Comment by charlesritchea** [comment]
Yes, I tried that

**Comment by Raibaz** [comment]
Can you please provide a full example?
