### ISSUE TITLE
How to verify (or capture) a return value?

### ISSUE THREAD

**Issue by volo-droid** [mockk/mockk#579]
Is there a way to verify/capture mocked method return value? The subject under test is OkHttp Interceptor

```kotlin
class MyInterceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
        val builder = chain.request().newBuilder()
            .header(ACCEPT, ACCEPT_VALUE)
            .header(CONTENT_TYPE, CONTENT_TYPE_VALUE)
        // …other headers logic

        return chain.proceed(builder.build())
    }
}

// Test

val chain = mockk<Interceptor.Chain>(relaxed = true) {
    every { request() } returns request
    every { proceed(any()) } returns response
    val slot = slot<Request>()
    every { proceed(capture(slot)) } answers {
        stubResponse.newBuilder().request(slot.captured).build()
    }
}       
```

I'd like to verify that the value returned by the `intercept` method is the same as the one returned by the `chain.proceed` method. Since the latter one is mocked with an `answers` block, I was looking for a way to capture its return value, but couldn't find a way of doing it.

### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by Raibaz** [comment]
Not really sure if this makes sense to you, but I think you can just

```
val response = something
val chain = mockk<Interceptor.Chain>(relaxed = true) {
    every { proceed(any()) } returns response
}

val returned = myInterceptor.intercept(something)

assertEquals(response, returned)
```

Does this make sense to you?

**Comment by volo-droid** [comment]
@Raibaz yes, that was what I had done in the end. Also, it's possible to just do:
```kotlin
val argSlot = slot<Request>()
val returnSlot = slot<Response>()
every { proceed(capture(slot)) } answers {
    stubResponse.newBuilder().request(slot.captured).build().also {
        returnSlot.captured = it
        returnSlot.isCaptured = true
    }
}
```
It doesn't look very elegant, but can be extracted into an extension method. I'm gonna play a bit more with it, and post the result here.
