### ISSUE TITLE
callOriginal() should be documented

### ISSUE THREAD

**Issue by AlexisRiksman-TomTom** [mockk/mockk#580]
### Expected Behavior

The ``answer`` clause ``callOriginal()`` should be documented at https://mockk.io/
This is a very useful feature of a ``spyk``, but I had to learn it from a colleague.

### Current Behavior

No reference to ``callOriginal`` present.

**Comment by Raibaz** [comment]
Thanks for spotting this! I Just added it to the doc.

**Comment by AlexisRiksman-TomTom** [comment]
Thanks for the fast reaction !
