### ISSUE TITLE
What's the correct way to do `every` for Boolean param?

### ISSUE THREAD

**Issue by anticafe** [mockk/mockk#581]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Current Behavior

I want to use `every` for property, not method. For example
```
private val mockBool: Boolean = mockk(relaxed = true)
private val myLogic = Logic(mockBool) // real use case will have more params
...
every { mockBool} returns false
assertFalse(myLogic.mockBool))
```
Then get exception: `MockKException: Missing calls inside every { ... } block.`
If I declare `private val mockBool: Boolean = mockk()`, then another exception `MockKException: no answer found for: Boolean(#3).booleanValue()`.
However, I cannot find method `booleanValue()`.

### Expected Behavior
I want to `every` for Bool type. Do you know is it possible?
Note: I know if I re-create `Logic(mockBool)` it would be fix the test case. However in my use case, I would like to just re-use its instance instead.

**Comment by Raibaz** [comment]
Hi, thanks for submitting this.

What exactly do you want to test here? 

If you want to test that your Logic class behaves differently upon different values of the boolean parameter you pass, you can just pass `true` or `false` depending on the value you want to test for.

Generally speaking, it is considered a bad practice to mock a value object, i.e. an object with no logic inside but just a value; consequently, it is a bad practice as well to mock a primitive type like Boolean.

The main reason for this is that you don't really need a mock to drive the behavior of a Boolean, you can just use different values.

Have a look at [this discussion](https://softwareengineering.stackexchange.com/questions/363112/is-it-really-a-bad-practice-to-mock-a-pojo-value-object-if-you-dont-care-abou) and [this explanation](https://github.com/mockito/mockito/wiki/How-to-write-good-tests#dont-mock-value-objects) from the Mockito docs for further reference.
