### ISSUE TITLE
Feature request: clear mocks of current thread

### ISSUE THREAD

**Issue by pelletier197** [mockk/mockk#584]
Hello dear Mockk maintainers! First of all, I would like to point out I really appreciate your work at designing such a great library to use. 

I'm writing this issue today to ask for something that maybe already exists, but might not be documented. I don't know if it's doable in any way, but i'll take my chance anyway.

There is a mechanism with `mockito` when using `junit` that automatically does the following after each test case:
- ensure all mocked methods were called during the test -> This helps ensuring you don't have useless mocking
- clear all mocks -> to ensure test independency

I don't know if that is supported out of the box with mockk for `junit` but it sure isn't with [Kotest](https://kotest.io/docs/framework/listeners.html#testlistener) framework . With Kotest, we always have to clear mocks manually every test, and also check manually that they were called (and as lazy programmers, we don't do that necessarily.. :wink: )

However, I found a way to do that properly in Kotest with Global [Test Listeners](https://kotest.io/docs/framework/listeners.html#testlistener). I can auto-wire those listeners and implement the `afterEach` methods to do the necessary checks. I am however faced with three problems that might find their solution here.

1)  The `clearAllMocks` method actually clears all the mocks globally, which is really bad to use when writing parallel unit tests, because as you might guess, it clear the mocks of other tests that are running. Would there happen to be already an existing `ThreadLocal` object that contains the mocks of the current thread? Or is it something that can be good to add in your opinion? 
Edit: _I actually found a workaround for that: I could use [Isolation mode](https://github.com/kotest/kotest/blob/master/doc/isolation_mode.md#isolation-modes) and use `InstancePerLeaf` which would also  "clear all mocks of the current tests" automatically._

2) There is no way to get the mocks instantiated by the framework easily for a test (thread), making it hard to do run verifications on all the mocks created by the current test easily

3) I see mockk has a function `confirmVerified` that ensures all called methods were verified, but does it have the opposite verification: That all mocked methods were called during the test?

Thank you for your help, and sorry for the big wall of text, but it's better to have a good initial explanation to make the problem clear :smile:

**Comment by Raibaz** [comment]
Hi, thanks for submitting this.

As for ensuring all mocked functions were actually called during test execution, it's already been requested by #334. 

There have been several requests and issues about it already and it doesn't look like too much of a pain to implement, so it may actually be the next big thing I try to tackle.

About your other request, we recently fixed #142 that does something in that direction, i.e. calling `unmockkAll()` after each test; as you correctly mention, though, this may be an issue if tests are being executed in parallel and mocks are cleared while a test is running.

Generally speaking, I think tests should be completely isolated and independent on each other, i.e. using kotest's isolation mode by default.

We could definitely think of a better integration with kotest, like providing a MockK testlistener that takes care of clearing mocks automatically as we do with the MockkExtension for JUnit; i'm just more familiar with JUnit than I am with Kotest, but I definitely think it would make sense.

About having Mockk knowing which thread each mock belongs to: it may technically be done, but it seems to me a bit overkill, given that most testing frameworks allow tests to be executed in isolation, and it's a good practice overall.

Does this make sense?

**Comment by pelletier197** [comment]
Thank you for your really fast answer. Yes, I absolutely agree with you that all of that makes sense. 

Test isolation provided by frameworks is definitely the way to go because it's much safer overall, but I haven't figured out a way to write a test listener that can get the mocks of the current test without having to provide the mocks manually to that listener. With JUnit, I believe you can get the test class in your listener and fetch the mocks by reflection or something like that. With Kotest, the mocks are not really fields of your class, but  local variables of the `init` method (don't quote me on that, i'm not 100% certain of how they did it), which makes it quite hard to fetch the mocks of the current test case.

That's why I thought of the `per thread` mock approach, but maybe there's another way around.  

That to say that it might be hard to provide the extension for Kotest right away, even if you want to, but it would definitely be a good addition to the framework!

**Comment by Raibaz** [comment]
I just found out [this](https://kotest.io/docs/framework/integrations/mocking.html) page in the Kotest doc describing mockk integration and test isolation.

Going to close this issue as it seems to be covered by Kotest.

**Comment by tonicsoft** [comment]
FYI I just tried to parallelize a Kotest suite where some specs use `clearAllMocks()`.

Adding `isolationMode = IsolationMode.InstancePerTest` in all the tests that used `clearAllMocks` (and removing `clearAllMocks` seeing as it is now redundant) worked.

Adding `@DoNotParallize` to the tests that used `clearAllMocks` also works.
