### ISSUE TITLE
Mocking the result of a secondary constructor?

### ISSUE THREAD

**Issue by byamba3** [mockk/mockk#590]
I would like to mock the result of a secondary constructor of a class.

Let's say I have a class called `SomeMock`, and there's another class called `SomeMockWrapped` which is essentially almost the same class with custom modifications.
```
class SomeMock(val a: String = "")

class SomeMockWrapped(private val a: Int = 0) {
  constructor(someMock: SomeMock) : this(someMock.a.toInt())  

 companion object {
  // does the same thing as the secondary constructor
   fun from(someMock: SomeMock) {
        return SomeMockWrapped(someMock.a.toInt())
   }
 }
}
```

Now I want every creation of `SomeMockWrapped` from `SomeMock` to return the right mocked data. This is what I have right now which works:
```
val someMock: SomeMock = mockk()
val someMockWrapped: SomeMockWrapped = mockk()

mockkObject(SomeMockWrapped)
 every { SomeMockWrapped.from(someMock) } returns someMockWrapped
```

However, I'd like to mock it just using the secondary constructor instead like the following, which does not work: 
```
val someMock: SomeMock = mockk()
val someMockWrapped: SomeMockWrapped = mockk()

mockkConstructor(SomeMockWrapped::class)
every { SomeMockWrapped(someMock) } returns someMockWrapped
```

I noticed that we can mock functions easily but not constructors. I really wish we had this ability in mockk.

**Comment by Raibaz** [comment]
This was actually fixed in 1.11.0 with the introduction of `constructedWith`.
