### ISSUE TITLE
Is there a way to run a `verifySequence` ignoring parent private methods?

### ISSUE THREAD

**Issue by desgraci** [mockk/mockk#591]
### Expected Behavior
I was expecting to do a `verifySequence` and be able to ignore the private methods not relevant for my test

### Current Behavior
I get an `java.lang.AssertionError: Verification failed: calls are not exactly matching verification sequence` and the test fails

### Failure Information (for bugs)
This could be related to the limitation of Mockk with private methods of a parent class, so prbly is not a bug.

#### Steps to Reproduce
```
abstract class A {
protected fun methodA(){
   methodB()
}

private fun methodB(){
...
} 
}

class B(): A {
fun callMethods(){
methodA()
}
}

//////Meanwhile in the test///////
@Spykk
lateinit var b:B
...
b.callMethods
verifySequence {
                b invoke "methodA"  //works without methodB being called
}
```
error cause was expecting `methodB` now, I cannot invoke or `excludeRecords` for `methodB`
Please provide detailed steps for reproducing the issue.

#### Context

I have reactive apps, that could be calling internal methods not relevant for my test

* MockK version: 1.10.6
* OS: OSX
* Kotlin version: 1.4.30
* JDK version: don't remember :p
* JUnit version: 4
* Type of test: unit test OR android instrumented test: BOTH

#### Failure Logs
```
java.lang.AssertionError: Verification failed: calls are not exactly matching verification sequence

Matchers: 
B(#5).methodA()

Calls:
1) B(#5).methodB()
2) B(#5).methodA()
```
#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
io.mockk.MockKException: Class cast exception. Probably type information was erased.
In this case use `hint` before call to specify exact return type of a method. 

	
 io.mockk.impl.InternalPlatform.captureStackTrace (InternalPlatform.kt:121)              
                                                   io.mockk.impl.stub.MockKStub.handleInvocation  (MockKStub.kt:247)                     
                 io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation        (JvmMockFactoryHelper.kt:25)           
                                  io.mockk.proxy.android.advice.Advice$handle$1.call              (Advice.kt:77)                         
                         test.project.app.viewmodel.B.toState           (-:40)                                 
          test.project.presentation.B$DefaultImpls.A       (B.kt:25) 
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

**Comment by Raibaz** [comment]
The reason why you are facing this issue is that `verifySequence` is meant to be used for verifying that exactly all the functions in the verification block are being called, no more and no less.

If you have a sequence of functions being called that you want to verify but is not consisting of _all_ the functions being called you can use `verifyOrder`.
