### ISSUE TITLE
Unresolved reference: mockk with Kotest

### ISSUE THREAD

**Issue by sergey-morenets** [mockk/mockk#595]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Expected Behavior

Tests with mokks are running without compilation errors

### Current Behavior

When I try to run test in IDE or the terminal, I always get this error: 

`Unresolved reference: mockk`

#### Steps to Reproduce

Just runs the test in IDE (Intellij) or using command: _gradle test._

#### Context

* MockK version: 1.9.3
* OS: Windows 10
* Kotlin version: 1.4.32
* JDK version: 1.15
* JUnit version: 5.7.1
* Type of test: unit test 

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
    val kotestVersion = "4.4.3"

    testImplementation("io.kotest:kotest-runner-junit5:$kotestVersion")
    testImplementation("io.kotest:kotest-assertions-core:$kotestVersion")
    testImplementation("io.kotest:kotest-property:$kotestVersion")
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package io.mockk.gh

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.mockk.*
import server.Server
import server.Writer

class ServerTest : StringSpec({

    val writer = mockk<Writer>()
    val server = Server(writer)
    every { writer.write(any()) } just Runs

    "Server start should write log message" {
        server.start()
        server.started shouldBe true
        verify(exactly = 1) { writer.write("Success") }
    }
})
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by Raibaz** [comment]
Kind of a wild guess here, but are you including `testImplementation("io.mockk:mockk:1.11.0")` in your build.gradle?

**Comment by sergey-morenets** [comment]
> testImplementation("io.mockk:mockk:1.11.0")

Thank you, it helped. I assumed that Kotest dependencies are enough for use Mockk.
