### ISSUE TITLE
Increased heap consumption: Mocks are not freed from memory even after the tests in the test class are completed

### ISSUE THREAD

**Issue by AshokKumarMandava** [mockk/mockk#596]
### Prerequisites
I am running the latest version
I checked the documentation and found no answer
I checked to make sure that this issue has not already been filed

### Expected Behavior
Mocks can be freed from the memory after the test case is completed or at least after all the test cases of a test class are completed.

### Current Behavior
Mocks are not freed from memory.

### Failure Information (for bugs)
I have written lot of test cases. Each test case repeatedly (large no of times) creates the class under test and its spy by mocking many things.

I observed that heap size consumption is increased by 1+ GB. When I analysed the heap dump, I see many objects of class under test are leaked.

#### Steps to Reproduce
1. Create a simple unit test by creating a mock in a new test class.
2. In a test class which gets executed later to the one created in step1, in @BeforeClass annotated method, collect the heap dump of the Java process in which these tests are executing. I pasted the code for collecting heap dump (HeapDumpCollector.dumpHeap()).
2. Run tests from command line.
3. Analyse the heap dump using Eclipse Memory Analyser Tool. Go to Histogram and search for the test class. Right click on it > List Objects > With Incoming references > Select any item > right click > Path to GC roots > exclude weak references

#### Context
* MockK version: 1.11.0 and 1.10.0
* OS: Mac OS
* Kotlin version: 1.4.30
* JDK version: "11.0.10" 2021-01-19 LTS
* JUnit version: 4.+
* Type of test: unit test

#### Failure Logs
![image](https://user-images.githubusercontent.com/49074785/113672153-fb670d00-96d4-11eb-85e9-c04abe7b64f9.png)
![image](https://user-images.githubusercontent.com/49074785/113672223-0d48b000-96d5-11eb-8159-52b83c1213f7.png)

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9"

    testImplementation 'junit:junit:4.+'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.3.7'
    testImplementation 'androidx.test.ext:junit:1.1.2'
    testImplementation "io.mockk:mockk:1.11.0"
    testImplementation "android.arch.core:core-testing:1.1.1"
    testImplementation 'androidx.test:runner:1.3.0'
    testImplementation 'androidx.test.ext:junit-ktx:1.1.2'
    testImplementation 'org.robolectric:robolectric:4.5.1'
    
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.ashok.app.test.mockkheapincreaseverify

import io.mockk.*
import org.junit.*

class BTest {

    @Test
    fun b1() {
        val bMock: B = mockk()
        every {bMock.b1()} returns 10
        every {bMock.b2()} returns 20
        every {bMock.b3()} returns 30
        val retVal = bMock.b1()
        Assert.assertEquals(10, retVal)
    }
    
    @After
    fun afterTest() {
        clearAllMocks()
    }

    companion object {
        @AfterClass
        @JvmStatic
        fun afterClass() {
            unmockkAll()
        }
    }

}


package com.ashok.app.test.mockkheapincreaseverify

import java.io.BufferedReader
import java.io.File
import java.io.FileOutputStream
import java.io.InputStreamReader
import java.lang.StringBuilder
import java.text.SimpleDateFormat
import java.util.*

class HeapDumpCollector {
    companion object {
        fun getPid(): String? {
            val command = "jps -lv"
            val process = Runtime.getRuntime().exec(command)
            process.waitFor()
            val bufferedReader = BufferedReader(InputStreamReader(process.inputStream))
            val stringBuilder = StringBuilder()
            var pid: String? = null
            while (bufferedReader.readLine()?.let {
                    stringBuilder.append(it).append("\n")
                    if (it.contains("com.intellij.rt.junit.JUnitStarter") ||
                        it.contains("worker.org.gradle.process.internal.worker.GradleWorkerMain")) {
                        pid = it.split(" ")[0]
                    }
                    } != null) {}
            println(stringBuilder.toString())
            println("pid: $pid")
            return pid
        }

        fun dumpHeap(fileNameWithoutExtension: String): Boolean {
            val pid = getPid()
            val bytes = getHeapUsageInBytes()

            val fileOutStream = FileOutputStream(File("/Users/ashokmandava/temp/${getCurrentDateTime()}-$fileNameWithoutExtension.txt"))
            fileOutStream.write("HeapDumpCollector.dumpHeap() - bytes: $bytes kb: ${bytes.bytesToKiloBytes()} mb: ${bytes.bytesToMegaBytes()}".toByteArray())
            fileOutStream.flush()
            fileOutStream.close()

            println("HeapDumpCollector.dumpHeap() - bytes: $bytes kb: ${bytes.bytesToKiloBytes()} mb: ${bytes.bytesToMegaBytes()}")
            val command = "jmap -dump:live,format=b,file=/Users/ashokmandava/temp/${getCurrentDateTime()}-$fileNameWithoutExtension.bin $pid"
            println("HeapDumpCollector.dumpHeap() - command: $command")
            val process = Runtime.getRuntime().exec(command)
            process.waitFor()
            val bufferedReader = BufferedReader(InputStreamReader(process.inputStream))
            var output: String = ""
            while (bufferedReader.readLine()?.let {
                    output = it } != null) {}
            if ("Heap dump file created" == output) {
                println("HeapDumpCollector.dumpHeap() - heap is dumped successfully")
                return true
            } else {
                println("HeapDumpCollector.dumpHeap() - failed to dump the heap")
                return false
            }
        }

        fun getHeapUsageInBytes(): Long {
            val runtime = Runtime.getRuntime()
            return runtime.totalMemory() - runtime.freeMemory()
        }

        fun Long.bytesToKiloBytes(): Float = this.toFloat() / 1024

        fun Long.bytesToMegaBytes(): Float = this.toFloat() / (1024 * 1024)

        fun getCurrentDateTime(): String = SimpleDateFormat("yyyy-M-dd-hh-mm-ss-SSS").format(Date())
    }
}

// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by Raibaz** [comment]
Thanks for taking the time to investigate this. Will have a look soon.

**Comment by Raibaz** [comment]
Still valid. Wondering if fixing #634 will also have impacts on this.

**Comment by elihart** [comment]
I was running out of heap space while running my test suite after adding more mockk usage in my tests; updating from 1.12.3 to 1.13.4 seems to have stopped the memory issues though so something seems to have been improved in recent releases.

**Comment by elihart** [comment]
Some more information - it turns out I cannot use 1.13.4 because of https://github.com/mockk/mockk/issues/997

Unfortunately 1.13.3 seems to still give me heap issues, so something between 1.13.3 and 1.13.4 seems to have improved the memory situation.

It would be great to get a new release that includes the fix for https://github.com/mockk/mockk/issues/997 so that we can hopefully have a new release without memory issues. thanks!

**Comment by Raibaz** [comment]
Just released 1.13.5 which fixes #997.

**Comment by AleksaMatic-TomTom** [comment]
I am still facing this issue on 1.13.5

@AshokKumarMandava did you maybe find a workaround for this issue?

**Comment by rschattauer** [comment]
I still get `Caused by: io.mockk.proxy.MockKAgentException: Value for this result is not assigned` on 1.13.5 (not on 1.13.3) when running all tests on random occasions. With jdk17 this problem increased drastically, while with jdk11 it is pretty rare.

**Comment by anykeyjunkie** [comment]
We experienced OOM issues as well after increasing our mockk usage in tests. Updating to the most recent version 1.13.5 helped shortly, but issues reappeared. We found that using `excludeRecords` command helps a lot, as stated in this issue as well: https://github.com/mockk/mockk/issues/298 Now our OOM problems are gone.

**Comment by TomBAMU** [comment]
we are still facing this issue and no updates or workrounds stated here are working. Should this be reactivated then?

**Comment by st235** [comment]
As a temporary solution I use

```kotlin
@After
fun tearDown() {
    clearAllMocks()
}
```

It seems to fix the issue in a short run. 

I, sometimes, also see `OOM` with some tests with a lot of mocks in them. I suspect either one of the following scenarios:
- There are so many mock records in tests so they consume all memory
- There is a memory leak within the library itself
