### ISSUE TITLE
`coVerify()` fails even thogh function is being called in test case

### ISSUE THREAD

**Issue by mecoFarid** [mockk/mockk#597]
On the latest version of the library following test case fails:
```
    @Test
    fun search_Success()  {
        val successResult = Result.Success(data = PlaceData<List<AutocompletePrediction>>(data = listOf()), message = "", messageResId = 0)
        val constraints = SearchPlaceConstraints("Fake place")
        coEvery { googlePlaceSearchRemoteDataSource.search(constraints) } returns successResult
        lateinit var result: Result<PlaceData<List<AutocompletePrediction>>>
        coJustRun { result = googlePlaceSearchRemoteDataSource.search(constraints)}
        coVerify { googlePlaceSearchRemoteDataSource.search(constraints) }

        assert(successResult == result)
    } 
```
"search" function being tested:
```
    override suspend fun search(searchPlaceConstraints: SearchPlaceConstraints): Result<PlaceData<List<AutocompletePrediction>>> {
        val request = FindAutocompletePredictionsRequest.builder()
            .setSessionToken(autocompleteSessionToken)
            .setQuery(searchPlaceConstraints.queryText)
            .build()
        return placesClient.findAutocompletePredictions(request).searchResult()
    }
```

With the below error:

> java.lang.AssertionError: Verification failed: call 1 of 3: PlacesClient(#2).findAutocompletePredictions(eq(FindAutocompletePredictionsRequest{query=Fake place, locationBias=null, locationRestriction=null, origin=null, countries=[], sessionToken=AutocompleteSessionToken(#1), typeFilter=null, cancellationToken=null}))) was not called
> 
> 	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
> 	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
> 	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
> 	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
> 	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
> 	at io.mockk.MockKDsl.internalCoVerify(API.kt:143)
> 	at io.mockk.MockKKt.coVerify(MockK.kt:175)
> 	at io.mockk.MockKKt.coVerify$default(MockK.kt:172)
> 	at com.voom.search.google.data.source.remote.GooglePlaceSearchRemoteDataSourceTest.search_Success(GooglePlaceSearchRemoteDataSourceTest.kt:35)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
> 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
> 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
> 
> 
> Process finished with exit code 255
>

**Comment by Raibaz** [comment]
Was this working with 1.10.*? 

If it was, my guess is that it is due to a different handling of the Result class in Kotlin 1.4, as described in #478.

**Comment by mecoFarid** [comment]
I have tried it with 1.10.6, to no avail. Mockk threw the same exception. BTW, `Result` is a custom class, not Kotlin's `kotlin.Result`
