### ISSUE TITLE
Testing a method with try/catch block result in failed test

### ISSUE THREAD

**Issue by mecoFarid** [mockk/mockk#604]
I am trying to test a method with `try/catch` block.

The method to be tested looks like this:
```
    suspend fun findPredictions(
        predictionConstraints: PredictionConstraints
    ): Result<pPredictionDataBeanp> =
        try {
            val call = remoteDataService.findPredictions(
                PredictionRequest(PredictionConstraints.points)
            )
            call.asResult()
        } catch (exception: Exception) {
            Result.Error(error = DefaultError(throwable = exception))
        }
```
Whenever `orderRemoteDataServiceInterface.findVehiclePredictions()` throws exception it will caught an returned as `Error`:

The following test is intended to test the "exception" scenario:
```
    @Test
    fun test_ErrorOnException_findPredictions(){
        val constraints =        // Omitted
        val request =              // Omitted
        val mockResponse = // Omitted

        // Mock every call to findPrediction
        coEvery { mockRemoteService.findPredictions(request)} returns if(serviceThrowsException) {
            throw IOException("Syntax error")
        } else {mockResponse}

        // Call the function being tested
        val result = runBlocking { remoteDataSource.findPredictions(constraints) }

        // assert 
       assert(result is Result.Error)
    }
```

**Expected behavior:**
Expecting the test pass, because the exception is thrown should be caught internally and handled.

**Current behavior:**
The test method throws an exception on `throw IOException("Syntax error")` line and terminates the test resulting in a failed test.

Is there any way to "pass" the exception down as if the calling method threw the exception like the way `returns` works?

**Comment by Raibaz** [comment]
I think the right way to express what you are trying to describe in your test is this:

```
if(serviceThrowsException) {
        coEvery { mockRemoteService.findPredictions(request)} throws IOException("Syntax error")
} else {
        coEvery { mockRemoteService.findPredictions(request)} returns mockResponse
}
```

Note that this uses `throws`, not `throw`, to have the mocked method throw the exception rather than throwing it in your test, which would make it fail as you are experiencing.

Also, note that in my opinion it would probably be clearer to have two different tests, one for the case when an exception is thrown and one for the case when it isn't, rather than having an if in a test.

**Comment by mecoFarid** [comment]
Appreciate it.

I'm actually using two different tests, this method is a common helper method with appropriate input params. I trimmed other parts to make it a bit compact
