### ISSUE TITLE
Can not mock super method call in mockK?

### ISSUE THREAD

**Issue by ZSmallX** [mockk/mockk#607]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

`super.print()` is mocked by `answers`.

### Current Behavior

`super.print()` is not mocked.

#### Context

* MockK version: 1.11.0
* OS: Mac OsX
* Kotlin version: 1.3
* JDK version: Java 8
* JUnit version: 4.13.1
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

```kotlin
class SuperCallTest {

    open class Parent {
        open fun print() {
            println("Parent")
        }
    }

    class Children: Parent() {
        override fun print() {
            super.print()
            println("Children")
        }
    }

    @Test
    fun testCallSuper() {
        val children = Children()
        val spy = spyk(children)

        every { (spy as Parent).print() } answers { nothing }

        children.print()
    }

    @Test
    fun testCallSuper2() {
        val children = Children()
        val spy = spyk(children as Parent)

        every { spy.print() } answers { nothing }

        children.print()
    }

    @Test
    fun testCallSuper3() {
        mockkConstructor(Parent::class)
        every { anyConstructed<Parent>().print() } answers { nothing }

        val children = Children()

        children.print()
    }
}
```

#### Output

Console output:

```
Parent
Children
```

for both 3 cases.

**Comment by ChandoraAnkit** [comment]
Any update on this?. I'm also facing the same issue for both the  both `answers` and `returns`

**Comment by markwang1971** [comment]
@Raibaz I also need this fix in my project.

**Comment by shrralis** [comment]
+1 need this

**Comment by iamramizansari** [comment]
+1

**Comment by Yeroshin** [comment]
+1

**Comment by Prakkkmak** [comment]
Same problem here

**Comment by leonardocordeiro** [comment]
+1

**Comment by 1ast** [comment]
+1

**Comment by Raibaz** [comment]
I'd consider this a feature, not a bug.

[This stackoverflow answer](https://stackoverflow.com/a/48631616/1454) clearly states why trying to mock `super` means you are not testing what you want to test.

**Comment by piefel** [comment]
However, general answers do not address the fact that there may always be exceptions to the rule.

I cannot meaningfully unit test a class that inherits from `android.text.InputFilter.AllCaps` – during unit tests, all methods will just return `null` (an Android “feature”). Switching to compositions just makes everything more complicated.
