### ISSUE TITLE
Reorganize tests

### ISSUE THREAD

**Issue by Raibaz** [mockk/mockk#618]
The test suite is currently split between two organization models: some tests are organized by the component, or the feature, they test (like [this](https://github.com/mockk/mockk/blob/master/mockk/jvm/src/test/kotlin/io/mockk/it/StaticMockJVMTest.kt)), and a lot of tests are organized by the number of the GitHub issue they verify (like [this](https://github.com/mockk/mockk/blob/master/mockk/jvm/src/test/kotlin/io/mockk/gh/Issue102Test.kt)).

This leads to test failures due to regressions not being easy to trace, and to some features or behaviors being tested more than once in several different places.

I'd like to reorganize the tests by moving the ones in the `io.mockk.gh` to the specific package and test class they are related to, possibly adding some more descriptive test names and keeping the association with the GitHub issue in a comment.

This, BTW, also seems to me like a good starting point for new contributors to get accustomed with MockK internals.

**Comment by Endhuine** [comment]
I totally agree with this. Seems like a huge task, I'll try to carry on a little by myself, if anyone is interested please, let me know, so we don't risk doing the same job twice.

**Comment by Raibaz** [comment]
Yep I definitely don't expect this to be fixed by a single PR, it's more of an effort to be completed in a longer timespan.

**Comment by Lysoun** [comment]
I'm interested in helping out with the tests. Is this issue still a thing?
If so, do you have any advice for a new contributor to tackle such reorganization?

**Comment by Raibaz** [comment]
I think we can consider this completed, since we don't have any tests named after GitHub issues anymore.

However, there are plenty of issues tagged with `good-first-issue` that you can start tackling :)
