### ISSUE TITLE
Use refreshVersions?

### ISSUE THREAD

**Issue by jmfayard** [mockk/mockk#629]
Hello, I'm the author of refreshVersions, a Gradle plugin whose mission is to make adding and updating dependencies faster, more convenient and less error-prone

See [https://jmfayard.github.io/refreshVersions/](https://jmfayard.github.io/refreshVersions/)

I'm currently working on improving how we migrate existing projects. I prefer to work on real-world projects, that's why I'm looking for existing open-source projects to contribute to.
Would you be interested in having a pull request adding refreshVersions to mockk?

**Comment by henrik242** [comment]
I'd rather use the new central declaration of dependencies from Gradle 7: https://docs.gradle.org/current/userguide/platforms.html

**Comment by jmfayard** [comment]
@henrik242 refreshVersions or Gradle versions catalog

Why not both?

The versions catalog provides typesafe accessor (like the buildSrc module but better) while refreshVersions provides something different : automatically find available updates for versions.

And they work well together, refreshVersions has a task `refreshVersionsCatalog` that generates the versions catalog

**Comment by henrik242** [comment]
> And they work well together, refreshVersions has even a task refreshVersionsCatalog that generates the versions catalog

But this isn't released yet, right?

**Comment by jmfayard** [comment]
It's released in a snapshot version, and it only needs to be run once, meaning I can downgrade to the stable version after.
