### ISSUE TITLE
getString(any(), any()) returns constant resource value

### ISSUE THREAD

**Issue by ecejmsr** [mockk/mockk#630]
### Expected Behavior

Expecting to receive used string resource.
1900369 08:30 PM1900298

### Current Behavior

Receiving constant string resource.

2131952655 08:30 PM2131952610

### Failure Information (for bugs)

I'm not certain if this is a bug or lack of my understanding to implement the test correctly. I'm getting the same string resource from my test regardless of the classes real return value. It happens with the nested getString(any(), any()) function. I'm assuming it has something to do with the `every { mockApp.getString(any(), any()) } answers { it.invocation.args[0].toString() }`, but this works fine for single getString(any()). I thought this issue would help:
https://github.com/mockk/mockk/issues/224 but I couldn't seem to find the answer I was looking for in the PR 

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create function utilizing getString(any(), any()
2. getString returns same value of resource

#### Context

* MockK version: 1.11.0
* OS: MacOS(Big Sur)
* Kotlin version: 1.4.31-release-Studio4.1-1
* JDK version: 14.0.2
* JUnit version: 4.13
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
```
package io.mockk.gh

import io.mockk.every
import io.mockk.mockk
import kotlin.test.Test

class TestSubject {

    private val mockApp = mockk<MyApplication>(relaxed = true)
    private val mockTimeProvider = spyk(TimeProviderImpl())

    @Before
    fun setUp() {
        every { mockApp.getString(any()) } answers { it.invocation.args[0].toString() }
        every { mockApp.getString(any(), any()) } answers { it.invocation.args[0].toString() }
        testSubject = TestSubject(mockApp, mockTimeProvider)
    }

   //This one will return the same string resource even though
    @Test
    fun `nested getString resource should return Opens Thursday at 0830 AM`() {
       val timeModel = createTimeModel()
       
       val result = testSubject.getFormattedOpenTimes(timeModel)
       
        result.assertEqual(
                StringBuilder(
                     mockApp.getString(R.string.SEARCH_entity_opensAtLabel,
                    "Thursday"
                    ))
                    .append(" ")
                    .append("08:30 PM")
                    .append(mockApp.getString(R.string.ET))
                    .toString()
        )
    }
}
```
    
```
class Subject {
      fun getFormattedOpenTimes(timeModel: TimeModel): String {
            if(timeModel.day == GregorianCalendar.dayOfWeek) {
              return  StringBuilder(
                     mockApp.getString(R.string.opensAtLabel,
                    mockApp.getString(R.string.todayAtLabel)
                    ))
                    .append(" ")
                    .append(timeModel.openTime)
                    .append(mockApp.getString(R.string.ET))
                    .toString()
                   )
      } else {
           return  StringBuilder(
                     mockApp.getString(opensAtLabel,
                     mockApp.getString(R.string.tomorrowAtLabel)
                    ))
                    .append(" ")
                    .append(timeModel.openTime)
                    .append(mockApp.getString(R.string.ET))
                    .toString()
                   )
      }

}
```
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------

**Comment by ecejmsr** [comment]
I don't think anyone is going to be looking into this. I can't get this working successfully with single strings, but not with multiple. If any mod is here I guess it can be closed.

**Comment by Raibaz** [comment]
Ok, thanks for checking in.

**Comment by tonymanou** [comment]
@ecejmsr Sorry I am a bit late to the party... I had a similar mocking problem that got resolved using the `anyVararg()` matcher instead of `any()`.

In your setup method, try to replace the second line by
```kotlin
every { mockApp.getString(any(), *anyVararg()) } answers { it.invocation.args[0].toString() }
```
(I suppose you could drop the first line too, as it would become redundant :thinking:)

Good luck!
