### ISSUE TITLE
Bug: Invoking a mock too many times leads to halting execution

### ISSUE THREAD

**Issue by Kantis** [mockk/mockk#634]
### Expected Behavior

Invoking a mockk should never cause a test to hang. If too many invocations lead to performance issues, it would be better to either: 
* throw an exception once a reasonable cap is reached
* rotate away old data

### Current Behavior

After invoking a mock around 130 000 times (on my machine, running JDK 15 on Windows) further invocations will hit a wall and take forever (minutes) to finish.

### Steps to Reproduce

I made a small reproduction repo here: https://github.com/Kantis/mockk-repro

1. Run `./gradlew test -i` and you'll see some output as the mock is invoked over and over until it causes problems.

#### Context

* MockK version: 1.11.0
* OS: Windows
* Kotlin version: 1.5.10 (Also applies to 1.4.32)
* JDK version: 15
* ~JUnit version~ Kotest: 4.6.0
* Type of test: Unit test

**Comment by Raibaz** [comment]
This shouldn't be too hard to fix, it should be just a matter of setting a cap to the size of recorded calls and throwing a clear enough exception when the size exceeds a threshold.

(It should be a very rare case though)

**Comment by ahmadshabib** [comment]
@Raibaz Is it up for grabs, I would like to contribute with this.

**Comment by Raibaz** [comment]
Sure it is, basically every open issue can be considered up for grabs :)

**Comment by ahmadshabib** [comment]
@Raibaz Great! I will pick it up then.
Who should I tag in case of questions?

**Comment by Raibaz** [comment]
Me :)

Thanks for picking this up!

**Comment by Kantis** [comment]
@Raibaz @ahmadshabib has there been any progress on this? I saw @Raibaz is planning a release soon-ish and if nothing is started I might give it a go to get it into the next release.

**Comment by Raibaz** [comment]
Sure, the release does not take long to prepare so I can wait if you want to have a look at this.

**Comment by Kantis** [comment]
@Raibaz I added this locally. I was testing it and noticed that the reproduction has no problems running on a build from latest master, so something seems to have changed which fixes the issue. 

Is there any snapshot-repository where I can get the latest master as it would be when built using the regular release-pipeline? If not, I think it's better we go ahead with the release and I can try it out with an official build and hopefully close this :)

**Comment by ahmadshabib** [comment]
@Kantis @Raibaz  Hey guys, sorry for replying late, I wasn't able to look into it, unfortunately.
If it is not a release blocker I would be working on it later next week, otherwise some one else can pick it up and I can work on a different ticket

**Comment by Raibaz** [comment]
No worries, it's definitely not blocking any release, feel free to work on it whenever you like.
