### ISSUE TITLE
NullPointerException while using 'and' matcher with capture

### ISSUE THREAD

**Issue by glockbender** [mockk/mockk#647]
### Failure Information (for bugs)

I've updated:
- mockk from 1.9.3 to 1.11.0 
- kotlin 1.4.30 to 1.5.10
 and after that, the code below throws NPE. 

#### Steps to Reproduce

Run code below

#### Context

* MockK version: 1.11.0
* OS: macos Catalina 10.15.7
* Kotlin version: 1.5.10
* JDK version: 11.0.10
* JUnit version: 5.7.2
* Type of test: unit test

#### Stack trace

```
java.lang.NullPointerException
	at org.proj.userservice.domain.model.DeviceToken.hashCode(domain.kt)
	at io.mockk.AndOrMatcher.hashCode(Matchers.kt)
	at java.base/java.util.ArrayList.hashCodeRange(ArrayList.java:627)
	at java.base/java.util.ArrayList.hashCode(ArrayList.java:614)
	at io.mockk.InvocationMatcher.hashCode(API.kt:3782)
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.get(HashMap.java:552)
	at java.base/java.util.Collections$SynchronizedMap.get(Collections.java:2594)
	at io.mockk.impl.InternalPlatform.customComputeIfAbsent(InternalPlatform.kt:39)
	at io.mockk.impl.stub.MockKStub$childMockK$$inlined$synchronized$lambda$1.invoke(MockKStub.kt:192)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:72)
	at io.mockk.impl.log.SafeToString.exec(SafeToString.kt:10)
	at io.mockk.impl.stub.MockKStub.childMockK(MockKStub.kt:191)
	at io.mockk.impl.recording.PermanentMocker.permamentize(PermanentMocker.kt:48)
	at io.mockk.impl.recording.PermanentMocker.mock(PermanentMocker.kt:24)
	at io.mockk.impl.recording.states.RecordingState.mockPermanently(RecordingState.kt:121)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:33)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:63)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)

```

```kotlin

val kotestVersion = "4.6.0"
val kotestExtVersion = "1.0.0"

fun kotest(moduleName: String, version: String = kotestVersion) = "io.kotest:kotest-$moduleName-jvm:$version"
fun kotestExt(moduleName: String, version: String = kotestExtVersion) = "io.kotest.extensions:kotest-$moduleName:$version"

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
    testImplementation(kotest("runner-junit5"))
    testImplementation(kotest("property"))
    testImplementation(kotestExt("property-arrow")) {
        exclude("io.arrow-kt")
    }
    testImplementation(kotest("assertions-core"))
    testImplementation(kotestExt("assertions-arrow")) {
        exclude("io.arrow-kt")
    }
    testImplementation(kotestExt("extensions-testcontainers"))
    testImplementation(kotestExt("extensions-spring"))
    testImplementation(springBoot("test")) {
        exclude(module = "junit")
        exclude(module = "mockito-core")
    }
    testImplementation("io.mockk:mockk:1.11.0")
}

class Spec: FreeSpec({

    data class DevicePinToken(
      val userId: UUID,
      val deviceId: String,
      val creationTime: LocalDateTime
    )

    open class Mockks {
            val service: DeviceService = mockk()
            val deviceSlot = slot<DeviceToken>()
    
            init {
                every { // Failed here
                    service.upsertDeviceToken(
                        and(
                            capture(deviceSlot), 
                            match { it.deviceId == deviceId && it.userId == userId}
                        )
                    )
                } just Runs

     "any spec" {
            with(Mockks()) { // Mockks initialization failed

            }
     }
})
```

**Comment by Endhuine** [comment]
I give it a shot and the problem seems related only to kotlin 1.5
Running the same test with both mockk 1.11.0 and 1.9.3 with kotlin 1.4 is fine.

@Raibaz I'll try giving it a shot.

**Comment by Raibaz** [comment]
Great, thanks @Endhuine!

**Comment by Endhuine** [comment]
@Raibaz The problem seems not only with a matcher and a capture but with the `AndOrMatcher` itself. 

I double-checked and the issue can be related to the [new IR compiler](https://kotlinlang.org/docs/whatsnew15.html#stable-jvm-ir-backend) that is the default in kotlin 1.5. 
Setting up the new compiler with 1.4.30 with
```
tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        useIR = false
    }
}
```
ends up with the same exception.

I will have to dig more

**Comment by glockbender** [comment]
This issue is still relevant

**Comment by untra** [comment]
I am reproducing this myself. glad I found someone has already made a github issue. defiantly looks like the `and` matcher calls  equality operation, which calls hashcode, which tested objects may not define or be capable of responding to.

**Comment by gmazzo** [comment]
Not sure it's related, but I just faced this issue while bumping to Kotlin 1.7. After digging deeper in the issue, it seems, at least in my case, the NPE it's actually happening while instrumenting the mocked class:
![image](https://user-images.githubusercontent.com/513566/204737480-4fee6636-817e-4e89-9098-81382b6661ba.png)

**Comment by gmazzo** [comment]
I'm pretty sure the issue is here:
https://github.com/mockk/mockk/blob/master/modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/transformation/InliningClassTransformer.kt#L67

```kotlin
val spec = specMap[classBeingRedefined]
```
this assumes `classBeingRedefined` is not null, but according to the docs, it may:
> `classBeingRedefined` - if this is triggered by a redefine or retransform, the class being redefined or retransformed; if this is a class load, `null`

https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/ClassFileTransformer.html

**Comment by gmazzo** [comment]
It seems the one in the `android` codebase has this issue fixed already:
```kotlin
        if (classBeingRedefined == null) {
            return classfileBuffer
        }
 ```
https://github.com/mockk/mockk/blob/master/modules/mockk-agent-android/src/main/kotlin/io/mockk/proxy/android/transformation/InliningClassTransformer.kt#L30

So both `InliningClassTransformer` classes have diverged. I'm going to open a PR to fix the JVM one as well
