### ISSUE TITLE
JetBrains community support for contributors

### ISSUE THREAD

**Issue by oleksiyp** [mockk/mockk#655]
I negotiated to get additional 4 full-pack licenses(all products) for open source development from JetBrains.
The condition to get is sufficient contributions to an open-source project during 3 months.
Licenses are targeted only for non-commercial open-source development.

@qoomon @hrach @drazen04 and @Endhuine please get back to me in this thread if you are interested to get them

JFYI @Raibaz

**Comment by Raibaz** [comment]
Yep i've seen the thread, thanks a lot!

**Comment by drazen04** [comment]
Sounds great, thank you! :)

**Comment by oleksiyp** [comment]
@drazen04  sent an activation link to hotmail email

**Comment by qoomon** [comment]
@oleksiyp oh thx, that would be neat :-)

**Comment by oleksiyp** [comment]
@qoomon sent via linkedin 😄

**Comment by Endhuine** [comment]
That's nice! Thank you! :D

**Comment by oleksiyp** [comment]
Closing ticket. Let's check if we can get more licenses with next releases 😄 

@Endhuine I sent you the activation code. It is up to you if you want to activate it. If you take it - good, if not it will be a free slot that might be used for anybody else who's contributing. Thanks!

**Comment by oleksiyp** [comment]
Also @Endhuine I suggest editing your git configs so that it is picked up by Github. First, it is going to be displayed in statistics(and thus no need to explain JetBrains that commits are done via another name)
