### ISSUE TITLE
Add a function to confirm that all mock/spy invocations are verified

### ISSUE THREAD

**Issue by erikhuizinga** [mockk/mockk#659]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version (v1.12.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

There is `fun confirmVerified(vararg mocks: Any)`, but it might be handy to just have a shorthand to verify that _all_ invocations of _all_ mocks/spies are verified. Suggested signature: `fun confirmAllVerified(): Unit`.

### Current Behavior

There is no function that allows to confirm that all mock/spy calls were verified.

**Comment by Raibaz** [comment]
This looks really like a duplicate of #334.

**Comment by erikhuizinga** [comment]
It might be, although the approach seems a little different. I'll leave it up to you to close this issue if you think this is not the way to go, e.g. if the other issue would be a better approach.

**Comment by d35h** [comment]
@erikhuizinga there is a verifyAll, which you can use for that purpose

```
        verifyAll {
            mock.processValue(arg1)
            mock2.processValue(arg2)
        }
```
