### ISSUE TITLE
@InjectMockks + @SpyK: Wrong order?

### ISSUE THREAD

**Issue by spyro2000** [mockk/mockk#668]
Hi there,

since 1.12.0, we finally can use `@SpyK` and `@InjectMocks` together :)
But this seem only to work if the variable of the test instance **has a alphabetically 'higher' name**, than the spy variable.

Given these two classes here:

```kotlin
class ServiceToSpy(private val log: Logger) {
    fun sayHello(): String {
        log.log(Level.INFO, "Saying hello" )
        return "Say hello"
    }
}

class ServiceToTest(private val serviceToSpy: ServiceToSpy, val log: Logger) {
    fun doSomething() {
        log.log(Level.INFO, "Doing something" )
        serviceToSpy.sayHello()
    }
}
```` 

While this here runs just fine:

```kotlin
internal class SpyTest {

    @MockK
    lateinit var log: Logger

    @SpyK
    @InjectMockKs
    lateinit var serviceToSpy: ServiceToSpy

    @InjectMockKs
    lateinit var underTest: ServiceToTest

    @BeforeEach
    fun setUp() {
        MockKAnnotations.init(this, relaxUnitFun = true)
    }

    @Test
    fun testSomething() {
        // WHEN
        underTest.doSomething()

        // THEN
        verify { serviceToSpy.sayHello() }

    }
}
````

When I just rename `serviceToSpy` to ` xServiceToSpy`, the test setup fails:

````
No matching constructors found:
constructor(serviceToSpy : com.airbus.remis.remisapi.common.domain.services.ServiceToSpy = <not able to lookup>, log : java.util.logging.Logger = Logger(log#1))
````

Is this expected? The only workaround for me currently is something like 

```kotlin
@SpyK
var serviceToSpy = ServiceToSpy(mockk(relaxed = true)) // can't reuse existing mock here
````

Absolute Killer-Solution would be, if MockK could internally call the constructor of the object to spy, using the provided mocks

```kotlin
@SpyK
lateinit var serviceToSpy: ServiceToSpy // will not work with non-empty constructor
````

**Comment by Raibaz** [comment]
Very weird and looking like a bug indeed, thanks for submitting this.

**Comment by spyro2000** [comment]
Well, er, will there be any fix or something? :)

**Comment by Xintong-Dai** [comment]
Run into the same issue.

When multiple  @InjectMockKs exists, it looks like the injected objects are created in class name order, ignoring constructor dependence.

**Comment by wfan3** [comment]
Having the same issue currently... Any fix???

**Comment by spyro2000** [comment]
@[Raibaz](https://github.com/Raibaz)
Any reaction? It's been almost a year?

**Comment by SemjonWps** [comment]
This bug still exists in 2025 in Version V1.14.5
