### ISSUE TITLE
Using TestCoroutineDispatcher with MockK

### ISSUE THREAD

**Issue by Teja-Konjeti** [mockk/mockk#671]
I would like to use `val testCoroutineDispatcher = TestCoroutineDispatcher()` of `api "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.1"` to run override the coroutines inside `InternalPlatformDsl.runCoroutine()`. This will help run the coroutines with an immediate dispatcher for faster execution of test cases.

Testcases fail with the following error right now.

`java.lang.AssertionError: Verification failed: call 1 of 1: Default(#3).onError()) was not called (timeout = 210 ms)`

**Comment by Teja-Konjeti** [comment]
@Raibaz Any comments on this?

**Comment by Raibaz** [comment]
Can you please provide a complete example of the behavior you'd like to achieve?
