### ISSUE TITLE
question, how to mock a constructor o return a null object

### ISSUE THREAD

**Issue by lannyf77** [mockk/mockk#673]
Having a function it is internally using the a java class which is coming from a lib, ClientCreationHandler(context, NotificationManager).

the kotlin function to be tested (need to pass the coverage test)
is `registerClientCreationHandler`
```
class Runner {
    ...
    @JvmField
    internal var mClientHandler: ClientCreationHandler? = null
   
    /** 
    /* register the handler if client has not been created
    **/
    fun registerClientCreationHandler(context: Context, notificationManager: NotificationManager) {
          mClientHandler = ClientCreationHandler(context, notificationManager)
          mClientHandler?.register() //<=== the coverage test result showing mClientHandler == null is never called
    }
    
    fun doSomethingOnClient() {
         mClientHandler?.let { ... }
    }
}
```
The  mClientHandler is always not null, so the coverage test failed the test on the line with `mClientHandler?`

the java lass in the lib:
```
class ClientCreationHandler implements IHandler {

    protected Context mAppContext;
    protected NotificationManager mNotificationManager;

    ClientCreationHandler(@NonNull Context appContext, @NonNull NotificationManager notificationManager) {
        mAppContext = appContext;
        mNotificationManager = notificationManager;
    }
```
the test below does not work

1.  got error `Not enough information to infer type variable T` on the `anyConstructed`, and error `Too many arguments for public final inline fun <reified T : Any> anyConstructed(): T defined in MockKMatcherScop` on the two `OfTypeMatcher`
2. got error `Null can not be a value of a non-null type ClientCreationHandler` on the `return null`

Is there a way to mock the constructor of `ClientCreationHandler(Context, NotificationManager)` to return a null?

```
@Test
    fun test () {
       
        mockkConstructor(ClientCreationHandler::class)
        every { anyConstructed<AppLifecycleObserver>(OfTypeMatcher<Context>(Context::class), OfTypeMatcher<NotificationManager>(NotificationManager::class)) } returns null
       
        Runner().registerClientCreationHandler(context, notificationManager)
        // verify......
    }
```

**Comment by lannyf77** [comment]
it can change to use lazy to avoid `mClientHandler?.register()`
```
    internal val mClientHandler: ClientCreationHandler by lazy {
        ClientCreationHandler(context, notificationManager)
    }
```
but question is still not sure how to mock a constructor, i.e. how pass in the class type `OfTypeMatcher<Context>(Context::class)`?

**Comment by Endhuine** [comment]
I think you can rewrite your code like this:

```kotlin
class Runner {
    ...
    @JvmField
    internal var mClientHandler: ClientCreationHandler? = null
   
    /** 
     * register the handler if a client has not been created
     **/
    fun registerClientCreationHandler(context: Context, notificationManager: NotificationManager) {
          mClientHandler = ClientCreationHandler(context, notificationManager).apply {
               register()
          }
    }
    
    fun doSomethingOnClient() {
         mClientHandler?.let { ... }
    }
}
```

Your failing coverage is telling you (beware that this is my personal opinion) that there is a possibility that your handler is turned to null just after being created. 
Using `apply` you are making explicit that this is the exact instance that you want to register and, to me, gives better readability. 
Plus I don't think that mocking a constructor to return null should be done, a constructor has a non-null return type, at most, it could fail with an exception.
