### ISSUE TITLE
Failed matching mocking signature using `any()` when argument is `Unit`

### ISSUE THREAD

**Issue by vitorhugods** [mockk/mockk#675]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I must say that the keyword `Unit` is beyond useless, as it actually broadens the search. The word "Unit" is pretty much _always_ together with Mockk in the form of "unit testing" 🤔. So I apologise beforehand if my search was just fruitless because of that.

### Expected Behavior

When using `any()` argument matcher, it should work with _any_ arguments, including arguments of type `Unit`.

### Current Behavior

It fails to stub `Unit` parameters, with `io.mockk.MockKException: Failed matching mocking signature for SignedCall...`

### Failure Information

Seems to have started on Kotlin 1.5.0 and is still reproduceable on Kotlin 1.5.20.
Did not happen on Kotlin 1.4.30 and before that.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a mock of a class with a function that takes an `Unit` as argument
2. Use `any()` as the matcher to that argument when stubbing
3. 😢

#### Context

I've noticed the issue when upgrading from Kotlin 1.4.30 to 1.5.20.
**It seems that it was working as intended on 1.4.30 and the issue started on Kotlin 1.5.0**.
Going through the changelogs, I could not spot something that could have introduced this issue.

* MockK version: 1.12.0
* OS: Linux and Windows
* Kotlin version: 1.5.20
* JDK version: 8
* JUnit version: 4.13
* Type of test: unit test

#### Stack trace

```
io.mockk.MockKException: Failed matching mocking signature for
SignedCall(retValue=, isRetValueMock=true, retType=class kotlin.Unit, self=Thing(thing#3), method=doIt(Unit), args=[kotlin.Unit], invocationStr=Thing(thing#3).doIt(kotlin.Unit))
left matchers: [any()]

	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:99)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:63)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at com.wire.android.MockkUnitMatcherTest.given the parameter type is Unit, when using any() matcher, then mocking should succeed(MockkUnitTest.kt:25)
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
// --------------------- [GRADLE DEFINITIONS] -------------------
dependencies {
    testImplementation("io.mockk:mockk:1.12.0")
}

// ------------------ [CODE FOR REPRODUCTION] ----------------
class MockkUnitMatcherTest {

    class Thing {
        fun doIt(params: Unit){}
    }

    @MockK
    lateinit var thing: Thing

    @Before
    fun setup(){
        MockKAnnotations.init(this)
    }

    @Test
    fun `given the parameter type is Unit, when using any() matcher, then stubbing should succeed`(){
        every { thing.doIt(any()) } // Fails
    }

    @Test
    fun `given the parameter type is Unit, when using Unit parameter matching, then stubbing should succeed`(){
        every { thing.doIt(Unit) } // Succeeds
    }
}
```

**Comment by Raibaz** [comment]
This is likely because `Unit` is kind of a special type in kotlin.

A couple of questions though: 
- Does this work if you explicitly specify the type of the `any()` matcher, i.e. `every { thing.doIt(any<Unit>()) }`?
- How about using the `ofType` matcher, i.e. `every { thing.doIt(ofType(Unit::class)) }`?
- What exactly is the usage of a `Unit` parameter?

**Comment by vitorhugods** [comment]
Indeed `Unit` is special.

I have not tried with `ofType` or `any<Unit>()` as I didn't see any advantage over just using `Unit`.

About a usage, it's usualy a side-effect of generics, for example:

```kotlin
interface BaseUseCase<out Result, in Params> {
    suspend fun run(params: Params): Result
}

class GetUnreadMessages<UnreadMessagesResult, Unit>() {
    override suspend fun run(params: Unit) { ... }
}
```

Being able to use `any()` for `Unit` is great just like with any other parameter type for tests where the input doesn't matter.

If the implementation of `GetUnreadMessages` change and it now requires something other than `Unit` as argument, the tests that don't care about input would not break.

**Comment by mattbutlar** [comment]
I just wanted to jump in here and say we have ran into this exact issue as well.  Is there any potential resolution that doesn't involve changing all of the tests?  If it is not looking likely then it will probably be something I need to correct in our project sooner rather than later.

**Comment by CityTransit** [comment]
👋 I'd just like to report that I'm running into the exact same behavior during our migration from Kotlin `1.4.30` to `1.5.20`.

Tried upgrading mockk as well so I can confirm it's reproducible with mockk 1.10.0, 1.11.0, and 1.12.0

> What exactly is the usage of a Unit parameter?

With rx we will sometimes use a generic type such as [PublishSubject](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/subjects/PublishSubject.html) but just as notification that some event occurred. e.g. `onCancelButtonClicked: PublishSubject<Unit>`

**Comment by OMARIHAMZA** [comment]
Were you guys able to solve this issue?

**Comment by JonasVautherin** [comment]
Note sure if that's the same issue, but I am getting a very similar error with the [following super small test](https://stackoverflow.com/questions/69353595/failed-matching-mocking-signature-for-signedcall):

I have the following interface:

```kotlin
interface MyDescriptor {
    fun receive(): UByteArray
    fun send(bytes: UByteArray)
}
```

And my test is:

```kotlin
    @Test
    fun send_oneMessage(): Unit = runBlocking {
        val payload = "Payload message"
        val byteStream = mockk<MyDescriptor>()
        every { byteStream.send(any()) } just Runs
    }
```

I get the error:

```
io.mockk.MockKException: Failed matching mocking signature for
SignedCall(retValue=, isRetValueMock=true, retType=class kotlin.Unit, self=MyDescriptor(#1), method=send-GBYM_sE(ByteArray), args=[null], invocationStr=MyDescriptor(#1).send-GBYM_sE(null))
left matchers: [any()]
```
