### ISSUE TITLE
Suggestion: add ability to verify using a predicate

### ISSUE THREAD

**Issue by antoine-mulet** [mockk/mockk#679]
This feature exists in mockito-kotlin:
https://github.com/mockito/mockito-kotlin/blob/37bbae48634d879640a754a1b122db99f0b00478/mockito-kotlin/src/main/kotlin/org/mockito/kotlin/Verification.kt#L237-L263

Capturing in mockk is very powerful and it lets you achieve pretty much the same however it may be nice to support it in order to facilitate migrating from mockito-kotlin to mockk.

What do you think?

**Comment by Raibaz** [comment]
I think you can already implement the same behavior by using `verify(match { predicate } )`.

Note that you can also use `matchNullable` and the coroutine equivalents: take a look [here](https://mockk.io/#matchers) for reference.

Is this what you were looking for?

**Comment by antoine-mulet** [comment]
@Raibaz thanks for commenting.

`match` is indeed quite close to what I am looking for but still not exactly what I need. There are two main reasons:

1. The predicate is of type `(T) -> Boolean` while I would like a predicate of type `(T) -> Unit` to be able to use assertions, just like in mockito-kotlin.
2. The implementation of `match` that relies on `FunctionMatcher` catches any `AssertionError` to return a boolean.

Here is an example, where using `match` doesn't give great results in my opinion:

```
class DummyTest : WordSpecUnitTests() {

    interface Test {
        fun doSomethingWithLambda(lambda: (String) -> String): Boolean
    }

    val mock = mockk<Test>()

    init {

        "it" should {
            "work" {
                every { mock.doSomethingWithLambda(any()) } returns true

                mock.doSomethingWithLambda { "Hello World" }
                
                // 1 - existing match matcher
                verify {
                    mock.doSomethingWithLambda(
                        match { it.invoke("whatever") == "Hello Worldd" }
                    )
                }

                // 2 - new check matcher
                verify {
                    mock.doSomethingWithLambda(
                        check { it.invoke("whatever") shouldBe "Hello Worldd" }
                    )
                }
            }
        }
    }
}
```

Output using `match`

> Verification failed: call 1 of 1: Test(2).doSomethingWithLambda(matcher<Function1>())). Only one matching call to Test(2)/doSomethingWithLambda(Function1) happened, but arguments are not matching:
> [0]: argument: lambda {}, matcher: matcher<Function1>(), result: -

Output using `check`

> expected:<"Hello Worldd"> but was:<"Hello World">
> Expected :"Hello Worldd"
> Actual   :"Hello World"

Here is the implementation of `check` I have used in my example:

```
inline fun <reified T : Any> MockKVerificationScope.check(noinline matcher: (T) -> Unit): T =
    match(CheckMatcher(matcher, T::class))

data class CheckMatcher<in T : Any>(
    val matchingFunc: (T) -> Unit,
    override val argumentType: KClass<*>
) : Matcher<T>, TypedMatcher, EquivalentMatcher {
    override fun equivalent(): Matcher<Any> = ConstantMatcher(true)

    override fun match(arg: T?): Boolean {
        return if (arg == null) {
            false
        } else {
            matchingFunc(arg)
            true
        }
    }

    override fun toString(): String = "matcher<${argumentType.simpleName}>()"
}
```

I understand that not catching `AssertionError` and always returning `true` is a bit of a hack compared to other matchers. Also I think proper capturing should be preferred over using `check` (if we were to add it to mockk) but it would still offer some flexibility. 

As I mentioned I came across this trying to migrate from mockito-kotlin to mockk so I thought I may not be the only one. But if people think it's not a good idea to add such `check` matcher, no problem I can still add it as an extension as shown in the code above.

Hopefully why I was suggesting this new matcher is a bit clearer now.

**Comment by Raibaz** [comment]
Ok, I see what you mean now, thanks a lot for the clarification.

In my opinion, though, matcher blocks (or check blocks as in your implementation) should really be as concise as possible, i.e. one instruction at most, because they already live inside a verify block.

I'm afraid allowing assertions inside a matcher block would incentivize people to add too much complexity in there, while I think using slots and capturing parameters makes the code cleaner because it separates function invocation verification and parameter value assertions.

Does this make sense to you?

**Comment by antoine-mulet** [comment]
Thanks for your response, it makes complete sense. Feel free to close the issue then.
