### ISSUE TITLE
Migrate the build.gradle files to kotlin

### ISSUE THREAD

**Issue by Raibaz** [mockk/mockk#690]
They are all currently written in groovy; I'd like to migrate them to the build.gradle.kts format to make the whole project Kotlin-based.

I think this can be done in steps, migrating one build.gradle file at a time - not sure about it though.

**Comment by femialaka** [comment]
I would like to work on this one

**Comment by jlengrand** [comment]
@femialaka still on it? :)

**Comment by fejd** [comment]
I'd be interested in contributing to this as well.

**Comment by Raibaz** [comment]
Sure, this can be worked on by multiple people at once as there are several build.gradle files that need to be migrated.

**Comment by DeKaN** [comment]
@Raibaz Can I convert scripts from `gradle` directory into plugins using [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html)?

**Comment by jlengrand** [comment]
We start to be a lot all of a sudden XD. You can pick it up folks :).

**Comment by fejd** [comment]
I'm starting with settings.gradle now. Would you prefer one commit per Gradle file? That might make it easier to collaborate if more people are interested.

**Comment by jlengrand** [comment]
That'd be the best indeed, since a few folks are interested. Extra kudos if you mention which modules you are all planning to work on :).

**Comment by vasanthdharmaraj** [comment]
I will work on `mockk/agent/api/build.gradle`.

**Comment by geekiyer** [comment]
I will work on `agent/jvm/build.gradle`

**Comment by geekiyer** [comment]
Working on `agent/common/build.gradle`
