### ISSUE TITLE
Update Objenesis?

### ISSUE THREAD

**Issue by pvegh** [mockk/mockk#705]
Lately I'm seeing this in new Android Studios (Arctic Fox and Bumblebee):

* What went wrong:
Execution failed for task ':app:mergeExtDexLocalDebug'.
> Could not resolve all files for configuration ':app:localDebugRuntimeClasspath'.
   > Failed to transform objenesis-3.1.jar (org.objenesis:objenesis:3.1) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=23, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/foo/.gradle/caches/transforms-3/1d99eb0761d5454a8d4c29cd536a9bd2/transformed/jetified-objenesis-3.1.jar.
         > Error while dexing.

Would updating objenesis dependency to 3.2 help us?

**Comment by sgjesse** [comment]
Related issue from the Android Studio issue tracker: https://issuetracker.google.com/201206188.

**Comment by svenjacobs** [comment]
As mentioned in the [Android Studio issue](https://issuetracker.google.com/issues/201206188#comment7), upgrading objenesis to 3.2 fixes this problem. Hence an upgrade of this dependency is greatly appreciated. Currently I solve this problem with:

```kotlin
configurations.all {
    resolutionStrategy {
        force("org.objenesis:objenesis:3.2")
    }
}
```

**Comment by Raibaz** [comment]
Sure thing, upgrading to 3.2 does not seem like a breaking change to me. 

Just pushed the upgrade to master.

Thanks for noticing this!

**Comment by colintheshots** [comment]
Could we please get an updated version posted to include this fix? I haven't found that the workaround is working great in our multiplatform project.

**Comment by Raibaz** [comment]
Sure thing, I'd like to get #816 merged first and then I'll publish a release straight away.
