### ISSUE TITLE
Cannot run multiple tests in the same time when mocking object

### ISSUE THREAD

**Issue by rantianhua** [mockk/mockk#716]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I mocked an object in the before function, every unit test will invoke the object method for instantiating. I hope I can run all tests together.

### Current Behavior

 If I run the unit tests one by one, everything is fine. If I run all the tests together, all tests failed because of the object mock.

### Failure Information (for bugs)

```
Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
```

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create an object with a `createXxx` method.
2. Create a class and invoke the `createXxx` during the class is instantiating.
3. Create two unit tests and new the class in every unit test
4. Run the whole unit test class
5. You get it...

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.11.0
* OS: MacOS 10.15.7
* Kotlin version: 1.4.2
* JDK version: 11
* JUnit version: 4.13.2
* Type of test: unit test OR android instrumented test
unit test

#### Failure Logs

```
Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
```

#### Stack trace

```
Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
```

**Comment by Raibaz** [comment]
Can you please provide a working code sample to reproduce this issue?
