### ISSUE TITLE
verifyAll requires a check on all methods on a mock

### ISSUE THREAD

**Issue by hoombar** [mockk/mockk#74]
It looks like the `verifyAll` function requires a verification for all methods on a mock that have an interaction when a function is called.

Take the below example:
```
class Test(val dummy: Dummy) {
    fun doStuff() {
        dummy.method1(listOf("value"))
        dummy.method2()
    }
}
interface Dummy {
    fun method1(value: List<String>)
    fun method2(): String
}

@Test
fun verifyAllCheck() {
    val mock = mockk<Dummy>(relaxed = true)
    every { mock.method2() } returns "method2"

    val test = Test(mock)
    test.doStuff()

    // works
    verify { mock.method1(match { it.size == 1 }) }
    // does not work
    verifyAll {
        mock.method1(match { it.size == 1 })
    }
}
```
When you run the test, you get this message
>java.lang.AssertionError: Verification failed: some calls were not matched: [Dummy(dummy).method2()]

You can make the `verifyAll` section pass by adding `mock.method2()` in to the verification, because the `doStuff()` method would invoke both method calls. It is suggested that this is as per design, but if I have a couple of interactions with my mock, I might not necessarily be interested in those interactions, but would currently be forced to add them in to the verifyAll block.

What I was trying to achieve was to be able to run multiple verifications on the list that was passed in to the method:
```
    verifyAll {
        mock.method1(match { it.size == 1 })
        mock.method1(match { it.get(0) == "value })
    }
```

Perhaps there's an alternative way of doing this, but the intuitive method seemed to be `verifyAll`. Maybe the introduction of `matchAll {}` would be a good route forwards.

**Comment by oleksiyp** [comment]
I'm not able to change the semantics of current API. Many current tests will fail. So any way you need to adhere rules already presented and I can only add something to it, but first, let's clarify everything.

### Validators

|Validator|Description|
|---------|-----------|
|`verify { mock.call() }`|Do unordered verification that call were performed|
|`verify(inverse=true) { mock.call() }`|Do unordered verification that call were not performed|
|`verify(atLeast=n) { mock.call() }`|Do unordered verification that call were performed at least `n` times|
|`verify(atMost=n) { mock.call() }`|Do unordered verification that call were performed at most `n` times|
|`verify(exactly=n) { mock.call() }`|Do unordered verification that call were performed at exactly `n` times|
|`verifyAll { mock.call1(); mock.call2() }`|Do unordered verification that only the specified calls were executed for mentioned mocks|
|`verifyOrder { mock.call1(); mock.call2() }`|Do verification that sequence of calls went one after another|
|`verifySequence { mock.call1(); mock.call2() }`|Do verification that only the specified sequence of calls were executed for mentioned mocks|
|`verify { mock wasNot Called }`|Do verification that mock was not called|
|`verify { listOf(mock1, mock2) wasNot Called }`|Do verification that list of mocks were not called|

So verify all is doing the following thing:

```
Do unordered verification that only specified calls were executed for mentioned mocks
```

This means that order can be arbitrary, but only that calls should happen.

I believe you need either:

```
    verify {
        mock.method1(match { it.size == 1 })
        mock.method1(match { it.get(0) == "value })
    }
```

OR 

```
    verifyAll {
        mock.method1(match { it.size == 1 })
        mock.method1(match { it.get(0) == "value })
        mock.method2()
    }
```

So why not to use just `verify`?

**Comment by hoombar** [comment]
Ah. I tried with `verify` and that's def what I wanted. It wasn't obvious to me that I could run multiple verifications in verify, so I looked to verifyAll. I thought I tried verify and it was only picking up the first one, but I've just tried again and it worked, so I must have been mistaken.

I'll update the README and submit a PR

**Comment by oleksiyp** [comment]
Seems to be resolved

**Comment by matejdro** [comment]
So, according to above table, what is the difference between `verifyAll` and `verifySequence`?

**Comment by matejdro** [comment]
Both https://mockk.io/ and KDoc in the actual code also lack this change.

**Comment by oleksiyp** [comment]
@matejdro seems you are right, missed to press merge, just approved. Do you need these things to be mentioned in docs?

**Comment by matejdro** [comment]
> Do you need these things to be mentioned in docs?

Yes. At the moment it says that `verifyAll` only checks that all calls are verified and does not state anywhere that it also makes sure there were no other calls. It can cake a lot of unnecessary trouble and debugging on why tests fail.

**Comment by oleksiyp** [comment]
@matejdro do you use Maven or Gradle? Documentation is working differently for me in Gradle based projects than in Maven based projects(maven worse). And besides that many Kotlin projects overall doesn't open documentation correctly. (recent observation) I will recheck if something can be improved with it in MockK

**Comment by matejdro** [comment]
Gradle. 

I don't think you need to do anything special, just update the comment here: https://github.com/mockk/mockk/blob/0dd309232fc75906dc52e75c3f0dc89d9f2cc63e/mockk/common/src/main/kotlin/io/mockk/MockK.kt#L174

**Comment by harel-biton** [comment]
@oleksiyp can you please update the KDoc of `io.mockk.MockK#verifyAll` as suggested above?
I think it should be something like this:
```
Verifies all the calls of the mocks specified inside [verifyBlock]. 
Please note that once you specify a mock inside [verifyBlock], all its recorded calls are expected to be verified within [verifyBlock]. 
**Does not** verify any order
```

**Comment by Raibaz** [comment]
Hi @harel-biton, feel free to send a PR to update the KDoc, I'll review it.
