### ISSUE TITLE
coEvery blocks forever when mocking BillingClient::querySkuDetails

### ISSUE THREAD

**Issue by Dimezis** [mockk/mockk#766]
I am mocking a `BillingClient` from Google billing library -`com.android.billingclient:billing-ktx:4.0.0`

```Kotlin
    @Test
    fun lol() {
        val client = mockk<BillingClient>()
        coEvery { client.querySkuDetails(any()) } returns SkuDetailsResult(BillingResult(), emptyList())
    }
```

I don't know what's special about this extension method (`querySkuDetails`) compared to other suspend functions, but Mockk hangs forever on `coEvery`.
I don't have problems with other suspend extension functions.

There are no logs to share, no exceptions, etc, it just spins forever.

* MockK version: 1.12.1
* OS: Macos Monterey 12.1 (21C52)
* Machine: M1 Max
* Kotlin version: 1.5.31
* JDK version: JDK Azul 11.0.13
* JUnit version: 4.13.2
* Type of test: Unit test 

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    implementation "com.android.billingclient:billing-ktx:4.0.0"
}
```

**Comment by joaopegoraro** [comment]
Have you tried mocking the `querySkuDetails` method? I was having a similar problem with the `await()` extension method of `kotlinx.coroutines`, and mocking it directly solved the problem

`mockkStatic("kotlinx.coroutines.tasks.TasksKt")`

**Comment by Dimezis** [comment]
Thanks, I'll try it, it could be the reason.
But I guess the library still shouldn't get stuck on it

**Comment by Raibaz** [comment]
I think @joaopegoraro has a good point, if it's an extension function you likely need to mock it explicitly with `mockkExtension`.

We could think of adding an explicit error when an extension function is being stubbed and `mockkExtension` has not been called, but I don't even know if it's feasible.

**Comment by Dimezis** [comment]
> I think @joaopegoraro has a good point, if it's an extension function you likely need to mock it explicitly with mockkExtension


So why does this work in that case? 

```Kotlin
    @Test
    fun test() {
        val mock = mockk<BillingClient>()
        coEvery { mock.someExtension() }.returns("123")
    }

    private suspend fun BillingClient.someExtension(): String {
        delay(1)
        return this.toString()
    }
```

**Comment by tunahanbozkurt** [comment]
> Have you tried mocking the `querySkuDetails` method? I was having a similar problem with the `Task::await()` extension method of `kotlinx.coroutines`, and mocking it directly solved the problem
> 
> `mockkStatic("kotlinx.coroutines.tasks.TasksKt")`
> 
> You may wanna see #344

This method solved my problem. Can I ask where can we find this name  "kotlinx.coroutines.tasks.TasksKt". I tried to find this name but I couldn't find anything. @joaopegoraro

**Comment by arielmagbanua** [comment]
> Have you tried mocking the `querySkuDetails` method? I was having a similar problem with the `Task::await()` extension method of `kotlinx.coroutines`, and mocking it directly solved the problem
> 
> `mockkStatic("kotlinx.coroutines.tasks.TasksKt")`
> 
> You may wanna see #344

This has solve my problem as well. Thanks

**Comment by Archdoog** [comment]
For those who run into this with the billing client. I originally had:

```kotlin
    @Test
    fun `queryProductDetails calls billingClient queryProductDetails`() = runTest {
        val params: QueryProductDetailsParams = mockk()
        val result: ProductDetailsResult = mockk()
        coEvery { billingClient.queryProductDetails(params) } returns result
        billingClientAdapter.queryProductDetails(params)
        coVerify { billingClient.queryProductDetails(params) }
    }
```

Which blocked indefinitely.

Adding `mockkStatic(billingClient::queryProductDetails)` such that the test looks like:

```kotlin
    @Test
    fun `queryProductDetails calls billingClient queryProductDetails`() = runTest {
        val params: QueryProductDetailsParams = mockk()
        val result: ProductDetailsResult = mockk()
        mockkStatic(billingClient::queryProductDetails)
        coEvery { billingClient.queryProductDetails(params) } returns result
        billingClientAdapter.queryProductDetails(params)
        coVerify { billingClient.queryProductDetails(params) }
    }
```

It immediately completed and passed.

**Comment by Manuel-FG** [comment]
@Archdoog Thanks for the info.

I was having this exact problem and was about to throw in the towel and leave that `BillingClient` method without a test.

In case someone else experiences this, I'd like to contribute the following under these conditions:
- JUnit Version: 5.13.4 `org.junit.jupiter:junit-jupiter`
- MockK Version: 1.14.5 `io.mockk:mockk`
- BillingClient Version: 8.0.0 `com.android.billingclient:billing-ktx`

Whether I use `mockkStatic` on the `BillingClient` library or on the mocked `billingClient` object, the functionality is correct, and the test runs. I don't know if there's any difference or if it affects anything in this specific case!

I also had to do a `mockk<ProductDetailsResult>` with the response from its `productDetailsList`

With all that, the test no longer gets stuck in a loop and runs correctly.

`
    
    private lateinit var billingDataSource: BillingDataSource

    @MockK
    private lateinit var billingClient: BillingClient

    @MockK
    private lateinit var productDetailsParams: QueryProductDetailsParams

    @BeforeEach
    fun onBefore() {
        MockKAnnotations.init(this)
        mockkStatic(BillingClient::queryProductDetails)
        billingDataSource = BillingDataSource(billingClient = billingClient)
    }

    @AfterEach
    fun onAfter() {
        unmockkAll()
    }

    @Test
    fun `Given Any ProductDetailsParams When getBillingProductDetails Then BillingClient Call queryProductDetails`() {
        val productsDetailsResult = mockk<ProductDetailsResult> { every { productDetailsList } returns mockk() }
        runTest {
            //Given
            coEvery { billingClient.queryProductDetails(any()) } returns productsDetailsResult

            //When
            billingDataSource.getBillingProductDetails(productDetailsParams = productDetailsParams)

            //Then
            coVerify(exactly = 1) { billingClient.queryProductDetails(any()) }
        }
    }
   
`
