### ISSUE TITLE
getProperty in 'every' block calls error "make sure the object inside the block is a mock"

### ISSUE THREAD

**Issue by antailyaqwer** [mockk/mockk#779]
### Prerequisites

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Expected Behavior
according to documentation, using getProperty() to get access to private property can mock this property. 
```
val mock = mockk<MyClass>()

every { mock getProperty "field" } returns 0
```

### Current Behavior

calls an error
`
Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
`

#### Steps to Reproduce

1. create mock or spy
2. try to get private property
3. code fails

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.2
* OS: Manjaro OS, linux 5.10.
* Kotlin version: 1.5.31
* JDK version: 11 (Android Studio embedded)
* JUnit version: 4.13.2
* Type of test: unit test 

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------
Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
	at app//io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
	at app//io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
	at app//io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
	at app//io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:64)
	at app//io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at app//io.mockk.MockKDsl.internalEvery(API.kt:93)
	at app//io.mockk.MockKKt.every(MockK.kt:98)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

**Comment by VickyBox** [comment]
I have the same problem, because of the Kotlin version.  In lower version, this problem never appears
