### ISSUE TITLE
Error mocking Kotlin static methods

### ISSUE THREAD

**Issue by RodrigoAmaroEng** [mockk/mockk#78]
Given two classes one written in Java and the other one exactly the same but converted to Kotlin (using the tool provided by Android Studio):

**Java Class**
```
public class StaticTest {
    static String test() {
        return "";
    }
}
```

**Kotlin Class**
```
object StaticTest {
    internal fun test(): String {
        return ""
    }
}
```

I get the expected behavior using the following code to mock the Java version, but it do not work with the Kotlin version:

```
staticMockk<StaticTest>().mock()
every { StaticTest.test() } returns "2"
```

It fails with 

> io.mockk.MockKException: Missing calls inside every { ... } block.
> 	at io.mockk.impl.recording.states.StubbingState.checkMissingCalls(StubbingState.kt:14)
> 	at io.mockk.impl.recording.states.StubbingState.recordingDone(StubbingState.kt:8)
> 	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:42)
> 	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:48)
> 	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)

#### Context

* MockK version:  1.8
* OS: Kubuntu 18.04
* Kotlin version: 1.2.41
* JDK version: 1.8.0_721
* Type of test: Unit test

**Comment by oleksiyp** [comment]
This happens because converted Kotlin code is not totally same code in terms of Java.
Anyway just replace `staticMockk` with `objectMockk`:

```
objectMockk(StaticTest).mock()
every { StaticTest.test() } returns "2"
```

**Comment by oleksiyp** [comment]
Dont use `::class`: `objectMockk(JavaStaticClass).mock()`

ср, 30 мая 2018 г., 23:24 RodrigoAmaroEng <notifications@github.com>:

**Comment by oleksiyp** [comment]
Closing. This code should work:
```
class StaticMethodTest {

    @Test // Failed with Missing calls inside every { ... } block.
    fun mockKotlinStaticMethodUsingObjectMock() { 
        objectMockk(KotlinStaticClass).mock()
        every { KotlinStaticClass.test() } returns "2"
        objectMockk(KotlinStaticClass).unmock()
    }

    @Test // Passed
    fun mockJavaStaticMethodUsingObjectMock() {
        objectMockk(JavaStaticClass).mock()
        every { JavaStaticClass.test() } returns "2"
        objectMockk(JavaStaticClass).unmock()
    }

    @Test // Failed with Missing calls inside every { ... } block.
    fun mockKotlinStaticMethodUsingStaticMock() {
        staticMockk<KotlinStaticClass>().mock()
        every { KotlinStaticClass.test() } returns "2"
        staticMockk<KotlinStaticClass>().unmock()

    }

    @Test // Failed with io.mockk.MockKException: Bad recording sequence. State: StubbingState
    fun mockJavaStaticMethodUsingStaticMock() {
        staticMockk<JavaStaticClass>().mock()
        every { JavaStaticClass.test() } returns "2"
        staticMockk<JavaStaticClass>().unmock()
    }
}
```

**Comment by RodrigoAmaroEng** [comment]
Sorry for the delay, it worked thanks
