### ISSUE TITLE
Abstract class not receiving injected mocks

### ISSUE THREAD

**Issue by verissimor** [mockk/mockk#780]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

Forgive me If I missed something on the specs, but I haven't found how to inject mocks on abstract classes. Eg.:

```kotlin
class Make(val name: String)

abstract class Vehicle {
  private lateinit var make: Make
  abstract fun run()
  fun showMake() = println(make.name)
}

// Trying to mock Car
class Car : Vehicle() {
  override fun run() = println("run")
}
```

### Current Behavior

Whenever I run the following piece of code:

```kotlin
class MockErrorTest {
  @MockK
  lateinit var make: Make

  @InjectMockKs
  lateinit var car: Car

  @BeforeEach
  fun setup() = MockKAnnotations.init(this)

  @AfterEach
  fun tearDown() = clearAllMocks()

  @Test
  fun `should verify a valid token`() {
    every { make.name } returns "m1"
    car.run()
    car.showMake()
  }
}
```

I get the error `lateinit property make has not been initialized`

### Failure Information (for bugs)

I can't imagine how to mock it because `Vehicle.make` is a `private` field.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run the two pieces of code above.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.2
* OS: MacOS Big Sur
* Kotlin version: 212-1.6.10-release-923-IJ5457.46
* JDK version: 11.0.11.hs
* JUnit version: 
* Type of test: unit test

#### Failure Logs

Please include any relevant log snippets or files here.

#### Stack trace

```
// -----------------------[ YOUR STACK STARTS HERE ] -----------------------

kotlin.UninitializedPropertyAccessException: lateinit property make has not been initialized
	at com.gambi.authorization.service.user.Vehicle.showMake(MockErrorTest.kt:36)
	at com.gambi.authorization.service.user.MockErrorTest.should verify a valid token(MockErrorTest.kt:60)
// -----------------------[ YOUR STACK TRACE ENDS HERE ] -----------------------
```

**Comment by Raibaz** [comment]
I don't really understand this.

How is your `make` property being populated in your application?

**Comment by verissimor** [comment]
hello @Raibaz 

I simplified it to create an easy reproduction. In fact, I'm using spring and `make` is a `@Autowired lateinit var`.

I understand that I could use `springmockk` to apply those mocks, however, in that case, I would need to have a Spring Context, which makes the test slower. 

Anyway, if mockk doesn't support injecting mocks on abstract classes I think this is not a bug.

**Comment by Raibaz** [comment]
As you can see [here](https://github.com/mockk/mockk/blob/02a49b2f3639e066ff96d35a160bf301fe0bbb00/mockk/jvm/src/main/kotlin/io/mockk/impl/annotations/JvmMockInitializer.kt#L58), the injection is being executed only on `cls.memberProperties`, which does not include private properties from superclasses.

(Note that it includes protected properties though)

I don't even know if springmockk is able to achieve this.

Sorry about this :(

**Comment by LintaoAmons** [comment]
Met the same issue :(

**Comment by melbic** [comment]
I just hit the same issue. Could you please mark this as important?

**Comment by jlouis12** [comment]
I also hit this issue

**Comment by Aschraf** [comment]
This is a pretty annoying issue :(
