### ISSUE TITLE
Can't mock Path extension function

### ISSUE THREAD

**Issue by andrashatvani** [mockk/mockk#805]
## Please remove sections wisely

Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

### Expected Behavior

Path extension function can be mocked.

### Current Behavior

Defined behaviour won't be replayed.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.2
* OS: MacOS 12.3
* Kotlin version: 1.6.10
* JDK version: 17.0.1
* JUnit version: 5.8.2
* Type of test: unit test 

#### Minimal reproducible code (the gist of this issue)

```kotlin
@Test
fun `path does not exist`() {
        mockkStatic("kotlin.io.path.PathsKt__PathUtilsKt")
        val nonExistentPath: Path = mockk(relaxed = true)
        every { nonExistentPath.exists() } returns false
        assertThat(nonExistentPath.exists()).isFalse
}
```

**Comment by Raibaz** [comment]
`Path.exists` is defined as online, so sadly, it's not mockable.
