### ISSUE TITLE
mockk-agent-android 1.12.4 missing native lib

### ISSUE THREAD

**Issue by rlatapy-luna** [mockk/mockk#819]
### Expected Behavior

`libmockkjvmtiagent.so` lib embedded in aar like before

### Current Behavior

No lib -> `This error occured due to an I/O error during the creation of this agent: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found`

![image](https://user-images.githubusercontent.com/45555889/168114194-0cf5d477-f724-477e-b66b-ec3517430aa2.png)

#### Steps to Reproduce

- Import 1.12.4
- Try to use Mockk

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.4
* Type of test: android instrumented test

#### Stack trace

```
Caused by: io.mockk.proxy.MockKAgentException: MockK could not self-attach a jvmti agent to the current VM. This feature is required for inline mocking.
This error occured due to an I/O error during the creation of this agent: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found

Potentially, the current VM does not support the jvmti API correctly
at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:67)
at io.mockk.impl.JvmMockKGateway.<init>(JvmMockKGateway.kt:46)
at io.mockk.impl.JvmMockKGateway.<clinit>(JvmMockKGateway.kt:186)
... 33 more
Caused by: java.io.IOException: Unable to dlopen libmockkjvmtiagent.so: dlopen failed: library "libmockkjvmtiagent.so" not found
at dalvik.system.VMDebug.nativeAttachAgent(Native Method)
at dalvik.system.VMDebug.attachAgent(VMDebug.java:572)
at android.os.Debug.attachJvmtiAgent(Debug.java:2563)
at io.mockk.proxy.android.JvmtiAgent.<init>(JvmtiAgent.kt:48)
at io.mockk.proxy.android.AndroidMockKAgentFactory.init(AndroidMockKAgentFactory.kt:40)
... 35 more
```

#### Minimal reproducible code (the gist of this issue)

```kotlin
mockk()
```

**Comment by rekaszeru** [comment]
I'm facing the same issue when running instrumented tests with mockk 1.12.4. 
[Gradle wrapper v7.4.2 / AGP v7.2.0] 

Any workaround or update will be much appreciated!

**Comment by SimonMarquis** [comment]
Can you check the list of tasks that are executed when you do the publish (`--dry-run` maybe)?
Is the Gradle log showing any warning/error?
Is the .so file compiled and does it exist in the /build directory after the publish task?

**Comment by kloverde** [comment]
I think this warrants either withdrawing the 1.12.4 release or putting warnings on the website, the readme, etc.  It isn't mentioned in the "Known Issues" section that this release is partially broken.

**Comment by SimonMarquis** [comment]
Back to normal with the latest release: https://github.com/mockk/mockk/releases/tag/1.12.5

**Comment by gerardoepitacio** [comment]
Is it asking me to update to Kotlin v1.7? this error happen when I updated from v1.12.0 to v1.12.5 of Mockk library.

jetified-mockk-common-1.12.5.jar!/META-INF/mockk-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
jetified-mockk-dsl-1.12.5.jar!/META-INF/mockk-dsl.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.

**Comment by mironoff2007** [comment]
Same aerror in android test 

library "libmockkjvmtiagent.so" not found

//Mockk
    ext.mockk_version = "1.13.8"
    testImplementation "io.mockk:mockk:$mockk_version"
    testImplementation "io.mockk:mockk-agent:$mockk_version"
    androidTestImplementation "io.mockk:mockk-android:$mockk_version"
    androidTestImplementation "io.mockk:mockk-agent:$mockk_version"

https://github.com/mironoff2007/news-app/tree/mockk_android_test

**Comment by mironoff2007** [comment]
helped me

testOptions {
        packagingOptions {
            jniLibs {
                useLegacyPackaging = true
            }
        }
    }

**Comment by Pugramming** [comment]
Got this same problem.

Running the instrumented tests on a real device, instead of using an emulator, worked for me.

**Comment by uiltonjose** [comment]
> Got this same problem.
> 
> Running the instrumented tests on a real device, instead of using an emulator, worked for me.

Got this same problem. Using version 1.13.12

I got the error even when using a real device.
