### ISSUE TITLE
[Feature Request] Enhance CapturingSlot by captured log

### ISSUE THREAD

**Issue by qoomon** [mockk/mockk#827]
```kotlin
inline fun <reified T : Any> slot() = CapturingSlot<T>()

class CapturingSlot<T : Any> private constructor(private val captureList: MutableList<T>) :
    MutableList<T> by captureList {
    constructor() : this(mutableListOf())

    val captured: T
        get() = captureList.last()

    override fun toString(): String =
        if (captureList.isEmpty()) "slot()"
        else captureList.joinToString("\n") { "slot($it)" }
}
```

**Comment by Raibaz** [comment]
I don't understand: why would this be better than using a `mutableList<T>` to capture arguments, which can already be done?

**Comment by qoomon** [comment]
Because both single and multi slots have types and a `slot<>()` method. That would increase readability

**Comment by Raibaz** [comment]
I still don't understand, `MutableList`s have types as well.

Can you please provide an example of the same thing achieved with a `MutableList<T>` and a `ListCapturingSlot<T>`, to help me understand?

Thanks :)

**Comment by qoomon** [comment]
In my opinion it is easy to read if you know it is a variable of type Slot instead of an ordinary list. Feature wise it will not add a new feature, it just add a Slot type that acts like a normal slot and can be used as a multi slot as well.

**Comment by Raibaz** [comment]
I see. 

Perhaps just using a `typealias MultiSlot<T> = MutableList<T>` would be fine then?

**Comment by qoomon** [comment]
I'll close this issue and go for the alias solution and own `slot` function.
