### ISSUE TITLE
coVerifySequence() and coVerifyAll() skip method calls

### ISSUE THREAD

**Issue by KaplunSergey** [mockk/mockk#839]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

`coVerifySequence()` and `coVerifyAll()` skip method call check in my case.

### Current Behavior

When I tried to cover my ViewModel with tests I found a problem. I have a function and inside this function I call some methods. But when I try to use `coVerifySequence()` and `coVerifyAll()` to check that my functions is called, I see that verify check skips some function call(that used inside the function being checked) and my test is passes. I will provide an example of code below

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run test with all the necessary method calls inside `coVerifySequence()` or `coVerifyAll()`;
2. See successful result;
3. Remove one of the method calls from verify block and run test again;
4. See successful result.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.4
* OS: Mac Os Monterey 12.4
* Kotlin version: 1.6.21
* JDK version: 11
* JUnit version: 4.13.2
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.mockk.coEvery
import io.mockk.coVerifySequence
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.TestCoroutineDispatcher
import kotlinx.coroutines.test.TestCoroutineScope
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.setMain
import org.junit.Test

import org.junit.Rule
import org.junit.rules.TestWatcher
import org.junit.runner.Description

class ExampleUnitTest {

    private val dispatcher = TestCoroutineDispatcher()

    @get:Rule
    val mainCoroutineRule = MainCoroutineRule(dispatcher)

    @Test
    fun addition_isCorrect() {
        val first = mockk<MyFirstObj>()
        val second = mockk<MySecondObj>()
        val third = mockk<MyThirdObj>()
        val myViewModel = MyVM(first, second, third)

        every { first.doWork() } returns Unit
        coEvery { second.getData() } returns "123"
        coEvery { third.getData() } returns "123"

        myViewModel.onCreate()

        coVerifySequence {
            first.doWork()
            second.getData()
            third.getData()
        }
    }

    class MyVM(private val first: MyFirstObj, private val second: MySecondObj, private val third: MyThirdObj) : ViewModel() {

        lateinit var data1: String
        lateinit var data2: String

        fun onCreate() {
            viewModelScope.launch {
                first.doWork()
                data1 = second.getData()
                data2 = third.getData()
            }
        }
    }

    class MyFirstObj {
        fun doWork() {
            println("Do Work")
        }
    }

    class MySecondObj {
        suspend fun getData(): String {
            delay(100)
            return "123"
        }
    }

    class MyThirdObj {
        suspend fun getData(): String {
            delay(100)
            return ""
        }
    }
}

@ExperimentalCoroutinesApi
class MainCoroutineRule(val dispatcher: TestCoroutineDispatcher) :
    TestWatcher(),
    TestCoroutineScope by TestCoroutineScope(dispatcher) {
    override fun starting(description: Description?) {
        super.starting(description)
        Dispatchers.setMain(dispatcher)
    }

    override fun finished(description: Description?) {
        super.finished(description)
        cleanupTestCoroutines()
        Dispatchers.resetMain()
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

When I run test I see successful result. It is correct. But when I removed one method call from verify block(for example - `second.getData()`), I see also successful result. Maybe I don't understand something, but I think this code should work. Can you help me?

P.S. I also tried `StandardTestDispatcher` and I had the same result

**Comment by Raibaz** [comment]
`coVerifySequence` and `coVerifyAll` are not the right methods for your use case: as [the doc](https://mockk.io/#top-level-functions) states, 

* `coVerifyAll` starts a verification block that should include all calls
* `coVerifySequence` starts a verification block that checks whether all calls were made in a specified sequence for coroutines

Basically, they both only verify that the methods inside the verification block have been executed; they don't specify anything about methods that are _not_ in the verification block.

To achieve the behavior you are describing, you should use `checkUnnecessaryStub(first, second, third)`, which will make sure that all your stubbed methods have been called at least once.

Does this make sense?

**Comment by KaplunSergey** [comment]
Yes, it makes sense. Apparently I misunderstood the functionality. Thanks

**Comment by KaplunSergey** [comment]
@Raibaz I have one question. I can't find `checkUnnecessaryStub()` in code. Where I can find this method?
