### ISSUE TITLE
More than one file was found with OS independent path ‘META-INF/main.kotlin_module’

### ISSUE THREAD

**Issue by GAumala** [mockk/mockk#84]
Below information is actually needed to make all the process of fixing faster.
Choose main points. Don't blindly follow this as a set of rules. 
Don't waste much time. Usually, the main thing is to have a good reproducible minimal code.

### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I expect to be able to run instrumentation tests with mockk

### Current Behavior

Everything seems to compile correctly, but when I want to run the instrumentation test on an actual device I get an error before launching the tests.

I think there something wrong with the 1.8+ android builds, the `META-INF/main.kotlin_module` file conflicting. This issue doesn't happen with unit tests or instrumentation tests on older versions though, I get a runtime error instead on android instrumentation tests.

### Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Run instrumentation tests on an android device in a project that declares multiple files at `META-INF/main.kotlin_module`.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.8 and 1.8.1
* OS: Arch Linux
* Kotlin version: 1.2.41
* JDK version: java-8-openjdk
* Type of test: android instrumented test

#### Failure Logs

```
Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformResourcesWithMergeJavaResForDebugAndroidTest'.
> More than one file was found with OS independent path 'META-INF/main.kotlin_module'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

**Comment by oleksiyp** [comment]
Thanks for report. Will check tomorrow(going to bed now)

**Comment by oleksiyp** [comment]
First thing.

Putting
```
    packagingOptions {
        exclude 'META-INF/main.kotlin_module'
    }

```
to `android` tag in build.gradle should help

https://stackoverflow.com/questions/44509608/duplicate-files-copied-in-apk-meta-inf-library-release-kotlin-module

Second will probably eliminate this issue in todays 1.8.2 release

**Comment by GAumala** [comment]
That did help. Thanks!
