### ISSUE TITLE
Feature: ofType() may be reified or somehow more friendly

### ISSUE THREAD

**Issue by oleksiyp** [mockk/mockk#88]
Hi, I would like to mock in a more concise way. Especially, as far as matchers are considered.
Previously, we have used the Spock, so below I give you the Spock version as a comparison.

If I understand correctly to match any value of a given type I have to use the ofType function.
And the ofType takes a KClass as an argument.
Here lies my problem:
I can write:
Action::class
but I cant write:
Action<in RequestSpec>::class
so I have to use explicit unchecked cast and this generates compiler warning:
ofType( Action::class as KClass<Action<in RequestSpec>> )
Also, this is very long.

I have created an example extension function to hide the cast.

My question is:
Can you provide any more concise way to provide the matchers?
Preferably, something similar to my arg() extension function, although I am not sure whether my function is good.

Examples:
```
// Mockk (original):
every { mockHttpClient.request(
  ofType(URI::class),
  ofType(Action::class as KClass<Action<in RequestSpec>>)) } // Action <? super RequestSpec>
  .returns (Promise.value(mockResponse))

every { mockObjectMapper.readValue(
  ofType(String::class),
  ofType(Class::class as KClass<Class<HcmProfileHolder>>)) } // Class<HcmProfileHolder>
  .returns (profileHolder)

// Mockk with extension function arg()
every { mockHttpClient.request(
  arg<URI>(),
  arg<Action<in RequestSpec>>() ) } // Action <? super RequestSpec>
  .returns (Promise.value(mockResponse))

every { mockObjectMapper.readValue(
  arg<String>(),
  arg<Class<HcmProfileHolder>>()) } // Class<HcmProfileHolder>
  .returns (profileHolder)

inline fun <reified T : Any> MockKMatcherScope.arg(): T {
    return ofType(T::class)
}

// Spock (Groovy):
mockHttpClient.request(*_) >> Promise.value(mockResponse())
mockObjectMapper.readValue(_ as Str
```

**Comment by orfeonomia** [comment]
Some parts of text disappeared due to markdown problems.

can write:
` Action::class `
can't write:
` Action<in RequestSpec>::class `
have to use explicit unchecked cast (as below) and this generates compiler warning:
` ofType( Action::class as KClass<Action<in RequestSpec>> ) `
