### ISSUE TITLE
Nested Spy not working

### ISSUE THREAD

**Issue by qoomon** [mockk/mockk#881]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I expect following test to fail, but it doesn't.
```kotlin
data class Dummy(val foo: Int)

@Test
fun `verify on nexted spy object`() {
    // given
    val dummy = spyk(Dummy(foo = 42))

    // given
    dummy.foo

    // then
    verify {
        dummy.foo
        dummy.foo.toLong()
    }
}
```
 
### Current Behavior

Test is passing.

#### Context

* MockK version: 1.12.5
* OS: MacOs
* Kotlin version: 1.7
* JDK version: 11
* JUnit version: 5.9.0
* Type of test: unit test

**Comment by Raibaz** [comment]
I don't really understand this - can you provide an example closer to a real world scenario?

If that was the case, I'd just say that spying on a data class is not a good idea, but I suspect you encountered the issue in a more complex context :)

**Comment by qoomon** [comment]
@Raibaz I totally agree it is not a common scenario, maybe there is a better totally different solution for my purpose.

I want to use a spy to test my mapping methods.

Let's say I have an object A with a nested other object B.

If I call my extension function `.toDTO()` on object A, I want to verify that all getter methods are called or used.
The verify should fail incase a field was not used during mapping (except field was excluded explicitly).  Currently I see no way to refactor following very method to work in a recursive way on nested objects.

```kotlin
fun <T : Any> verifyAllPropertyGetters(obj: T, vararg except: KProperty1<T, *>) {
    verify {
        obj::class.memberProperties
            .filter { it !in except }
            .forEach { obj.getProperty(it.name) }
    }
}
```

**Comment by Raibaz** [comment]
Ah, I see what you mean now, thanks a lot for clarifying.

It's an interesting case indeed: I think rather than verifying that all getters were called, you may want to check that after calling `.toDTO()` all the properties in your DTO have the same values as the original object

(I'm assuming `toDTO` does not do any conversion here)

It should be possible to design a generic way to compare your DTO and your original object by using reflection, so that if you add a property to your class and your DTO the test should automatically check its equality without requiring a change, but that depends on how your `.toDTO()` function works.

Generally speaking though, I'd rather assert that the DTO values are what I expect them to be after calling `.toDTO()` rather than verifying that the getters were called.

This being said, do you really need the getter verification to recurse and go inside nested objects? 

Why is verifying that getters were called only on the first level not enough?

(Apologies if I was a bit too abstract and philosophical)

**Comment by qoomon** [comment]
There is really no need for apologies :-). 

My test idea is as follow:
* call `sourceObject.toDTO()`
* compare the resulting DTO fields with expected values
* verify all field getter from the `sourceObject` were called. 
  * this ensures a failing test, if a new field is added to `SourceObject` class

A deep spy would allow to recursively check, if all getters of all levels have been used (or explicitly excluded) during mapping to DTO.

Maybe there a better methods to archive what I want, however that's the best I came up with :-)

The need of this kind of tests are caused by clean architecture. It's a real nice and clean approach to structure your project source code. The only drawback is you have to or should map your objects between layers to keep them independent. The mapping can be error-prone if you add new fields. For example: if you add a new optional field to a domain object in your core application package all mapping unit tests will still pass.

**Comment by qoomon** [comment]
And thanks a lot for your time to talk about this special use case.

**Comment by Raibaz** [comment]
>   * this ensures a failing test, if a new field is added to `SourceObject` class

Is this not already ensured by comparing the resulting DTO fields with the expected values?

And also, does adding a new field to the `SourceObject` class automatically require that the same field is added to the DTO?

I'm still very convinced that the only thing you should be testing in a `.toDTO()` function is that the values in your DTO are the ones you expect them to be, and in this case testing the behavior of the `sourceObject` is a bit overkill.

**Comment by qoomon** [comment]
Probably your are right, however it would be nice to have an option to produce deep spies.

**Comment by Raibaz** [comment]
I don't know, that sounds a bit confusing to me.

I admit I'm not a big fan of spies, but the need for a deep spy feels a bit like a code smell to me, a symptom that you may be overtesting the internal behavior of your class when you may just need to test its outcome, or that your design is a bit too tightly coupled.

What do you think?

**Comment by qoomon** [comment]
Ok you convinced me 😄 and thanks for the discussion.
