### ISSUE TITLE
No class files in io.mockk:mockk:1.12.6 or  io.mockk:mockk:1.12.7.

### ISSUE THREAD

**Issue by bbain** [mockk/mockk#891]
Please answer the following questions for yourself before submitting an issue.

- [ /] I am running the latest version
- [ /] I checked the documentation and found no answer
- [ /] I checked to make sure that this issue has not already been filed

### Expected Behavior

There are classes in the jar files.

### Current Behavior

There are no classes in the jars. Not possible to compile against the library.

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.12.6 or 1.12.7
* OS: MacOS
* Kotlin version: 1.7.10
* JDK version: 11
* JUnit version: 5 
* Type of test: unit test

**Comment by alvindizon** [comment]
Did you also get this error? `Could not find io.mockk:mockk-jvm:1.12.6`? Our project also cannot use this update because of this error

**Comment by bbain** [comment]
I cold see the jar file though it may have been on our maven proxy. The actual problem is when trying to compile I get:

```
Unresolved reference: mockk
....
```
Because the `jar` itself is empty.

**Comment by stefanzilske** [comment]
Same here, already reported yesterday for 1.12.6 in #884. Seems not to be resolved with 1.12.7.

**Comment by aSemy** [comment]
Are you using Maven? Might be the same issue as 
https://github.com/mockk/mockk/issues/889#issuecomment-1224286127

**Comment by bbain** [comment]
So we are using maven. This fails:

```
<dependency>
    <groupId>io.mockk</groupId>
    <artifactId>mockk</artifactId>
    <version>1.12.7</version>
    <scope>test</scope>
</dependency>
```

Changing it to something like this works:

```
<dependency>
    <groupId>io.mockk</groupId>
    <artifactId>mockk-jvm</artifactId>
    <version>1.12.7</version>
    <exclusions>
        <exclusion>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </exclusion>
    </exclusions>
    <scope>test</scope>
</dependency>
```

Are we meant to now depend on `mockk-jvm` directly?

**Comment by Raibaz** [comment]
Yes, if you use maven you need to depend on `mockk-jvm` rather than `mockk` because maven does not understand multiplatform projects.

I think this should be added to the docs, in fact.

**Comment by aSemy** [comment]
> ```xml
> <dependency>
>     <groupId>io.mockk</groupId>
>     <artifactId>mockk-jvm</artifactId>
>     <version>1.12.7</version>
>     <exclusions>
>         <exclusion>
>             <groupId>junit</groupId>
>             <artifactId>junit</artifactId>
>         </exclusion>
>     </exclusions>
>     <scope>test</scope>
> </dependency>
> ```

Hmm you shouldn't need to exclude JUnit. If it is necessary, then I think that's something that should be fixed, if possible.

**Comment by bbain** [comment]
> Hmm you shouldn't need to exclude JUnit. If it is necessary, then I think that's something that should be fixed, if possible.

Sorry. My project has a check that JUnit 4 does not get included as a transitive dep. I'm sure it would work without this exclude.
