### ISSUE TITLE
Release 1.12.6 and 1.12.7 jars are empty on Maven Central

### ISSUE THREAD

**Issue by m-rm** [mockk/mockk#896]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

The jar files should contain files other than META-INF.

### Current Behavior

They do not, which causes the tests to fail because the classes can't be found.

#### Steps to Reproduce

1. Download https://repo1.maven.org/maven2/io/mockk/mockk/1.12.7/mockk-1.12.7.jar or https://repo1.maven.org/maven2/io/mockk/mockk/1.12.6/mockk-1.12.6.jar
2. Examine contents with 7Zip or similar

#### Context

* MockK version: 1.12.6, 1.12.7

**Comment by jeromewaibel** [comment]
See [this comment](https://github.com/mockk/mockk/issues/891#issuecomment-1225373782).

**Comment by m-rm** [comment]
Thank you. README.md should be changed since it still contains the following example for Maven:
```
<dependency>
    <groupId>io.mockk</groupId>
    <artifactId>mockk</artifactId>
    <version>{version}</version>
    <scope>test</scope>
</dependency>
```
