### ISSUE TITLE
mockk-jvm:1.12.6 is missing the POM in mavenCentral()

### ISSUE THREAD

**Issue by TWiStErRob** [mockk/mockk#897]
### Expected Behavior

`testImplementation("io.mockk:mockk:1.12.6")` just works

### Current Behavior

I'm getting the same as with mockk-jvm:
```
Execution failed for task ':test:internal:compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':test:internal:compileKotlin'
   > Could not resolve all files for configuration ':test:internal:compileClasspath'.
      > Could not find io.mockk:mockk-jvm:1.12.6.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/io/mockk/mockk-jvm/1.12.6/mockk-jvm-1.12.6.pom
          - https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.6/mockk-jvm-1.12.6.pom
          - https://repo.gradle.org/gradle/libs-releases-local/io/mockk/mockk-jvm/1.12.6/mockk-jvm-1.12.6.pom
        Required by:
            project :test:internal > io.mockk:mockk:1.12.6
```

### Failure Information (for bugs)

Have a look at https://repo.maven.apache.org/maven2/io/mockk/mockk-jvm/1.12.6/

#### Context

* MockK version: 1.12.6

Note: 1.12.7 works, so maybe just leave a note in [releases](https://github.com/mockk/mockk/releases/tag/1.12.6) that this is broken?

Similar issues: #883 #891 #892

**Comment by aSemy** [comment]
Updating the release notes is a good idea.

This will never work though:

> `testImplementation("io.mockk:mockk:1.12.6")` just works

There's no way to change something once it's published to Maven Central.

**Comment by Raibaz** [comment]
Good point, I updated the release notes.

I think this can be closed though.

**Comment by TWiStErRob** [comment]
@aSemy I've been using it like this forever...
```
[versions]
mockk = "1.12.7"
[libraries]
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
```
\+
```
testImplementation(libs.mockk)
```
