### ISSUE TITLE
Missing transitive dependencies for Android tests

### ISSUE THREAD

**Issue by SimonMarquis** [mockk/mockk#903]
### Expected Behavior

Compilation should just work with the default gradle/maven setup:

```groovy
androidTestImplementation "io.mockk:mockk-android:1.12.7"
androidTestImplementation "io.mockk:mockk-agent-jvm:1.12.7"
```

Source: https://mockk.io/#gradlemaven-dependency

### Current Behavior

The public mockk dsl is not available for the `androidTest` configuration: `io.mockk.mockk`, `io.mockk.verify`

Though it is available for the regular `test` configuration when adding dependencies with `testImplementation`.

---

Here are the resolved dependencies: (I removed all non-mockk dependencies for clarity)

- `gradlew dependencies --configuration debugAndroidTestCompileClasspath`
  ```
  debugAndroidTestCompileClasspath - Compile classpath for compilation 'debugAndroidTest' (target  (androidJvm)).
  +--- io.mockk:mockk-android:1.12.7
  +--- io.mockk:mockk-agent-jvm:1.12.7
  |    +--- io.mockk:mockk-agent-api:1.12.7
  |         \--- io.mockk:mockk-agent-api-jvm:1.12.7
  +--- io.mockk:mockk-android:{strictly 1.12.7} -> 1.12.7 (c)
  +--- io.mockk:mockk-agent-jvm:{strictly 1.12.7} -> 1.12.7 (c)
  +--- io.mockk:mockk-agent-api:{strictly 1.12.7} -> 1.12.7 (c)
  \--- io.mockk:mockk-agent-api-jvm:{strictly 1.12.7} -> 1.12.7 (c)
  ```

- `gradlew dependencies --configuration debugAndroidTestRuntimeClasspath`
  ```
  debugAndroidTestRuntimeClasspath - Runtime classpath of compilation 'debugAndroidTest' (target  (androidJvm)).
  +--- io.mockk:mockk-android:1.12.7
  |    +--- io.mockk:mockk:1.12.7
  |    |    \--- io.mockk:mockk-jvm:1.12.7
  |    |         +--- io.mockk:mockk-dsl:1.12.7
  |    |         |    \--- io.mockk:mockk-dsl-jvm:1.12.7
  |    |         +--- io.mockk:mockk-agent:1.12.7
  |    |         |    \--- io.mockk:mockk-agent-jvm:1.12.7
  |    |         |         +--- io.mockk:mockk-agent-api:1.12.7
  |    |         |              \--- io.mockk:mockk-agent-api-jvm:1.12.7
  |    |         \--- io.mockk:mockk-agent-api:1.12.7 (*)
  |    +--- io.mockk:mockk-agent-api:1.12.7 (*)
  |    +--- io.mockk:mockk-agent-android:1.12.7
  |         +--- io.mockk:mockk-agent-api:1.12.7 (*)
  |         \--- io.mockk:mockk-agent:1.12.7 (*)
  \--- io.mockk:mockk-agent-jvm:1.12.7 (*)
  ```

---

It seems that the `io.mockk:mockk` artifact is not part of the compilation classpath, but only a runtime dependency.

**Comment by SimonMarquis** [comment]
Also, quick question, what was the reason to not make it is there a reason to not make `io.mockk:mockk-agent-jvm` an explicit transitive dependency of `io.mockk:mockk-android`? This would simplify the setup process and require only a single dependency.

**Comment by SimonMarquis** [comment]
The [pom.xml](https://repo1.maven.org/maven2/io/mockk/mockk-android/1.12.7/mockk-android-1.12.7.pom) contains only `runtime` dependencies:

```xml
<project>
  <!--  ...  -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.mockk</groupId>
  <artifactId>mockk-android</artifactId>
  <version>1.12.7</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
      <version>1.7.10</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk</artifactId>
      <version>1.12.7</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-agent-api</artifactId>
      <version>1.12.7</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk-agent-android</artifactId>
      <version>1.12.7</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-coroutines-core</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

Whereas [1.12.5](https://repo1.maven.org/maven2/io/mockk/mockk-android/1.12.5/mockk-android-1.12.5.pom) as a compile dependency on `io.mockk:mockk:1.12.5`

```xml
<project>
  <!-- ... -->
  <dependencies>
    <dependency>
      <groupId>io.mockk</groupId>
      <artifactId>mockk</artifactId>
      <version>1.12.5</version>
      <scope>compile</scope>
      <!-- ... -->
    </dependency>
    <!-- ... -->
</project>
```

**Comment by SimonMarquis** [comment]
I remember a long time ago having to re-write scopes from the generated pom, but this should not be necessary anymore.

I've tested replacing

https://github.com/mockk/mockk/blob/fe36b92f89434f81fab2ef51cd8def5d2841ee14/modules/mockk-android/build.gradle.kts#L34-L36

with

```kotlin
api(projects.modules.mockk)
api(projects.modules.mockkAgentApi)
api(projects.modules.mockkAgentAndroid)
```

And the generated pom.xml contains the right `compile` scope 🤷 

<html>
<body>
<table class=" wide" id="be2abc80" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: var(--rs-text-2-font-size,16px); line-height: var(--rs-text-2-line-height,24px); font-family: var(--rs-font-family-ui,var(--rs-font-family-jb-sans,&quot;JetBrains Sans&quot;,Inter,system-ui,-apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Roboto,Oxygen,Ubuntu,Cantarell,&quot;Droid Sans&quot;,&quot;Helvetica Neue&quot;,Arial,sans-serif)); vertical-align: baseline; border-collapse: unset; border-spacing: 0px; letter-spacing: 0.0015em; clear: left; width: 681px; text-align: left; color: var(--wh-color-text-main);"><thead style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: var(--wh-color-text-main);"><tr class="ijRowHead" id="da531625" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><th id="c1872a7d" style="margin: 0px; padding: 16px 32px 16px 0px; border: 0px; font: inherit; vertical-align: top;"><p class="article__p child" style="margin-top: 0px !important; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">Type</p></th><th id="8fd58d2d" style="margin: 0px; padding: 16px 32px 16px 0px; border: 0px; font: inherit; vertical-align: top;"><p class="article__p child" style="margin-top: 0px !important; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">Description</p></th><th id="99e1e357" style="margin: 0px; padding: 16px 0px; border: 0px; font: inherit; vertical-align: top;"><p class="article__p child" style="margin-top: 0px !important; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">When to use</p></th></tr></thead><tbody style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><tr class="" id="585791a3" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><td id="65e13ea6" style="margin: 0px; padding: 16px 32px 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;"><code class="code " style="margin: 0px; padding: 2px 6px; border: 0px; font-style: inherit; font-variant-ligatures: none; font-variant-caps: inherit; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: inherit; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: var(--rs-font-family-mono,&quot;JetBrains Mono&quot;,SFMono-Regular,Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace); vertical-align: baseline; box-sizing: border-box; display: inline; border-radius: 3px; word-break: normal; color: var(--wh-color-text-main); background-color: var(--wh-color-backlight-main);">api</code></p></td><td id="14221d62" style="margin: 0px; padding: 16px 32px 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">Used both during compilation and at runtime and is exported to library consumers.</p></td><td id="e31711c" style="margin: 0px; padding: 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">If any type from a dependency is used in the public API of the current module, use an<span> </span><code class="code " style="margin: 0px; padding: 2px 6px; border: 0px; font-style: inherit; font-variant-ligatures: none; font-variant-caps: inherit; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: inherit; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: var(--rs-font-family-mono,&quot;JetBrains Mono&quot;,SFMono-Regular,Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace); vertical-align: baseline; box-sizing: border-box; display: inline; border-radius: 3px; word-break: normal; color: var(--wh-color-text-main); background-color: var(--wh-color-backlight-main);">api</code><span> </span>dependency.</p></td></tr><tr class="" id="456bfe61" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><td id="ffc321e0" style="margin: 0px; padding: 16px 32px 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;"><code class="code " style="margin: 0px; padding: 2px 6px; border: 0px; font-style: inherit; font-variant-ligatures: none; font-variant-caps: inherit; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: inherit; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: var(--rs-font-family-mono,&quot;JetBrains Mono&quot;,SFMono-Regular,Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace); vertical-align: baseline; box-sizing: border-box; display: inline; border-radius: 3px; word-break: normal; color: var(--wh-color-text-main); background-color: var(--wh-color-backlight-main);">implementation</code></p></td><td id="8e41095" style="margin: 0px; padding: 16px 32px 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">Used during compilation and at runtime for the current module, but is not exposed for compilation of other modules depending on the one with the `implementation` dependency.</p></td><td id="efd03b9a" style="margin: 0px; padding: 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p id="689ccf6c" class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">Use for dependencies needed for the internal logic of a module.</p><p id="86d7b3c6" class="article__p child" style="margin: 12px 0px 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">If a module is an endpoint application which is not published, use<span> </span><code class="code " style="margin: 0px; padding: 2px 6px; border: 0px; font-style: inherit; font-variant-ligatures: none; font-variant-caps: inherit; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: inherit; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: var(--rs-font-family-mono,&quot;JetBrains Mono&quot;,SFMono-Regular,Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace); vertical-align: baseline; box-sizing: border-box; display: inline; border-radius: 3px; word-break: normal; color: var(--wh-color-text-main); background-color: var(--wh-color-backlight-main);">implementation</code><span> </span>dependencies instead of<span> </span><code class="code " style="margin: 0px; padding: 2px 6px; border: 0px; font-style: inherit; font-variant-ligatures: none; font-variant-caps: inherit; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: inherit; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: var(--rs-font-family-mono,&quot;JetBrains Mono&quot;,SFMono-Regular,Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace); vertical-align: baseline; box-sizing: border-box; display: inline; border-radius: 3px; word-break: normal; color: var(--wh-color-text-main); background-color: var(--wh-color-backlight-main);">api</code><span> </span>dependencies.</p></td></tr><tr class="" id="97bfdd7e" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><td id="b01b0981" style="margin: 0px; padding: 16px 32px 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;"><code class="code " style="margin: 0px; padding: 2px 6px; border: 0px; font-style: inherit; font-variant-ligatures: none; font-variant-caps: inherit; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: inherit; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: var(--rs-font-family-mono,&quot;JetBrains Mono&quot;,SFMono-Regular,Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace); vertical-align: baseline; box-sizing: border-box; display: inline; border-radius: 3px; word-break: normal; color: var(--wh-color-text-main); background-color: var(--wh-color-backlight-main);">compileOnly</code></p></td><td id="b85f1547" style="margin: 0px; padding: 16px 32px 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">Used for compilation of the current module and is not available at runtime nor during compilation of other modules.</p></td><td id="43c9a237" style="margin: 0px; padding: 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font: inherit; vertical-align: top;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">Use for APIs which have a third-party implementation available at runtime.</p></td></tr><tr class="" id="d77b21f1" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><td id="15a9f78d" style="margin: 0px; padding: 16px 32px 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;JetBrains Sans&quot;, Inter, system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; vertical-align: top; color: rgb(25, 25, 28); letter-spacing: 0.024px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;"><code class="code " style="margin: 0px; padding: 2px 6px; border: 0px; font-style: inherit; font-variant-ligatures: none; font-variant-caps: inherit; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: inherit; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: var(--rs-font-family-mono,&quot;JetBrains Mono&quot;,SFMono-Regular,Consolas,&quot;Liberation Mono&quot;,Menlo,Courier,monospace); vertical-align: baseline; box-sizing: border-box; display: inline; border-radius: 3px; word-break: normal; color: var(--wh-color-text-main); background-color: var(--wh-color-backlight-main);">runtimeOnly</code></p></td><td id="f687f05d" style="margin: 0px; padding: 16px 32px 16px 0px; border-top: 1px solid var(--wh-color-border-default); border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;JetBrains Sans&quot;, Inter, system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; vertical-align: top; color: rgb(25, 25, 28); letter-spacing: 0.024px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="article__p child" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: var(--wh-max-width-l); color: inherit;">Available at runtime but is not visible during compilation of any module.</p></td><br class="Apple-interchange-newline">
</body>
</html>

Source: https://kotlinlang.org/docs/gradle.html#dependency-types

**Comment by Raibaz** [comment]
Ah, you're right, those should probably be `api` rather than `implementation`.

And I'm also thinking this may also be the reason why maven users need to depend on `mockk-jvm` rather than `mockk` as they used to.

@aSemy what do you think?

**Comment by aSemy** [comment]
This makes sense! I think the `api(...)` definitions got lost during the Kotlin Multiplatform update. 

https://github.com/mockk/mockk/blob/7dc1169c6d59973fa2175bee561a35599e914af3/mockk/android/build.gradle.kts#L53-L55

It can be confusing having too many api defs, so only setting them in 'public' projects (`io.mockk:mockk` and `io.mockk:mock-android`, I think?) would help, and hopefully be clearer that they're the projects that are specifically for public consumption?

**Comment by Raibaz** [comment]
Yep, makes perfect sense to me.

**Comment by aSemy** [comment]
I'll make a PR.

Thanks for the investigation @SimonMarquis!

**Comment by SimonMarquis** [comment]
I'm glad it helped 😄

> Also, quick question, what was the reason to not make it is there a reason to not make `io.mockk:mockk-agent-jvm` an explicit transitive dependency of `io.mockk:mockk-android`? This would simplify the setup process and require only a single dependency.

Any comment on this? (sorry for including it in this issue, I can create a dedicated issue if you want me to).

**Comment by aSemy** [comment]
> I'm glad it helped 😄
> 
> > Also, quick question, what was the reason to not make it is there a reason to not make `io.mockk:mockk-agent-jvm` an explicit transitive dependency of `io.mockk:mockk-android`? This would simplify the setup process and require only a single dependency.
> 
> Any comment on this? (sorry for including it in this issue, I can create a dedicated issue if you want me to).

Sorry I'm a little bit lost in the dependencies, but I think that this was the case in v1.12.5

https://github.com/mockk/mockk/blob/7dc1169c6d59973fa2175bee561a35599e914af3/mockk/android/build.gradle.kts#L53-L55

But we recently updated the Kotlin Multiplatform plugin and it didn't get translated correctly

**Comment by SimonMarquis** [comment]
> `io.mockk:mockk` looks correct compared to 1.12.5 https://repo.maven.apache.org/maven2/io/mockk/mockk/1.12.5/mockk-1.12.5.pom

I think we never made the jump to this version because of missing `.so` shared libs at work.
In our setup, we only had a single dependency for pure jvm tests, and another one for android tests.
