### ISSUE TITLE
Missing mocked calls exception for Sealed class

### ISSUE THREAD

**Issue by AndriiZaliskyi** [mockk/mockk#938]
``` kotlin
val sealedClass = mockk<SealedClass>()
every { sealedClass.id } returns 0
```

### Expected Behavior

mockk for Sealed classes should work fine like on version 1.13.1

### Current Behavior

mockk for Sealed classes don't work

#### Context

* MockK version: 1.13.2
* OS: macOS Monterey 12.6
* Kotlin version: 1.7.10
* JDK version: JDK 11
* JUnit version: 4.13.2
* Type of test: unit test

#### Failure Logs

`io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock`

**Comment by jcgarciam-signavio** [comment]
Same happens for Sealed Interfaces my setup:

MockK version: 1.13.2
OS: Linux
Kotlin version: 1.7.10
JDK version: JDK 17
JUnit version: 5.9.1

Simple example:

 ```
@Test
    fun verify_bug_mockk_sealed_class_without_without_subclasses() {
        val theMock = mockk<SealedClassWithoutSubclasses>()
        every { theMock.property } returns "aValue"

//        It throws:
//        Can't instantiate proxy for class com............SealedClassWithoutSubclasses
//        io.mockk.MockKException: Can't instantiate proxy for class com.signavio.pi.dt.engine.interceptors.SealedClassWithoutSubclasses
    }

    @Test
    fun verify_bug_mockk_sealed_interface_without_subclasses() {
        val theMock = mockk<SealedInterfaceWithoutSubclasses>()
        every { theMock.property } returns "aValue"

//        It throws:
//        Can't instantiate proxy for class com............SealedInterface
//        io.mockk.MockKException: Can't instantiate proxy for class com.signavio.pi.dt.engine.interceptors.SealedInterface
    }

    @Test
    fun verify_bug_mockk_sealed_interface_with_subclasses() {
        val theMock = mockk<SealedInterfaceWithSubclasses>()
        every { theMock.property } returns "aValue"

//        It throws:
//        Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
//        io.mockk.MockKException: Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock
    }


sealed class SealedClassWithoutSubclasses {
    val property : String = "x"
}
sealed interface SealedInterfaceWithoutSubclasses {
    val property : String
}
sealed interface SealedInterfaceWithSubclasses {
    val property : String
}
class SIX1 : SealedInterfaceWithSubclasses {
    override val property: String
        get() = "X1 property"
}
```

**Comment by BOOMeranGG** [comment]
[jcgarciam-signavio](https://github.com/jcgarciam-signavio)
About ```Can't instantiate proxy for class ...```
This check was added in latest version of Mockk (ProxyMaker.kt file). So, you cannot initialize mock for sealed class without any subclasses. 
![image](https://user-images.githubusercontent.com/40336034/203055000-d0d61fbc-4786-4fec-8ff6-903dc93f8172.png)

About ```Missing mocked calls inside every { ... } block: make sure the object inside the block is a mock```
I got this exception when overrided mocking method. If there is no overrides it works fine.

To fix those tests you should **create mock from child** of sealed class.
