### ISSUE TITLE
Bug: Mocking getter of interface returning java.util.Locale causes NPE in Locale#hashCode

### ISSUE THREAD

**Issue by TheWishWithin** [mockk/mockk#94]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I'm mocking an interface method of `HttpServletRequest#getLocale` which is a simple getter for a `java.util.Locale`.
This should simply work an return my given Locale.

### Current Behavior

I'm mocking an interface method of `HttpServletRequest#getLocale` which is a simple getter for a `java.util.Locale`.
Doing that gives me a NullPointerException.
I guess that MockK tries to mock a default return object of type Locale and then fails? I have no idea.

### Failure Information (for bugs)

This seems clearly like a bug. Maybe because `Locale` is *final*.

#### Context

* MockK version: 1.8.3
* OS: Windows 10
* Kotlin version: 1.2.50
* JDK version: 1.7?
* Type of test: JUnit 5

#### Stack trace

```
java.lang.NullPointerException
	at java.util.Locale.hashCode(Locale.java:1978)
	at io.mockk.RecordedCall.hashCode(API.kt)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at io.mockk.impl.recording.PermanentMocker.describeCallTree(PermanentMocker.kt:98)
	at io.mockk.impl.recording.PermanentMocker.access$describeCallTree(PermanentMocker.kt:11)
	at io.mockk.impl.recording.PermanentMocker$mock$callTree$1.invoke(PermanentMocker.kt:28)
	at io.mockk.impl.recording.PermanentMocker$mock$callTree$1.invoke(PermanentMocker.kt:11)
	at io.mockk.impl.recording.CommonCallRecorder.safeExec(CommonCallRecorder.kt:66)
	at io.mockk.impl.log.SafeLog.exec(SafeLog.kt:10)
	at io.mockk.impl.recording.PermanentMocker.mock(PermanentMocker.kt:28)
	at io.mockk.impl.recording.states.RecordingState.mockPermanently(RecordingState.kt:115)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:32)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:45)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:47)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:25)
```

#### Minimal reproducible code (the gist of this issue)

I think that ```HttpServletRequest``` can be found in this dependency for Gradle:
```org.apache.tomcat.embed:tomcat-embed-core:8.5.28```

This is a snippet that causes this bug:
```kotlin
import java.util.Locale
import javax.servlet.http.HttpServletRequest

@Test
fun buggyBug() {
            val germany = Locale.GERMANY
            germany.hashCode() // Fine, no NPE
            val httpServletRequest: HttpServletRequest = mockk {
                every { this@mockk.locale } returns germany // Somewhere here we get an NPE
            }
}
```

Interface method of `HttpServletRequest`:
```
    /**
     * Returns the preferred <code>Locale</code> that the client will accept
     * content in, based on the Accept-Language header. If the client request
     * doesn't provide an Accept-Language header, this method returns the
     * default locale for the server.
     *
     * @return the preferred <code>Locale</code> for the client
     */
    public Locale getLocale();
```

Implementation of `Locale#hashCode`:
```
    @Override
    public int hashCode() {
        int hc = hashCodeValue;
        if (hc == 0) {
            hc = baseLocale.hashCode(); // This is where the NPE happens
            if (localeExtensions != null) {
                hc ^= localeExtensions.hashCode();
            }
            hashCodeValue = hc;
        }
        return hc;
    }
```

**Comment by TheWishWithin** [comment]
Actually, it doesn't even depend on this specific interface, it's clearly a problem with `Locale` as the following example has the same problem:

```
package foo.test

import io.mockk.every
import io.mockk.mockk
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import java.util.*

class LocaleTest {

    @Test
    fun shouldMockLocale() {
        val foo = mockk<Foo> {
            every { getLocale() } returns Locale.GERMANY
        }

        assertThat(foo.getLocale())
                .isEqualTo(Locale.GERMANY)
    }
}

interface Foo {

    fun getLocale(): Locale

}
```

**Comment by TheWishWithin** [comment]
Just found another problem: The same thing happens if I try to mock a method that returns `java.time.OffsetDateTime`

**Comment by TheWishWithin** [comment]
I think the problem is that in both cases, MockK wants to mock an OffsetDateTime or Locale for some reason, but uses the original hashCode implementation, which fails because the used fields are not initialized.

**Comment by oleksiyp** [comment]
Because of child mocking i.e. ability to chain mocking calls it's required to mock return value. 

Anyway checking this issue. Thanks for reporting

**Comment by oleksiyp** [comment]
The fix is on master branch, now it's a matter of releasing a new version of MockK. I'll do that before Monday

**Comment by oleksiyp** [comment]
Version 1.8.4 released, please check if everything ok and close the issue.

**Comment by TheWishWithin** [comment]
The bug is fixed in both cases, thank you very much!
