### ISSUE TITLE
java.lang.InstantiationError with slot() using data classes that inherit from a sealed class on jdk 17 (jdk 11 works)

### ISSUE THREAD

**Issue by u6f6o** [mockk/mockk#971]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

Using `slot` for data classes that inherit from a sealed class should work with java 17 and 11

### Current Behavior

It only works with java 11

### Failure Information (for bugs)

```
EventsTest > testSth() FAILED
    java.lang.InstantiationError at EventsTest.kt:19
```

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. git clone git@github.com:u6f6o/mock-slot-bug-v2.git
2. cd  mock-slot-bug-v2
3. ./gradlew test 
4. git checkout woring-with-java-11
5. ./gradlew test

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.2
* OS: Darwin MB-52-P14.fritz.box 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
* Kotlin version: 1.7.20
* JDK version: openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Homebrew (build 17.0.4.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.4.1+0, mixed mode, sharing)
* JUnit version: 5.8.1
* Type of test: unit test

**Comment by disco-Chris-Spoehr** [comment]
I believe I'm seeing related behavior when `any()` is set to match against a sealed class. Kotlin 1.7.10, mockk 1.13.2, JVM 17 target.

**Comment by WiSparky82** [comment]
I believe I'm seeing related behavior when any() is set to match against a sealed class. Kotlin 1.7.10, mockk 1.13.2, JVM 17 target.

**Comment by ygaller** [comment]
I think that 1.13.4 solves this issue (upgrading worked for me).

**Comment by u6f6o** [comment]
Yes, I can confirm, that 1.13.4 solves the issue!
