### ISSUE TITLE
`every` hangs on invoke of function type returning a value class

### ISSUE THREAD

**Issue by dmcg** [mockk/mockk#977]
### Expected Behavior

It sets an expectation

### Current Behavior

It waits for(low values of)ever

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.13.2
* OS: Mac
* Kotlin version: 1.7.10
* JDK version: 15
* JUnit version: 5.9.0
* Type of test: unit test 

#### Minimal reproducible code (the gist of this issue)

```kotlin
@JvmInline
value class Foo(val bar: String)

val f: () -> Foo = mockk()

@Test
fun `test value`() {
    every { f.invoke() } returns Foo("test")
    f.invoke()
}
```

See also https://stackoverflow.com/a/74414374/97777

**Comment by andreaevooq** [comment]
Same issue here!

**Comment by y9vad9** [comment]
I have the same issue with the interface that returns value class:
```kotlin
@JvmInline
value class UserId(val long: Long)

interface UsersRepository {
    suspend fun create(..): UserId
}

@Test fun test() {
   val userId = UserId(1)
    coEvery { usersRepository.createUser(any(), any(), any(), any()) }
            .returns(userId)
}
```
And it fails with the exception:
```
class java.lang.Long cannot be cast to class UserId (java.lang.Long is in module java.base of loader 'bootstrap'; UserId is in unnamed module of loader 'app')
java.lang.ClassCastException: class java.lang.Long cannot be cast to class io.timemates.backend.users.types.value.UserId (java.lang.Long is in module java.base of loader 'bootstrap'; UserId is in unnamed module of loader 'app')
```

**Comment by y9vad9** [comment]
very actual for me
